/* Eligibility precedes style scoring. Conservative checks, NOT a semantic truth oracle. */
'use strict';
const L=require('./library'),Cities=require('./city-scope');
function eligibility(answer,intent,records,request=''){const reasons=[];if(!answer||!answer.text)return{eligible:false,reasons:['missing-answer']};if(answer.notice==='conversation-only'&&intent.kind==='other'&&!(answer.sourceIds||[]).length)return{eligible:true,reasons:['conversation-only-not-a-factual-source-check']};const sources=(answer.sourceIds||[]).map(id=>records.find(r=>r.id===id));if(!sources.length||sources.some(r=>!r||!L.current(r)))reasons.push('missing-or-held-source');if(sources.some(r=>r&&!Cities.applies(r,intent.city)))reasons.push('city-or-jurisdiction-mismatch');const channel=/\b12306\b/i.test(request)?'12306':/MTR|机场快线|機場快綫/i.test(request)?'mtr-online-airport-express':null;if(channel&&sources.some(r=>r?.channels?.length&&!r.channels.includes(channel)))reasons.push('explicit-channel-mismatch');return{eligible:!reasons.length,reasons};}
function combineRisk(a,b){if(!a?.text||!b?.text)return null;const na=a.text.toLowerCase().replace(/\s/g,''),nb=b.text.toLowerCase().replace(/\s/g,'');if(na===nb||na.includes(nb)||nb.includes(na))return'duplicate';const negative=t=>/不支持|不可用|禁止|does not support|not supported|unavailable|prohibited/i.test(t),positive=t=>/支持|可使用|supports?|available|can use/i.test(t);if(negative(a.text)!==negative(b.text)&&(positive(a.text)||positive(b.text)))return'potential-support-conflict';
 // Candidate concatenation is withheld by default: simple presence checks cannot
 // prove that two numerical/channel claims are compatible.
 return'unverified-cross-candidate-combination';}
function select(local,generated,intent,request,records,Arbitration){const l=eligibility(local,intent,records,request),g=eligibility(generated,intent,records,request),a=l.eligible?local:null,b=g.eligible?generated:null;if(!a&&!b)return{held:true,guard:{local:l,generated:g,selected:'none'}};const decision=Arbitration.decide(a,b,intent,request);let mergeReason=null;if(decision.selected==='combined'){mergeReason=combineRisk(a,b);decision.selected=g.eligible?'deepseek':'tool';decision.reason+=' V6.5 不拼接未经冲突核验的两份候选。';}return{answer:Arbitration.apply(a,b,decision),decision,guard:{local:l,generated:g,mergeReason,selected:decision.selected,scope:'Source freshness/scope gates and conservative no-merge; not full semantic validation.'}};}
module.exports={eligibility,combineRisk,select};
