/* Browser shell: page actions and speech are one event stream. */
(function(){'use strict';
const E=TravelEngine,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=E.state(),server=false,serverRevision=0,queue=[],draining=false,generation=0,modelController=null,proposal=null,actor=null,syncError=false,startup=Promise.resolve();const history=[],callId=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);let cid=callId(),sessionId=null;
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),4500);}
async function api(p,b,signal){if(b&&['candidate','edit','evaluate','vote','rollback'].includes(p)&&!b.requestId)b={...b,requestId:callId()};const r=await fetch('/api/v5/'+p,{method:b===undefined?'GET':'POST',headers:b===undefined?{}:{'Content-Type':'application/json'},body:b===undefined?undefined:JSON.stringify(b),signal:signal||AbortSignal.timeout(35000)});let j;try{j=await r.json();}catch(_){throw Error('Node backend is not connected.');}if(!r.ok){const e=Error(j.error||'HTTP_'+r.status);e.data=j;throw e;}return j;}
const callOptions={api,onPacket:p=>{if(p.state&&p.revision>=serverRevision&&!queue.length&&!draining){state=p.state;serverRevision=p.revision;generation++;render();refine();}},onText:text=>commit({type:'text',text,channel:'voice'}),onCaption:text=>{$('interim').textContent=text;},onDraft:text=>{const b=$('speech-draft');b.dataset.text=E.clean(text,1500);$('speech-draft-text').textContent=b.dataset.text;b.classList.remove('hidden');},onState:s=>{const names={idle:'Ready when you are',ended:'Call ended / 通话已结束',connecting:'Connecting / 建立通话',speaking:'Speaking · 可随时点选或打断',listening:'Listening / 正在听你说',processing:'Updating your trip / 更新需求',waiting:'Still here / 等待你',reconnecting:'Reconnecting / 正在恢复连接',muted:'Microphone paused / 麦克风暂停',unavailable:'Voice unavailable / 可用文字与点选',permission_denied:'Microphone permission denied',voice_error:'Voice connection paused',audio_error:'Audio unavailable'};$('call-status').textContent=names[s.phase]||s.phase;$('orb').dataset.phase=s.phase;$('call-hint').textContent=s.detail|| (s.active?'You do not have to wait for my voice. Choose or interrupt anytime.':'Start a call. I’ll ask, listen, and build your plan with you.');for(const id of ['interrupt','mic','speaker','hangup'])$(id).classList.toggle('hidden',!s.active);$('start-call').classList.toggle('hidden',s.active);$('mic').textContent=s.muted?'恢复麦克风':'静音麦克风';$('speaker').textContent=s.output?'关闭播报':'开启播报';}};
let call=new TravelVoice.Call(callOptions);
function remember(){try{if($('remember').checked)localStorage.setItem('visit-china-v5-facts',JSON.stringify({facts:state.facts,tasks:state.tasks,language:state.language}));else localStorage.removeItem('visit-china-v5-facts');}catch(_){if($('remember').checked&&!remember.warned){remember.warned=true;toast('Browser storage unavailable; this session still works.');}}}
function render(){const r=E.reply(state);$('assistant-says').textContent=r.say;$('choices').innerHTML=r.options.map(o=>'<button data-choice="'+esc(o.id)+'">'+esc(o.label)+'</button>').join('');$('revision').textContent='rev '+state.revision;$('summary').innerHTML=r.summary.length?r.summary.map(t=>'<li>'+esc(t)+'</li>').join(''):'<li class="empty">Tell me a little about your trip. I’ll keep it here.</li>';$('known').textContent=[state.facts.airport,state.facts.terminal,state.facts.zone,state.facts.battery!==undefined?'Battery '+state.facts.battery+'%':'',state.facts.network].filter(Boolean).join(' · ');$('confirmation').textContent=state.confirmedRevision===state.revision?'✓ 已确认此版本 · 没有执行预订':'可直接说“确认”；新的需求会使旧确认失效。';$('policy-version').textContent='workflow '+r.policyVersion+' · pinned for this call';
 $('plan').innerHTML=r.plan.length?r.plan.map(p=>'<div class="step"><strong>'+esc(p.title)+'</strong><p>'+esc(p.reason)+'</p>'+(p.url?'<a href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer">Open provider ↗</a>':'')+'<button data-guide="'+esc(p.id)+'">查看指引与来源</button>'+'<button data-done="'+esc(p.id)+'">'+(p.status==='done'?'✓ 用户确认完成':'标记完成')+'</button></div>').join(''):'<p class="empty">Your actions will appear as we talk.</p>';
 $('extensions').innerHTML=r.suggestions.length?r.suggestions.map(x=>'<div class="extension"><p>'+esc(x.text)+'</p><a href="'+esc(x.url)+'" target="_blank" rel="noopener noreferrer">查看平台入口 ↗</a></div>').join(''):'<p class="empty">Relevant suggestions, never an automatic purchase.</p>';
 $('urgent').classList.toggle('hidden',!r.urgent&&state.facts.network!=='offline');$('urgent').textContent=r.urgent?'您好，我手机快没电了。请问能否帮我找到工作人员或询问哪里可以充电？谢谢。':'您好，我的手机无法上网。请问哪里可以咨询通信或网络服务？谢谢。';
 if(r.urgent){call.cancel();call.mute(true);}
 $('transcript').innerHTML=history.slice(-30).map(h=>'<div class="utterance"><small>'+esc(h.role)+' · '+esc(h.channel||'assistant')+'</small>'+esc(h.text)+'</div>').join('');$('turn-count').textContent=state.history.length;remember();
}
function speakReply(){const r=E.reply(state);if(call.active&&!r.urgent){call.language=state.language==='zh'?'zh-CN':$('voice-language').value;call.speak(r.spoken);}}
function commit(event){try{call.cancel({preserveInterim:true});modelController?.abort();proposal=null;$('proposal').classList.add('hidden');const old=state;state=E.apply(state,event);generation++;history.push({role:'You',channel:event.channel||'click',text:state.history.at(-1).text});history.push({role:'Companion',text:E.reply(state).say});render();speakReply();if(server){queue.push({event,requestId:callId(),generation,session_id:sessionId});drain();}else $('model-note').textContent='浏览器模式：状态在当前浏览器计算；DeepSeek 与五人审核需要本地 Node。';}catch(e){toast(e.message);}}
async function drain(){if(draining||!server)return;draining=true;await startup;while(queue.length){const job=queue[0];try{const out=await api('turn',{expectedRevision:serverRevision,requestId:job.requestId,event:job.event,session_id:job.session_id||sessionId});serverRevision=out.state.revision;queue.shift();if(job.generation===generation){state=out.state;render();}syncError=false;}catch(e){if(e.data?.state&&(job.retries||0)<2){job.retries=(job.retries||0)+1;serverRevision=e.data.state.revision;state=queue.reduce((current,entry)=>E.apply(current,entry.event),e.data.state);render();continue;}syncError=true;queue=[];if(e.data?.state){state=e.data.state;serverRevision=state.revision;generation++;render();}toast('未同步：'+e.message+'。已保留当前页面；重新建立通话后继续。');break;}}draining=false;if(!syncError){if(call.remote)call.sync();refine();}}
async function refine(){if(!server||!$('model-consent').checked||queue.length||draining)return;if(E.reply(state).urgent||['offline','poor'].includes(state.facts.network)){modelController?.abort();$('model-note').textContent='低电量或网络受限：暂停模型调用，保留文字与现场求助。';return;}const rev=serverRevision,gen=generation;modelController?.abort();modelController=new AbortController();$('model-note').textContent='DeepSeek 正在补充理解；可继续说话或点击，旧结果不会覆盖新选择。';try{const out=await api('refine',{revision:rev,modelConsent:true},modelController.signal);if(gen!==generation)return;proposal=out.proposal;$('model-note').textContent=out.mode==='deepseek'?'DeepSeek 已返回结构化提议。需要确认，不会自动改写已选行程。':'未配置或未授权模型，继续使用默认模式。';if(proposal&&Object.keys(proposal.facts).some(k=>state.facts[k]!==proposal.facts[k])){$('proposal').innerHTML='<strong>AI 补充理解</strong><p>'+esc(JSON.stringify(proposal.facts))+'</p><button id="adopt" class="primary">确认补充并继续</button>';$('proposal').classList.remove('hidden');}}catch(e){if(e.name!=='AbortError'&&gen===generation)$('model-note').textContent='模型回退：'+e.message+'。语音和点击流程仍可继续。';}}
async function begin(){if(!$('mic-consent').checked){$('consent-error').textContent='请先确认麦克风与语音服务同意。';return;}$('consent-dialog').close();
 const remote=$('voice-provider').value==='livekit';call.stop();call=remote?new TravelRealtime.Call(callOptions):new TravelVoice.Call(callOptions);
 state.language=$('voice-language').value.startsWith('zh')?'zh':'en';history.push({role:'Companion',text:E.reply(state).say});render();cid=callId();
 if(!remote){call.start({consent:true,language:$('voice-language').value});call.speak(E.reply(state).spoken);}
 if(server){const gen=generation;startup=api('begin',{reset:false,restore:$('remember').checked,facts:state.facts,language:state.language}).then(out=>{serverRevision=out.state.revision;sessionId=out.session_id;if(gen===generation){state={...out.state,language:state.language};render();}});try{await startup;}catch(e){call.stop();toast(e.message);return;}}
 if(remote)try{await call.start({consent:true});}catch(e){toast(e.message==='VOICE_ACCESS_REQUIRED'?'请先在 Operations 登录已授权账号，再开始 LiveKit 通话。':'LiveKit: '+e.message);}
}
$('start-call').onclick=()=>{$('consent-error').textContent='';$('consent-dialog').showModal();};$('consent-cancel').onclick=()=>$('consent-dialog').close();$('consent-start').onclick=begin;
$('interrupt').onclick=()=>call.interruptAndListen();$('mic').onclick=()=>call.mute(!call.muted);$('speaker').onclick=()=>call.setOutput(!call.output);$('hangup').onclick=()=>{call.stop();queue=queue.filter(job=>job.event.channel!=='voice');modelController?.abort();if(server)api('end',{}).catch(()=>{});};
$('send').onclick=()=>{const t=$('message').value;if(!t.trim())return;$('message').value='';commit({type:'text',text:t,channel:'text'});};$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('send').click();}};
$('choices').onclick=e=>{const b=e.target.closest('[data-choice]');if(b)commit({type:'choice',id:b.dataset.choice,channel:'click'});};$('confirm').onclick=()=>commit({type:'confirm',channel:'click'});
$('proposal').onclick=async e=>{if(e.target.id!=='adopt'||!proposal)return;call.cancel();try{const out=await api('adopt',{hash:proposal.hash});state=out.state;serverRevision=state.revision;generation++;if(call.remote)call.sync();proposal=null;$('proposal').classList.add('hidden');render();speakReply();}catch(err){toast(err.message);}};
$('new-trip').onclick=async()=>{if(!confirm('清空当前旅程与本浏览器保存的选择？不会删除运营审核记录。'))return;call.stop();generation++;modelController?.abort();queue=[];history.length=0;$('speech-draft').dataset.text='';$('speech-draft').classList.add('hidden');state=E.state();if(server){try{const out=await api('begin',{reset:true});state=out.state;serverRevision=state.revision;}catch(e){toast(e.message);}}render();};
$('speech-draft-use').onclick=()=>{const b=$('speech-draft');$('message').value=[$('message').value,b.dataset.text].filter(Boolean).join(' ');b.dataset.text='';b.classList.add('hidden');$('message').focus();};$('speech-draft-discard').onclick=()=>{$('speech-draft').dataset.text='';$('speech-draft').classList.add('hidden');};$('remember').onchange=remember;$('model-consent').onchange=()=>{if(!$('model-consent').checked){modelController?.abort();proposal=null;$('proposal').classList.add('hidden');}else refine();};
$('feedback').onclick=async()=>{if(!server){toast('反馈需要本机 Node；本浏览器演示不会制造共享工单。');return;}try{await api('feedback',{key:cid+':'+state.revision+':'+$('feedback-category').value,category:$('feedback-category').value,note:'User selected feedback category for this conversation revision.'});toast('已加入待改进队列；不会自动修改工作流。');}catch(e){toast(e.message);}};
let guideTask=null,guideController=null;function guides(task){guideTask=task||null;$('guide-refresh').disabled=!server||!task;$('guide-result').innerHTML='';guideController?.abort();if(server)api('turn',{requestId:callId(),expectedRevision:serverRevision,event:{type:'context',view:'guide:'+String(task||'library')}}).catch(()=>{});const mapping={metro:['sh-metro'],rail:['rail-passport'],payment:['wechat-fee','alipay-app'],power:['pvg-arrival'],connection:['pvg-arrival'],cash:['pvg-arrival'],help:['pvg-arrival','beijing-arrival']};let rows=ArrivalData.sources;if(mapping[task])rows=rows.filter(x=>mapping[task].includes(x.id));if(task)rows=rows.filter(x=>x.city==='China'||!x.city||x.city===state.facts.city);if(!rows.length){$('guides-list').innerHTML='<p>请先告诉我城市；本地资料缺少对应城市的已核对指南。不会直接套用上海的位置。</p>';$('guides-dialog').showModal();return;}$('guides-list').innerHTML=rows.map(r=>'<article class="guide"><h3>'+esc(r.title)+'</h3><p>'+esc(r.summaryZh||r.summary)+'</p><p class="muted">'+esc(r.publisher)+' · published '+esc(r.published||'see publisher')+' · reviewed '+esc(r.reviewedAt||'not reviewed')+'</p><div class="links"><a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">完整原文 ↗</a>'+((r.media||[]).length&&!E.reply(state).urgent?'<button data-photo="'+esc(r.id)+'" class="light">查看官方照片</button>':'')+'</div><div id="photo-'+esc(r.id)+'"></div><p class="muted">这是已保存的摘要，不是本轮实时抓取；可在当前卡片选择联网核验。</p></article>').join('');$('guides-dialog').showModal();}
$('guides-list').onclick=e=>{const b=e.target.closest('[data-photo]');if(!b)return;const r=ArrivalData.sources.find(s=>s.id===b.dataset.photo);$('photo-'+r.id).innerHTML=(r.media||[]).map(m=>'<img loading="lazy" referrerpolicy="no-referrer" src="'+esc(m.url)+'" alt="'+esc(m.alt)+'"><p class="muted">'+esc(m.rights)+'</p>').join('');b.disabled=true;};
$('nav-guides').onclick=()=>guides();$('guides-close').onclick=()=>{guideController?.abort();$('guides-dialog').close();};$('nav-call').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
$('plan').onclick=e=>{const g=e.target.closest('[data-guide]');if(g)return guides(g.dataset.guide);const d=e.target.closest('[data-done]');if(d){commit({type:'outcome',task:d.dataset.done,channel:'click'});toast('已记录你的完成确认；不是平台交易回执。');}};
$('nav-ops').onclick=()=>{if(call.active)call.mute(true);modelController?.abort();TravelOps.open({api,server,toast,esc,onActor:a=>{actor=a;}});};$('ops-close').onclick=()=>$('ops-dialog').close();
setInterval(()=>{const sec=call.startedAt?Math.floor((Date.now()-call.startedAt)/1000):0;$('clock').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');},1000);
window.addEventListener('beforeunload',()=>{call.stop();modelController?.abort();});
try{const saved=JSON.parse(localStorage.getItem('visit-china-v5-facts')||'null');if(saved){state.facts=E.validatePatch(saved.facts);state.tasks=(saved.tasks||[]).filter(x=>E.TASKS.includes(x));state.language=saved.language==='zh'?'zh':'en';$('remember').checked=true;}}catch(_){}
render();if(location.protocol!=='file:')api('status',undefined,AbortSignal.timeout(4000)).then(r=>{server=r.server===true;actor=r.actor;serverRevision=r.state.revision;if(r.state.revision)state=r.state;else state.policy=r.policy;$('mode').textContent='本机后端已连接 · 真实接口';const option=$('voice-provider').querySelector('[value=livekit]');option.disabled=!r.voice?.configured;option.textContent=r.voice?.configured?'LiveKit WebRTC（需登录）':'LiveKit WebRTC（待配置）';if(r.voice?.configured)$('voice-provider').value='livekit';render();}).catch(()=>{$('mode').textContent='浏览器体验 · 后端未连接';});else $('mode').textContent='单文件体验 · 无后端';
$('guide-refresh').onclick=async()=>{if(!guideTask||!server)return;guideController?.abort();guideController=new AbortController();const rev=serverRevision,gen=generation,task=guideTask;$('guide-result').textContent='正在核对官网；浏览资料不会改变旅程事实或抢话。';try{const out=await api('guide',{task,revision:rev,live:true,modelConsent:$('model-consent').checked},guideController.signal);if(gen!==generation||task!==guideTask)return;$('guide-result').innerHTML='<article class="guide"><h3>'+esc(out.node.title)+'</h3><p>'+esc({"travel-inspiration":'游玩参考',"provider-information":'服务机构信息',"official-guidance":'官方指引'}[out.sourceClass])+' · '+esc(out.node.mode==='deepseek-grounded'?'依据本次来源整理':'已保存摘要，来源检查结果见下方')+'</p><ol>'+out.node.actions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol><p>'+esc(out.node.uncertainty)+'</p>'+out.node.evidence.map(e=>'<p><a href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">'+esc(e.title)+'</a><br>'+esc({fetched:'已获取网页',changed_or_unmatched:'页面已变化，原摘要待复核',unavailable:'无法获取网页',not_requested:'未请求联网'}[e.liveStatus]||e.liveStatus)+' · '+esc(e.cacheHit?'缓存命中':'本次检查')+' · '+esc(e.checkedAt||'未联网')+' '+esc(e.error||'')+'</p>').join('')+'<p>没有核验实时库存，也没有执行预订。</p>'+ (out.notice?'<p>'+esc(out.notice)+'</p>':'')+'</article>';}catch(e){if(e.name!=='AbortError')$('guide-result').textContent='未完成核验：'+e.message;}};
// Public development hooks expose only non-secret state; useful for reproducible UI tests.
window.TravelApp={getState:()=>JSON.parse(JSON.stringify(state)),getCall:()=>({active:call.active,phase:call.phase,muted:call.muted}),commit};
})();
