/* Browser shell: page actions and speech are one event stream. */
(function(){'use strict';
const E=TravelEngine,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selectedSources=[];
let resetting=false,connectionPending=location.protocol!=='file:',modelConfigured=false,captionText='',state={...E.state(),language:'zh'},server=false,serverRevision=0,queue=[],draining=false,generation=0,modelController=null,proposal=null,actor=null,syncError=false,startup=Promise.resolve(),endRequest=Promise.resolve();const callId=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);let cid=callId(),sessionId=null;
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.add('hidden'),4500);}
async function api(p,b,signal){if(b&&['candidate','edit','evaluate','vote','rollback'].includes(p)&&!b.requestId)b={...b,requestId:callId()};const r=await fetch('/api/v5/'+p,{method:b===undefined?'GET':'POST',headers:b===undefined?{}:{'Content-Type':'application/json'},body:b===undefined?undefined:JSON.stringify(b),signal:signal||AbortSignal.timeout(35000)});let j;try{j=await r.json();}catch(_){throw Error('Node backend is not connected.');}if(!r.ok){const e=Error(j.error||'HTTP_'+r.status);e.data=j;throw e;}return j;}
const callOptions={api,onPacket:p=>{if(p.state&&p.revision>=serverRevision&&!queue.length&&!draining){state=p.state;serverRevision=p.revision;generation++;render();refine();}},onText:text=>commit({type:'text',text,channel:'voice'}),onCaption:text=>{captionText=text;renderCaption();},onLevel:value=>{$('voice-level').value=value;},onDraft:text=>{const b=$('speech-draft');b.dataset.text=E.clean(text,1500);$('speech-draft-text').textContent=b.dataset.text;b.classList.remove('hidden');},onState:s=>{const names={idle:'Ready when you are',ended:'Call ended / 通话已结束',connecting:'Connecting / 建立通话',loading:'加载本机语音模型…',speaking:'Speaking · 可随时点选或打断',listening:'Listening / 正在听你说',processing:'Updating your trip / 更新需求',waiting:'Still here / 等待你',reconnecting:'Reconnecting / 正在恢复连接',muted:'Microphone paused / 麦克风暂停',unavailable:'Voice unavailable / 可用文字与点选',permission_denied:'Microphone permission denied',voice_error:'Voice connection paused',audio_error:'Audio unavailable'};$('library-hangup').classList.toggle('hidden',!s.active);$('call-status').textContent=names[s.phase]||s.phase;$('orb').dataset.phase=s.phase;$('voice-phase').textContent=names[s.phase]||s.phase;$('voice-level-wrap').classList.toggle('hidden',!(call?.local&&s.phase==='listening'));$('finish-speech').disabled=s.phase!=='listening'||typeof call?.finish!=='function';$('voice-provider').disabled=s.active;$('call-panel').classList.toggle('in-call',s.active);document.querySelector('.conversation').classList.toggle('voice-active',s.active);$('voice-language').disabled=Boolean(s.active&&call?.remote);$('call-hint').textContent=s.detail|| (s.active?'说完停顿约 1.4 秒自动发送；回复后继续听，也可随时打断或点选。':'聊天已开启。直接打字，或开始通话后说出你的整体安排。');for(const id of ['interrupt','mic','speaker','hangup'])$(id).classList.toggle('hidden',!s.active);$('start-call').classList.toggle('hidden',s.active);$('mic').textContent=s.muted?'恢复麦克风':'静音麦克风';$('speaker').textContent=s.output?'关闭播报':'开启播报';}};
let call=new TravelVoice.Call(callOptions);
function remember(){try{if($('remember').checked)localStorage.setItem('visit-china-v5-facts',JSON.stringify(E.memory(state)));else localStorage.removeItem('visit-china-v5-facts');}catch(_){if($('remember').checked&&!remember.warned){remember.warned=true;toast('Browser storage unavailable; this session still works.');}}}
function renderCaption(){const last=[...state.history].reverse().find(h=>h.channel==='voice');$('interim').textContent=captionText||last?.text||'识别到的文字会显示在这里。';$('caption-kind').textContent=captionText?'实时字幕 · 尚未发送':last?'最近已发送 · 已保留在对话中':'等待说话';$('live-caption').classList.toggle('has-words',Boolean(captionText||last));}
function render(){renderCaption();const r=E.reply(state);$('assistant-says').textContent=r.say;$('choices').innerHTML=r.options.map(o=>'<button data-choice="'+esc(o.id)+'">'+esc(o.label)+'</button>').join('');$('revision').textContent='rev '+state.revision;$('summary').innerHTML=r.summary.length?r.summary.map(t=>'<li>'+esc(t)+'</li>').join(''):'<li class="empty">Tell me a little about your trip. I’ll keep it here.</li>';$('known').textContent=[state.facts.airport,state.facts.terminal,state.facts.zone,state.facts.battery!==undefined?'Battery '+state.facts.battery+'%':'',state.facts.network].filter(Boolean).join(' · ');$('confirmation').textContent=state.confirmedRevision===state.revision?'✓ 已确认此版本 · 没有执行预订':'可直接说“确认”；新的需求会使旧确认失效。';$('policy-version').textContent='workflow '+r.policyVersion+' · pinned for this call';
 $('plan').innerHTML=r.plan.length?r.plan.map(p=>'<div class="step"><strong>'+esc(p.title)+'</strong><p>'+esc(p.reason)+'</p>'+(p.url?'<a href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer">Open provider ↗</a>':'')+'<button data-guide="'+esc(p.id)+'">查看指引与来源</button>'+'<button data-done="'+esc(p.id)+'">'+(p.status==='done'?'✓ 用户确认完成':'标记完成')+'</button></div>').join(''):'<p class="empty">Your actions will appear as we talk.</p>';
 $('extensions').innerHTML=r.suggestions.length?r.suggestions.map(x=>'<div class="extension"><p>'+esc(x.text)+'</p><a href="'+esc(x.url)+'" target="_blank" rel="noopener noreferrer">查看平台入口 ↗</a></div>').join(''):'<p class="empty">Relevant suggestions, never an automatic purchase.</p>';
 $('urgent').classList.toggle('hidden',!r.urgent&&state.facts.network!=='offline');$('urgent').textContent=r.urgent?'您好，我手机快没电了。请问能否帮我找到工作人员或询问哪里可以充电？谢谢。':'您好，我的手机无法上网。请问哪里可以咨询通信或网络服务？谢谢。';
 if(r.urgent){call.cancel();call.mute(true);}
 const transcript=$('transcript'),nearBottom=transcript.scrollHeight-transcript.scrollTop-transcript.clientHeight<80;
 const content=conversationHTML(r);
 $('need-badges').innerHTML=r.plan.map(p=>'<span class="need-badge">'+(p.status==='done'?'✓ ':'○ ')+esc(p.title)+'</span>').join('')+(state.facts.flight==='booked'?'<span class="need-badge">✓ '+(state.language==='zh'?'机票已订 · 你提供':'Flight booked · you reported')+'</span>':'');
 $('output-language').value=state.outputLanguage||'auto';document.documentElement.lang=state.language==='zh'?'zh-CN':'en';
 refreshModel();window.TravelLibraryUI?.render();

 if(transcript.innerHTML!==content){transcript.innerHTML=content;if(nearBottom)latest();else $('jump-latest').classList.remove('hidden');}
 $('initial-request').textContent=state.initialRequest?.text||'第一段需求会固定在这里，后续补充不会覆盖它。';$('initial-request').classList.toggle('empty',!state.initialRequest);
 $('context-note').textContent=state.history.length?'已经结合 '+state.history.length+' 轮记录；下方为当前需求，修改会更新此处。':'说出整体需求后，再逐步补充细节。';
 $('turn-count').textContent=state.history.length;renderPreferences();remember();
}
function speakReply(){const r=E.reply(state);if(call.active&&!r.urgent){call.outputLanguage=state.language==='zh'?'zh-CN':'en-US';call.speak(r.spoken);}}
function commit(event){if(resetting)return;if(event.type==='text')event={...event,sourceIds:[...selectedSources]};try{call.cancel({preserveInterim:true});modelController?.abort();proposal=null;$('proposal').classList.add('hidden');state=E.apply(state,event);generation++;render();latest();if(!(canAssist()&&event.type==='text'))speakReply();else if(call.active)call.emit?.('processing','正在结合对话与资料回答，可随时打断。');if(server||connectionPending){queue.push({event,requestId:callId(),generation,session_id:sessionId});drain();}else $('model-note').textContent='免费模式：规则回复即时显示。DeepSeek 尚未接通；不会产生模型费用。';}catch(e){toast(e.message);}}
async function drain(){if(draining||!server)return;draining=true;try{await startup;}catch(e){draining=false;queue=[];toast('通话尚未建立：'+e.message);return;}while(queue.length){const job=queue[0];try{const out=await api('turn',{expectedRevision:serverRevision,requestId:job.requestId,event:job.event,session_id:job.session_id||sessionId});serverRevision=out.state.revision;queue.shift();if(job.generation===generation){state=out.state;render();}syncError=false;}catch(e){if(e.data?.state&&(job.retries||0)<2){job.retries=(job.retries||0)+1;serverRevision=e.data.state.revision;state=queue.reduce((current,entry)=>E.apply(current,entry.event),e.data.state);render();continue;}syncError=true;queue=[];if(e.data?.state){state=e.data.state;serverRevision=state.revision;generation++;render();}toast('未同步：'+e.message+'。已保留当前页面；重新建立通话后继续。');break;}}draining=false;if(!syncError){if(call.remote)call.sync();refine();}}
function canAssist(){return server&&modelConfigured&&actor&&$('model-consent').checked&&!E.reply(state).urgent&&!['offline','poor'].includes(state.facts.network);}
function refreshModel(){
 const status=!server?'免费模式 · 后端未连接':!modelConfigured?'免费模式 · DeepSeek 未配置':!actor?'DeepSeek 已配置 · 请登录':!$('model-consent').checked?'DeepSeek 已就绪 · 等待授权':'DeepSeek · 语音与文字共用';
 $('model-status').textContent=status;$('shared-model-status').textContent=status;$('shared-model-consent').checked=$('model-consent').checked;
 $('shared-model-detail').textContent=status+'。'+(!server?'当前公开页面提供免费规则对话和资料检索。接入持久后端后，两个入口共用同一个 DeepSeek 客户端。':'同一个服务端模型配置供对话、语音和资料整理使用。');
 $('model-facts').disabled=!canAssist();
}
async function refine(){
 const last=state.history.at(-1);if(!canAssist()||queue.length||draining||!last||last.revision!==state.revision||last.assistance||!['text','voice'].includes(last.channel))return;
 const rev=serverRevision,gen=generation;modelController?.abort();const ctl=new AbortController();modelController=ctl;
 $('model-note').textContent='DeepSeek 正在结合本次对话与可用资料回答…';
 let timedOut=false;const timer=setTimeout(()=>{timedOut=true;ctl.abort();},32000);
 try{const out=await api('assist',{revision:rev,modelConsent:true},ctl.signal);if(gen!==generation||ctl.signal.aborted)return;
  if(out.answer){state.history.at(-1).assistance=out.answer;render();latest();$('model-note').textContent=out.answer.mode==='deepseek'?'DeepSeek 已回答；资料范围与引用见本轮消息。':'资料不足或涉及费用：保留来源说明与固定工具。';
   if(call.active&&!call.muted){call.outputLanguage=state.language==='zh'?'zh-CN':'en-US';const speech=out.answer.text;call.speak(speech.length>state.policy.maxSpokenChars?(state.language==='zh'?'回答和参考资料已放在本轮对话中。':'The answer and references are in this conversation. ')+E.reply(state).spoken:speech);}
  }else speakReply();
 }catch(e){if(gen===generation){$('model-note').textContent=ctl.signal.aborted?'本轮 AI 回答已停止；可以继续输入。':'模型暂不可用，保留免费对话与资料：'+e.message;if(!ctl.signal.aborted||timedOut)speakReply();}}
 finally{clearTimeout(timer);}
}
async function refineFacts(){if(!server||!modelConfigured||!$('model-consent').checked||queue.length||draining)return;if(E.reply(state).urgent||['offline','poor'].includes(state.facts.network)){modelController?.abort();$('model-note').textContent='低电量或网络受限：暂停模型调用，保留文字与现场求助。';return;}const rev=serverRevision,gen=generation;modelController?.abort();modelController=new AbortController();$('model-note').textContent='DeepSeek 正在补充理解；可继续说话或点击，旧结果不会覆盖新选择。';try{const out=await api('refine',{revision:rev,modelConsent:true},modelController.signal);if(gen!==generation)return;proposal=out.proposal;$('model-note').textContent=out.mode==='deepseek'?'DeepSeek 已返回结构化提议。需要确认，不会自动改写已选行程。':'未配置或未授权模型，继续使用默认模式。';if(proposal&&Object.keys(proposal.facts).some(k=>state.facts[k]!==proposal.facts[k])){$('proposal').innerHTML='<strong>AI 补充理解</strong><p>'+esc(JSON.stringify(proposal.facts))+'</p><button id="adopt" class="primary">确认补充并继续</button>';$('proposal').classList.remove('hidden');}}catch(e){if(e.name!=='AbortError'&&gen===generation)$('model-note').textContent='模型回退：'+e.message+'。语音和点击流程仍可继续。';}}
async function begin(){if(!$('mic-consent').checked){$('consent-error').textContent='请先确认麦克风与语音服务同意。';return;}$('consent-dialog').close();
 const remote=$('voice-provider').value==='livekit';call.stop();call=remote?new TravelRealtime.Call(callOptions):$('voice-provider').value==='local'?new TravelLocalVoice.Call(callOptions):new TravelVoice.Call(callOptions);
 state.language=state.outputLanguage&&state.outputLanguage!=='auto'?state.outputLanguage:$('voice-language').value.startsWith('zh')?'zh':'en';render();cid=callId();
 if(!remote){call.start({consent:true,language:$('voice-language').value});call.outputLanguage=state.language==='zh'?'zh-CN':'en-US';call.speak(E.reply(state).spoken);}
 const gen=generation;startup=connectionReady.then(async()=>{if(!server)return;const out=await api('begin',{reset:false,restore:$('remember').checked,facts:state.facts,memory:E.memory(state),language:state.language,outputLanguage:state.outputLanguage});serverRevision=out.state.revision;sessionId=out.session_id;if(gen===generation){state={...out.state,language:state.language};render();}});try{await startup;}catch(e){call.stop();toast(e.message);return;}

 if(remote)try{await call.start({consent:true});}catch(e){toast(e.message==='VOICE_ACCESS_REQUIRED'?'请先在 Operations 登录已授权账号，再开始 LiveKit 通话。':'LiveKit: '+e.message);}
}
$('start-call').onclick=()=>{$('consent-error').textContent='';$('consent-dialog').showModal();};$('consent-cancel').onclick=()=>$('consent-dialog').close();$('consent-start').onclick=begin;
$('finish-speech').onclick=()=>call.finish?.();
$('interrupt').onclick=()=>{modelController?.abort();call.interruptAndListen();};$('mic').onclick=()=>call.mute(!call.muted);$('speaker').onclick=()=>call.setOutput(!call.output);$('hangup').onclick=()=>{call.stop();queue=queue.filter(job=>job.event.channel!=='voice');modelController?.abort();if(server)endRequest=api('end',{}).catch(()=>{});};
$('send').onclick=()=>{const t=$('message').value;if(!t.trim())return;$('message').value='';commit({type:'text',text:t,channel:'text'});};$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('send').click();}};
$('choices').onclick=e=>{const b=e.target.closest('[data-choice]');if(b)commit({type:'choice',id:b.dataset.choice,channel:'click'});};$('confirm').onclick=()=>commit({type:'confirm',channel:'click'});
$('proposal').onclick=async e=>{if(e.target.id!=='adopt'||!proposal)return;call.cancel();try{const out=await api('adopt',{hash:proposal.hash});state=out.state;serverRevision=state.revision;generation++;if(call.remote)call.sync();proposal=null;$('proposal').classList.add('hidden');render();speakReply();}catch(err){toast(err.message);}};
async function freshChat(reset=false){if(resetting)return;if(reset&&!confirm('重置本次对话和行程？所选偏好会保留。Reset this conversation?'))return;resetting=true;$('send').disabled=true;call.stop();generation++;modelController?.abort();queue=[];proposal=null;$('proposal').classList.add('hidden');$('speech-draft').dataset.text='';$('speech-draft').classList.add('hidden');captionText='';selectedSources=[];window.TravelLibraryUI?.view(false);$('message').value='';const lang=state.outputLanguage||'auto',prefs=reset||$('keep-preferences').checked?state.preferences||{}:{};state=E.state();state.outputLanguage=lang;state.language=lang==='auto'?($('voice-language').value.startsWith('zh')?'zh':'en'):lang;state.preferences=prefs;
 try{await connectionReady;await startup;await endRequest;while(draining)await new Promise(r=>setTimeout(r,20));if(server){const out=await api('begin',{reset:true,language:state.language,outputLanguage:lang,preferences:prefs});state=out.state;serverRevision=state.revision;sessionId=out.session_id;}}catch(e){toast(e.message);}resetting=false;$('send').disabled=false;cid=callId();render();renderPreferences();latest();$('call-status').textContent='聊天已就绪 · Chat ready';$('voice-phase').textContent='文字聊天已开启 · 可开始语音';$('message').focus({preventScroll:true});toast(reset?'本次聊天已重置，偏好已保留。':'新聊天已开启，旧行程已清空。');}
$('new-trip').onclick=()=>freshChat();$('new-chat-top').onclick=()=>freshChat();$('reset-chat').onclick=()=>freshChat(true);$('reset-chat-top').onclick=()=>freshChat(true);

$('speech-draft-use').onclick=()=>{const b=$('speech-draft');$('message').value=[$('message').value,b.dataset.text].filter(Boolean).join(' ');b.dataset.text='';b.classList.add('hidden');$('message').focus();};$('speech-draft-discard').onclick=()=>{$('speech-draft').dataset.text='';$('speech-draft').classList.add('hidden');};$('remember').onchange=remember;$('model-consent').onchange=()=>{refreshModel();if(!$('model-consent').checked){modelController?.abort();if(call.active&&call.phase==='processing')call.interruptAndListen();proposal=null;$('proposal').classList.add('hidden');}else if(!modelConfigured)$('model-note').textContent='DeepSeek 接口已预留，但当前站点没有配置服务端密钥。免费聊天照常可用。';else refine();};
$('feedback').onclick=async()=>{if(!server){toast('反馈需要本机 Node；本浏览器演示不会制造共享工单。');return;}try{await api('feedback',{key:cid+':'+state.revision+':'+$('feedback-category').value,category:$('feedback-category').value,note:'User selected feedback category for this conversation revision.'});toast('已加入待改进队列；不会自动修改工作流。');}catch(e){toast(e.message);}};
let guideTask=null,guideController=null;function guides(task){if(task&&['boston','new york','tokyo','paris','london','东京','巴黎','伦敦'].includes(String(state.facts.city||'').toLowerCase())){guideTask=null;$('guide-refresh').disabled=true;$('guide-result').innerHTML='';$('guides-list').innerHTML='<p>当前资料库未收录这个目的地的已核对指南。请使用对话卡上的平台入口查询。No verified guide for this destination is stored; use the provider links in the conversation.</p>';$('guides-dialog').showModal();return;}guideTask=task||null;$('guide-refresh').disabled=!server||!task;$('guide-result').innerHTML='';guideController?.abort();if(server)api('turn',{requestId:callId(),expectedRevision:serverRevision,event:{type:'context',view:'guide:'+String(task||'library')}}).catch(()=>{});const mapping={metro:['sh-metro'],rail:['rail-passport'],payment:['wechat-fee','alipay-app'],power:['pvg-arrival'],connection:['pvg-arrival'],cash:['pvg-arrival'],help:['pvg-arrival','beijing-arrival']};let rows=ArrivalData.sources;if(mapping[task])rows=rows.filter(x=>mapping[task].includes(x.id));if(task)rows=rows.filter(x=>x.city==='China'||!x.city||x.city===state.facts.city);if(!rows.length){$('guides-list').innerHTML='<p>请先告诉我城市；本地资料缺少对应城市的已核对指南。不会直接套用上海的位置。</p>';$('guides-dialog').showModal();return;}$('guides-list').innerHTML=rows.map(r=>'<article class="guide"><h3>'+esc(r.title)+'</h3><p>'+esc(r.summaryZh||r.summary)+'</p><p class="muted">'+esc(r.publisher)+' · published '+esc(r.published||'see publisher')+' · reviewed '+esc(r.reviewedAt||'not reviewed')+'</p><div class="links"><a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">完整原文 ↗</a>'+((r.media||[]).length&&!E.reply(state).urgent?'<button data-photo="'+esc(r.id)+'" class="light">查看官方照片</button>':'')+'</div><div id="photo-'+esc(r.id)+'"></div><p class="muted">这是已保存的摘要，不是本轮实时抓取；可在当前卡片选择联网核验。</p></article>').join('');$('guides-dialog').showModal();}
$('guides-list').onclick=e=>{const b=e.target.closest('[data-photo]');if(!b)return;const r=ArrivalData.sources.find(s=>s.id===b.dataset.photo);$('photo-'+r.id).innerHTML=(r.media||[]).map(m=>'<img loading="lazy" referrerpolicy="no-referrer" src="'+esc(m.url)+'" alt="'+esc(m.alt)+'"><p class="muted">'+esc(m.rights)+'</p>').join('');b.disabled=true;};
$('nav-guides').onclick=()=>guides();$('guides-close').onclick=()=>{guideController?.abort();$('guides-dialog').close();};$('nav-call').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});
$('plan').onclick=e=>{const g=e.target.closest('[data-guide]');if(g)return guides(g.dataset.guide);const d=e.target.closest('[data-done]');if(d){commit({type:'outcome',task:d.dataset.done,channel:'click'});toast('已记录你的完成确认；不是平台交易回执。');}};
$('nav-ops').onclick=async()=>{if(call.active)call.mute(true);modelController?.abort();$('nav-ops').disabled=true;try{await startup;await endRequest;while(draining||queue.length)await new Promise(resolve=>setTimeout(resolve,20));}catch(e){toast(e.message);}finally{$('nav-ops').disabled=false;}TravelOps.open({api,server,toast,esc,onActor:(a,model)=>{actor=a;modelConfigured=Boolean(model?.configured);refreshModel();}});};$('ops-close').onclick=()=>$('ops-dialog').close();
setInterval(()=>{const sec=call.startedAt?Math.floor((Date.now()-call.startedAt)/1000):0;$('clock').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');},1000);
window.addEventListener('beforeunload',()=>{call.stop();modelController?.abort();});
try{const saved=JSON.parse(localStorage.getItem('visit-china-v5-facts')||'null');if(saved){state=E.restoreMemory(saved);$('voice-language').value=state.language==='zh'?'zh-CN':'en-US';$('remember').checked=true;$('output-language').value=state.outputLanguage||'auto';}}catch(_){}
function providerNote(){const local=$('voice-provider').value==='local';$('voice-note').textContent=local?'开源 Vosk · 本机转写，无语音 API 费用。首次下载约 40–45 MB；播报使用本机系统语音。':'浏览器语音无需本项目的付费密钥，但识别可能由浏览器在线服务提供。';$('consent-note').textContent=local?'音频在此设备的浏览器内处理，不上传语音。模型下载后会缓存；本项目不保存录音。':'浏览器可能将音频发送至其识别服务。LiveKit 仅在另行配置后可用，相关服务可能收费。';}
 $('voice-provider').onchange=providerNote;providerNote();
const connectionReady=location.protocol!=='file:'?api('status',undefined,AbortSignal.timeout(4000)).then(r=>{server=r.server===true;modelConfigured=Boolean(r.model?.configured);actor=r.actor;serverRevision=r.state.revision;if(r.state.revision&&!state.revision&&generation===0)state=r.state;else state.policy=r.policy;$('mode').textContent='本机后端已连接 · 真实接口';const option=$('voice-provider').querySelector('[value=livekit]');option.disabled=!r.voice?.configured;option.textContent=r.voice?.configured?'LiveKit WebRTC（需登录）':'LiveKit WebRTC（待配置）';render();}).catch(()=>{$('mode').textContent='浏览器体验 · 后端未连接';}).finally(()=>{connectionPending=false;if(server&&queue.length)drain();else if(!server)queue=[];}):Promise.resolve();if(location.protocol==='file:')$('mode').textContent='单文件体验 · 无后端';
$('guide-refresh').onclick=async()=>{if(!guideTask||!server)return;guideController?.abort();guideController=new AbortController();const rev=serverRevision,gen=generation,task=guideTask;$('guide-result').textContent='正在核对官网；浏览资料不会改变旅程事实或抢话。';try{const out=await api('guide',{task,revision:rev,live:true,modelConsent:$('model-consent').checked},guideController.signal);if(gen!==generation||task!==guideTask)return;$('guide-result').innerHTML='<article class="guide"><h3>'+esc(out.node.title)+'</h3><p>'+esc({"travel-inspiration":'游玩参考',"provider-information":'服务机构信息',"official-guidance":'官方指引'}[out.sourceClass])+' · '+esc(out.node.mode==='deepseek-grounded'?'依据本次来源整理':'已保存摘要，来源检查结果见下方')+'</p><ol>'+out.node.actions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol><p>'+esc(out.node.uncertainty)+'</p>'+out.node.evidence.map(e=>'<p><a href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">'+esc(e.title)+'</a><br>'+esc({fetched:'已获取网页',changed_or_unmatched:'页面已变化，原摘要待复核',unavailable:'无法获取网页',not_requested:'未请求联网'}[e.liveStatus]||e.liveStatus)+' · '+esc(e.cacheHit?'缓存命中':'本次检查')+' · '+esc(e.checkedAt||'未联网')+' '+esc(e.error||'')+'</p>').join('')+'<p>没有核验实时库存，也没有执行预订。</p>'+ (out.notice?'<p>'+esc(out.notice)+'</p>':'')+'</article>';}catch(e){if(e.name!=='AbortError')$('guide-result').textContent='未完成核验：'+e.message;}};

function offerHTML(h){const lang=h.language||state.language,zh=lang==='zh';return TravelTools.offers(h,lang).map(group=>'<section class="offer-group"><div class="offer-heading"><strong>'+esc(group.title)+'</strong><span class="demo-tag">'+(zh?'模拟推荐':'Sample offers')+'</span></div><p class="offer-warning">'+esc(group.disclaimer)+'</p><div class="offer-grid">'+group.items.map(item=>'<article class="offer-card"><strong>'+esc(item.name)+'</strong><div class="route">'+esc(item.route)+'</div><div class="details">'+esc(item.detail)+'</div><div class="price">'+esc(item.price)+'</div></article>').join('')+'</div><a class="offer-link" href="'+esc(group.url)+'" target="_blank" rel="noopener noreferrer">'+(zh?'去平台查询真实结果 ↗':'Check real options on provider ↗')+'</a></section>').join('');}
function assistanceHTML(h){if(!h.assistance)return '';const a=h.assistance,labels={deepseek:'DeepSeek · 共用对话助手',restored:'历史回答 · 未重新核验','source-gap':'资料适用范围','fixed-guidance':'固定规则与工具'};return '<div class="assistant-answer"><small>'+esc(labels[a.mode]||'资料说明')+'</small><p>'+esc(a.text)+'</p></div>';}
function sourceHTML(h){const rows=TravelLibrary.choose(h,h.context?.city);if(!rows.length)return '';const used=TravelLibrary.ids(h.assistance?.sourceIds);return '<details class="turn-sources" '+(h.sourceIds?.length?'open':'')+'><summary>▧ '+(h.language==='zh'?'本轮参考资料':'Sources for this turn')+' · '+rows.length+'</summary>'+rows.map(r=>'<div class="turn-source"><button data-source-detail="'+esc(r.id)+'">'+esc(r.title)+' ↗</button><small>'+esc(TravelLibrary.label(r,h.language))+(used.includes(r.id)?' · AI 引用':'')+'</small><p>'+esc(TravelLibrary.summary(r,h.language).slice(0,360))+'</p></div>').join('')+'<small>'+(h.language==='zh'?'已保存资料，非本轮联网核验；具体适用条件请查看原文。':'Saved reference material, not live verification. Check the original for applicability.')+'</small></details>';}
function conversationHTML(r){if(!state.history.length)return '<div class="utterance companion"><small>旅行助手 / Companion</small><p>'+esc(r.say)+'</p><p class="muted">'+(state.language==='zh'?'聊天已开启。先说整体需求，接下来我会逐步询问。下方也有酒店、机票和高铁示例可以体验。':'Chat is ready. Tell me your overall plan; I will ask one question at a time. Try the hotel, flight and rail examples below.')+'</p></div>';
 return state.history.map(h=>{const taxi=TravelTools.taxiRequest(h.text,h.context?.city);return '<div class="utterance user"><small>你 / You · '+esc({voice:'🎙 语音',click:'点选',text:'文字'}[h.channel]||h.channel)+'</small><p>'+esc(h.text)+'</p></div>'+(h.reply?'<div class="utterance companion"><small>旅行助手 / Companion</small>'+assistanceHTML(h)+'<p>'+esc(h.reply)+'</p>'+sourceHTML(h)+offerHTML(h)+(taxi?'<button class="taxi-inline" data-taxi-city="'+esc(taxi.city)+'" data-taxi-km="'+esc(taxi.km??'')+'">🚕 '+(h.language==='zh'?'估算出租车费':'Estimate taxi fare')+(taxi.km?' · '+esc(taxi.km)+' km':'')+'</button>':'')+'</div>':'');}).join('');}
function latest(){const box=$('transcript'),anchor=box.querySelector('.user:last-of-type')||[...box.querySelectorAll('.user')].at(-1);if(anchor)box.scrollTop+=anchor.getBoundingClientRect().top-box.getBoundingClientRect().top-8;else box.scrollTop=0;$('jump-latest').classList.add('hidden');}
$('jump-latest').onclick=latest;$('transcript').onscroll=()=>{const t=$('transcript');const last=[...t.querySelectorAll('.user')].at(-1);$('jump-latest').classList.toggle('hidden',!last||last.getBoundingClientRect().top>=t.getBoundingClientRect().top-30);};
$('output-language').onchange=()=>commit({type:'language',language:$('output-language').value,channel:'click'});
$('voice-language').onchange=()=>{if(!call.active||call.remote)return;call.cancel({preserveInterim:true});call.stop();call=$('voice-provider').value==='local'?new TravelLocalVoice.Call(callOptions):new TravelVoice.Call(callOptions);call.outputLanguage=state.language==='zh'?'zh-CN':'en-US';call.start({consent:true,language:$('voice-language').value});if(!call.local)call.listen();};
document.querySelector('.scenario-buttons').onclick=e=>{const kind=e.target.closest('[data-demo]')?.dataset.demo;if(!kind)return;const zh=state.language==='zh',examples={restaurant:['我在上海，想找吃饭的饭店，请给几个推荐。','I am in Shanghai. Please suggest some restaurants.'],hotel:['我计划和父母去上海，机票已订，需要酒店。','I am planning a Shanghai trip with my parents. My flight is booked and I need a hotel.'],flight:['我计划去上海，需要机票，住宿也还没订。','I am planning to visit Shanghai. I need a flight and a hotel.'],rail:['我想看从上海虹桥到杭州东的高铁票，日期还没确定。','Show me train tickets from Shanghai Hongqiao to Hangzhou East; the date is not decided.']};commit({type:'text',text:examples[kind][zh?0:1],channel:'text'});latest();};
function taxiLanguage(){const zh=state.language==='zh',labels={city:['城市','City'],km:['行驶距离（公里）','Road distance (km)'],wait:['低速 / 等候（分钟）','Low-speed / waiting (minutes)'],extra:['已知附加费用（元）','Known extra fees (CNY)'],large:['上海 16 元起租车型','Shanghai vehicle with ¥16 base fare'],fuel:['北京燃油附加费 1 元（按实车确认）','Beijing ¥1 fuel fee (check the vehicle)'],peak:['北京高峰等候计费（7–9、17–19）','Beijing peak waiting rate (7–9, 17–19)']};for(const el of document.querySelectorAll('[data-taxi-label]'))el.textContent=labels[el.dataset.taxiLabel][zh?0:1];$('taxi-title').textContent=zh?'🚕 出租车费用估算':'🚕 Taxi fare estimate';$('taxi-scope').textContent=zh?'日间巡游出租车、单程估算；不适用于网约车一口价、夜间或跨城包车。':'Daytime metered taxi, one-way estimate. Excludes ride-hailing fixed fares, night trips and intercity charters.';$('taxi-calculate').textContent=zh?'估算车费':'Estimate fare';}
function openTaxi(city,km){taxiLanguage();$('taxi-city').value=TravelTools.tariffs[city]?city:'';$('taxi-km').value=km??'';$('taxi-result').innerHTML='';taxiCity();$('taxi-dialog').showModal();if(km&&TravelTools.tariffs[city])calculateTaxi();else $('taxi-km').focus();}
function taxiCity(){const sh=$('taxi-city').value==='Shanghai',bj=$('taxi-city').value==='Beijing';$('taxi-large-row').classList.toggle('hidden',!sh);$('taxi-fuel-row').classList.toggle('hidden',!bj);$('taxi-peak-row').classList.toggle('hidden',!bj);}
$('taxi-city').onchange=()=>{taxiCity();$('taxi-result').innerHTML='';};
$('taxi-form').addEventListener('input',()=>$('taxi-result').innerHTML='');
function calculateTaxi(){const zh=state.language==='zh',tr=(a,b)=>zh?a:b;try{const fare=TravelTools.taxi({city:$('taxi-city').value,km:$('taxi-km').value,wait:$('taxi-wait').value,extra:$('taxi-extra').value,large:$('taxi-large').checked,fuel:$('taxi-fuel').checked,peak:$('taxi-peak').checked});const rows=[[tr('起租价（含 3 公里）','Base fare (first 3 km)'),fare.base],[tr('超起租里程（含超 15 公里加价）','Distance beyond 3 km (includes surcharge beyond 15 km)'),fare.distance],[tr('低速 / 等候','Low-speed / waiting'),fare.waiting],[tr('燃油附加','Fuel surcharge'),fare.fuel],[tr('你填写的附加费用','Extra fees you entered'),fare.extra]];$('taxi-result').innerHTML='<div class="fare-total">≈ ¥'+fare.total.toFixed(2)+'</div><p>'+esc(tr('距离变化 ±10% 时，约 ','If distance varies ±10%: '))+'¥'+fare.low+'–'+fare.high+'</p><table>'+rows.map(row=>'<tr><td>'+esc(row[0])+'</td><td>¥'+row[1].toFixed(2)+'</td></tr>').join('')+'</table><p class="muted">'+esc(tr('按 '+fare.km+' 公里、连续里程近似计算，计价器进位可能不同。超 15 公里部分加计 50%。上海可能有经营者/节假日运价浮动；未包含未填写的路桥费等附加费用。','Based on '+fare.km+' km using continuous distance; meter increments may differ. The distance beyond 15 km adds 50%. Shanghai operator/holiday adjustments and any extras not entered are excluded.'))+'</p><p>'+esc(tr('先对照路线里程、计价器和票据。高于估算不直接代表宰客，可核对绕行、堵车和附加费。','Compare road distance, the meter and receipt. A higher fare alone does not prove overcharging; check detours, traffic and extras.'))+'</p><p class="muted"><a href="'+esc(fare.source)+'" target="_blank" rel="noopener noreferrer">'+esc(fare.publisher)+' ↗</a> · '+fare.checkedAt+'</p>';}catch(e){$('taxi-result').textContent=tr('请选择上海或北京；距离 0.1–300 公里、等候 0–180 分钟、附加费用 0–1000 元。','Choose Shanghai or Beijing. Distance: 0.1–300 km; waiting: 0–180 minutes; extras: ¥0–1,000.');}}
$('taxi-form').onsubmit=e=>{e.preventDefault();calculateTaxi();};$('taxi-close').onclick=()=>$('taxi-dialog').close();$('open-taxi').onclick=()=>openTaxi(state.facts.city,null);
$('transcript').onclick=e=>{const b=e.target.closest('[data-taxi-city]');if(b)openTaxi(b.dataset.taxiCity,b.dataset.taxiKm||null);};


const preferenceGroups={budget:{label:['预算','Budget'],values:{economy:['经济实惠','Economy'],comfort:['舒适优先','Comfort']}},pace:{label:['节奏','Pace'],values:{relaxed:['轻松慢游','Relaxed'],full:['多看多玩','Packed']}},diet:{label:['饮食','Food'],values:{vegetarian:['素食选择','Vegetarian'],local:['当地风味','Local food']}}};
function preferencesMarkup(){const zh=state.language==='zh';return Object.entries(preferenceGroups).map(([key,g])=>'<div class="preference-group"><span>'+esc(g.label[zh?0:1])+'</span>'+Object.entries(g.values).map(([value,label])=>'<button type="button" data-pref-key="'+key+'" data-pref-value="'+value+'" aria-pressed="'+String(state.preferences?.[key]===value)+'">'+esc(label[zh?0:1])+'</button>').join('')+'</div>').join('');}
function renderPreferences(){if(typeof preferenceGroups==='undefined')return;const markup=preferencesMarkup();$('preference-options').innerHTML=markup;$('preferences-mobile').innerHTML=markup;const zh=state.language==='zh';$('chat-preferences').innerHTML=Object.entries(state.preferences||{}).map(([key,value])=>'<button class="pref-chip" data-pref-key="'+key+'" data-pref-value="'+value+'" title="Click to remove preference">'+esc(preferenceGroups[key].label[zh?0:1])+': '+esc(preferenceGroups[key].values[value][zh?0:1])+' ×</button>').join('');try{if($('keep-preferences').checked)localStorage.setItem('visit-china-v5-preferences',JSON.stringify(state.preferences||{}));else localStorage.removeItem('visit-china-v5-preferences');}catch(_){} }
function choosePreference(e){const b=e.target.closest('[data-pref-key]');if(!b)return;const preferences={...state.preferences};if(preferences[b.dataset.prefKey]===b.dataset.prefValue)delete preferences[b.dataset.prefKey];else preferences[b.dataset.prefKey]=b.dataset.prefValue;commit({type:'preferences',preferences,channel:'click'});}
for(const id of ['preference-options','preferences-mobile','chat-preferences'])$(id).onclick=choosePreference;
$('keep-preferences').onchange=renderPreferences;$('preferences-open').onclick=()=>{$('preferences-mobile').innerHTML=preferencesMarkup();$('preferences-dialog').showModal();};$('preferences-close').onclick=()=>$('preferences-dialog').close();
$('recommend-now').onclick=()=>{const zh=state.language==='zh',needs=state.tasks.filter(x=>['hotel','flight','rail','restaurant'].includes(x));if(!needs.length){toast(zh?'先告诉我目的地，以及需要酒店、车票还是餐厅。':'Tell me your destination and whether you need a hotel, tickets or restaurants.');$('message').focus({preventScroll:true});return;}const names={hotel:['需要酒店','need a hotel'],flight:['需要机票','need a flight'],rail:['推荐火车票','train options'],restaurant:['推荐饭店','restaurant options']};commit({type:'text',text:(zh?'请按当前偏好重新推荐：':'Please recommend again using my preferences: ')+needs.map(x=>names[x][zh?0:1]).join(zh?'，':', '),channel:'text'});};
try{const prefs=JSON.parse(localStorage.getItem('visit-china-v5-preferences')||'null');if(prefs){state.preferences=E.preferences(prefs);$('keep-preferences').checked=true;}}catch(_){}
renderPreferences();$('message').focus({preventScroll:true});

render();
// Public development hooks expose only non-secret state; useful for reproducible UI tests.
window.TravelApp={getState:()=>JSON.parse(JSON.stringify(state)),getSourceIds:()=>[...selectedSources],addSource:id=>{if(!TravelLibrary.get(id))return false;if(selectedSources.includes(id))return true;if(selectedSources.length>=3){toast('每轮最多参考 3 份资料，请先移除一份。');return false;}selectedSources.push(id);return true;},removeSource:id=>{selectedSources=selectedSources.filter(x=>x!==id);},refreshModel,refineFacts,getCall:()=>({active:call.active,phase:call.phase,muted:call.muted}),commit};
})();
