'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function sourceCommit(){if(process.env.VERCEL_GIT_COMMIT_SHA||process.env.GITHUB_SHA)return process.env.VERCEL_GIT_COMMIT_SHA||process.env.GITHUB_SHA;try{return require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch(_){return null;}}
const root=path.join(__dirname,'..'),out=path.join(root,'dist');fs.mkdirSync(out,{recursive:true});
fs.cpSync(path.join(root,'skills/shanghai-metro-guide'),path.join(out,'skills/shanghai-metro-guide'),{recursive:true});
// Preserve the complete previous evidence workspace. It is not silently replaced by the voice UI.
require('../v4/build');const old=path.join(out,'v4');fs.mkdirSync(old,{recursive:true});for(const n of ['index.html','style.css','app.js','core.js','data.js','corpus.js','build-info.json'])fs.copyFileSync(path.join(out,n),path.join(old,n));
for(const n of ['index.html','style.css','engine.js','voice.js','app.js','ops.js','realtime.js','local-voice.js','travel-tools.js','metro.js','library.js','library-ui.js'])fs.copyFileSync(path.join(__dirname,n),path.join(out,n));fs.copyFileSync(path.join(root,'v4/data.js'),path.join(out,'v4-data.js'));
fs.copyFileSync(path.join(root,'node_modules/livekit-client/dist/livekit-client.umd.js'),path.join(out,'livekit.js'));
fs.copyFileSync(path.join(root,'node_modules/livekit-client/LICENSE'),path.join(out,'LiveKit-LICENSE.txt'));
fs.copyFileSync(require('../tools/prepare-vosk.cjs')(),path.join(out,'vosk.js'));
fs.copyFileSync(path.join(root,'runtime/voice-models/vosk-worker.js'),path.join(out,'vosk-worker.js'));
for(const name of ['Vosk-Browser-LICENSE.txt','Vosk-Browser-NOTICE.txt'])fs.copyFileSync(path.join(root,'third-party',name),path.join(out,name));
fs.mkdirSync(path.join(out,'models'),{recursive:true});
for(const name of ['en-us.tar.gz','zh-cn.tar.gz'])fs.copyFileSync(path.join(root,'runtime/voice-models',name),path.join(out,'models',name));
let html=fs.readFileSync(path.join(out,'index.html'),'utf8').replace('<link rel="stylesheet" href="style.css">','<style>'+fs.readFileSync(path.join(out,'style.css'),'utf8')+'</style>');for(const n of ['engine','travel-tools','metro','voice','local-voice','realtime','v4-data','core','corpus','library','ops','app','library-ui']){const js=fs.readFileSync(path.join(out,n+'.js'),'utf8');if(/<\/script/i.test(js))throw Error('INLINE_SCRIPT_BOUNDARY');html=html.replace('<script src="'+n+'.js"></script>','<script>'+js+'</script>');}html=html.replace('<script src="livekit.js"></script>','').replace('<option value="local">','<option value="local" disabled>');fs.writeFileSync(path.join(out,'Visit_China_AI_V5_Demo.html'),html);
const files={};for(const n of ['index.html','style.css','engine.js','voice.js','app.js','ops.js','realtime.js','v4-data.js','livekit.js','local-voice.js','travel-tools.js','metro.js','library.js','library-ui.js','core.js','corpus.js','vosk.js','vosk-worker.js','models/en-us.tar.gz','models/zh-cn.tar.gz'])files[n]=crypto.createHash('sha256').update(fs.readFileSync(path.join(out,n))).digest('hex');fs.writeFileSync(path.join(out,'build-info.json'),JSON.stringify({version:'5.6.0',sourceCommit:sourceCommit(),builtAt:new Date().toISOString(),files,scope:'Browser Vosk ASR runs locally without paid APIs. System local voices handle playback when available. Cloud chat runs through a stateless Vercel Function with server-side credentials; shared operations/SSO still need persistent Node backend. Real human microphone quality is not measured.'},null,2));console.log('V5 built; V4 retained under dist/v4.');
