'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function sourceCommit(){if(process.env.VERCEL_GIT_COMMIT_SHA||process.env.GITHUB_SHA)return process.env.VERCEL_GIT_COMMIT_SHA||process.env.GITHUB_SHA;try{return require('node:child_process').execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch(_){return null;}}
const root=path.join(__dirname,'..'),out=path.join(root,'dist');fs.mkdirSync(out,{recursive:true});
// Preserve the complete previous evidence workspace. It is not silently replaced by the voice UI.
require('../v4/build');const old=path.join(out,'v4');fs.mkdirSync(old,{recursive:true});for(const n of ['index.html','style.css','app.js','core.js','data.js','corpus.js','build-info.json'])fs.copyFileSync(path.join(out,n),path.join(old,n));
for(const n of ['index.html','style.css','engine.js','voice.js','app.js','ops.js','realtime.js'])fs.copyFileSync(path.join(__dirname,n),path.join(out,n));fs.copyFileSync(path.join(root,'v4/data.js'),path.join(out,'v4-data.js'));
fs.copyFileSync(path.join(root,'node_modules/livekit-client/dist/livekit-client.umd.js'),path.join(out,'livekit.js'));
fs.copyFileSync(path.join(root,'node_modules/livekit-client/LICENSE'),path.join(out,'LiveKit-LICENSE.txt'));
let html=fs.readFileSync(path.join(out,'index.html'),'utf8').replace('<link rel="stylesheet" href="style.css">','<style>'+fs.readFileSync(path.join(out,'style.css'),'utf8')+'</style>');for(const n of ['engine','voice','realtime','v4-data','ops','app']){const js=fs.readFileSync(path.join(out,n+'.js'),'utf8');if(/<\/script/i.test(js))throw Error('INLINE_SCRIPT_BOUNDARY');html=html.replace('<script src="'+n+'.js"></script>','<script>'+js+'</script>');}html=html.replace('<script src="livekit.js"></script>','');fs.writeFileSync(path.join(out,'Visit_China_AI_V5_Demo.html'),html);
const files={};for(const n of ['index.html','style.css','engine.js','voice.js','app.js','ops.js','realtime.js','v4-data.js','livekit.js'])files[n]=crypto.createHash('sha256').update(fs.readFileSync(path.join(out,n))).digest('hex');fs.writeFileSync(path.join(out,'build-info.json'),JSON.stringify({version:'5.2.0',sourceCommit:sourceCommit(),builtAt:new Date().toISOString(),files,scope:'Static preview only. LiveKit requires configured Node backend and separate media worker; SQLite needs a persistent local volume. Real microphone and SSO have not been validated.'},null,2));console.log('V5 built; V4 retained under dist/v4.');
