'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),http=require('node:http'),O=require('./operations');
test('issue APIs isolate visitors, require admin writes, enforce summary/replay consent and save model replay as evaluation',async t=>{
 let state=O.initial(),mode='summary',calls=0;const users=Object.fromEntries(['admin','reviewer1'].map(name=>[name,{role:name==='admin'?'admin':'reviewer',salt:'fixture',hash:crypto.scryptSync('test-pass','fixture',32).toString('hex')}]));const env={OPS_USERS_JSON:JSON.stringify(users),OPS_SESSION_SECRET:'fixture-secret-long-enough-32-chars',DEEPSEEK_API_KEY:'fixture-provider-key'},store={read:async()=>structuredClone(state),mutate:async fn=>{const n=structuredClone(state),result=fn(n);state=n;return result;}};
 const handler=require('./ops-api').createOps({env,store,fetcher:async()=>{calls++;const value=mode==='summary'?{need:'浦东机场到上海站地铁',problem:'原回答不完整',hypothesis:'可能是路线识别问题',evidenceNeeded:'核对地铁来源',nextAction:'使用当前工具回放'}:{intent:{kind:'metro',origin:'浦东国际机场',destination:'上海火车站',city:'Shanghai',confidence:.9},text:'',source_ids:[]};return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}}));}});
 const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const url='http://127.0.0.1:'+server.address().port;let jar={};async function req(body,path='/api/ops'){const r=await fetch(url+path,{method:body?'POST':'GET',headers:{cookie:Object.values(jar).join('; '),'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const c=r.headers.get('set-cookie');if(c)jar[c.split('=')[0]]=c.split(';')[0];return{status:r.status,body:await r.json()};}
 await req(null,'/api/ops?view=library');const issue=await req({action:'feedback-case-submit',chat:'test-chat-id',answerId:'test-answer-id',category:'wrong_route',comment:'缺少换乘步骤',shareContext:true,context:[{question:'浦东机场到上海火车站乘地铁怎样走',answer:'旧答案',language:'zh'}]});assert.equal(issue.status,200);const id=issue.body.result.id;assert.equal((await req()).body.feedbackCases,undefined);assert.equal((await req({action:'trial-issue'})).status,403);
 const owner=jar.vc_visit;delete jar.vc_visit;await req(null,'/api/ops?view=library');assert.equal((await req({action:'feedback-case-delete',id})).status,403);jar.vc_visit=owner;
 await req({action:'login',username:'reviewer1',password:'test-pass'});assert.equal((await req({action:'case-skill',id,version:1})).status,403);assert.deepEqual((await req()).body.trialCodes,[]);
 await req({action:'login',username:'admin',password:'test-pass'});assert.equal((await req({action:'case-summarize',id,version:1})).body.error,'MODEL_CONSENT_REQUIRED');assert.equal(calls,0);const summary=await req({action:'case-summarize',id,version:1,modelConsent:true});assert.equal(summary.status,200);assert.match(summary.body.result.need,/浦东/);mode='replay';const replay=await req({action:'case-replay',id,version:2,modelConsent:true});assert.equal(replay.status,200,JSON.stringify(replay.body));assert.equal(replay.body.result.kind,'metro');assert.ok(replay.body.result.answer.includes('人民广场'));assert.equal(state.executions.at(-1).dataset,'evaluation');assert.equal((await req({action:'case-update',id,version:2,status:'closed',category:'wrong_route',note:'查看回放'})).status,409);
 const trial=await req({action:'trial-issue',label:'体验',days:7,maxTurns:2});assert.match(trial.body.result.code,/^VC-/);assert.ok(!JSON.stringify((await req()).body).includes(trial.body.result.code));assert.ok(!JSON.stringify(state.audit).includes(trial.body.result.code));assert.equal((await req({action:'feedback-case-delete',id})).status,200);assert.equal(state.feedbackCases.length,0);
});
