(function(g,f){const x=f();if(typeof module==='object')module.exports=x;else g.Arrival5=x;})(globalThis,function(){
'use strict';
const baseline={id:'baseline',battery:10,failures:2,priority:'hotel'};
const initial=()=>({city:'',stage:'unknown',flight:'unknown',hotel:'unknown',hotelName:'',airport:'',terminal:'',zone:'',battery:null,network:'unknown',wallet:'unknown',topic:'general',ask:'city',needs:[],special:[],skip:[],revision:0,language:'en'});
function clean(x){return String(x||'').replace(/\bsk-[\w-]+/g,'[key removed]').replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,'[email removed]').replace(/\b(?:\d[ -]?){13,19}\b/g,'[number removed]').replace(/(passport|护照|otp|验证码|password|密码)\s*[:：]\s*\S+/gi,'$1: [removed]').slice(0,2000);}
const patterns={emergency:/(?:cannot|can.t|unable to) breathe|unconscious|severe bleeding|medical emergency|chest pain|on fire|being attacked|无法呼吸|昏迷|严重出血|胸痛|着火|被袭击|救护车/i,policy:/visa|immigration|service fee|spending limit|lost.{0,8}passport|手续费|限额|签证|免签|护照.{0,5}(丢|遗失)|财付通|tenpay|200.{0,8}(?:yuan|rmb|元)/i,power:/battery|charg|power.?bank|充电|没电|电量/i,connection:/wi.?fi|\bsim\b|internet|network|offline|网络|断网|没网|流量/i,luggage:/luggage|store.{0,10}bags|bag storage|寄存|存包/i,metro:/metro|subway|地铁/i,cash:/\bcash\b|exchange|coins?|换汇|现金|换钱|硬币|零钱/i,rail:/\btrain\b|rail|12306|高铁|火车/i,transfer:/taxi|transfer|ride.?hail|car rental|接送|打车|出租车|租车/i,explore:/poster|museum|attraction|sightsee|architecture|near.{0,10}hotel|things to do|海报|周边|景点|博物馆|建筑|美食/i};
function detect(t){for(const [k,re]of Object.entries(patterns))if(re.test(t)&&!(k==='emergency'&&/not an emergency|no emergency|不是紧急|没有着火/i.test(t)))return k;return 'general';}
function update(prev,input){const s=JSON.parse(JSON.stringify(prev||initial())),t=clean(input);s.revision++;s.language=/[\u4e00-\u9fff]/.test(t)?'zh':'en';let city='';if(/shanghai|上海|\bpvg\b|浦东|虹桥/i.test(t))city='Shanghai';else if(/beijing|北京|\bpek\b|\bpkx\b/i.test(t))city='Beijing';else if(/hangzhou|杭州/i.test(t))city='Hangzhou';else if(/chengdu|成都/i.test(t))city='Chengdu';
if(city&&s.city&&city!==s.city){Object.assign(s,{airport:'',terminal:'',zone:'',hotelName:'',hotel:'unknown',flight:'unknown',stage:'unknown',topic:'general',needs:[],skip:[]});}if(city)s.city=city;
const a=t.match(/\b(PVG|SHA|PEK|PKX)\b/i);if(a)s.airport=a[1].toUpperCase();else if(/浦东/.test(t))s.airport='PVG';else if(/虹桥/.test(t))s.airport='SHA';const term=t.match(/\bT\s*([123])\b|([123])号航站楼/i);if(term)s.terminal='T'+(term[1]||term[2]);if(/public arrivals|public area|landside|公共到达|公共区域/i.test(t))s.zone='public';else if(/airside|安检内/i.test(t))s.zone='restricted';else if(/baggage claim|行李提取/i.test(t))s.zone='baggage';
if(/already (?:landed|arrived)|just (?:landed|arrived)|at the airport|刚到|已到|落地了|抵达了/i.test(t)){s.stage='arrived';s.flight='booked';}if(/at (?:my|the) hotel|checked in|在酒店|入住了/i.test(t)){s.stage='in_city';s.hotel='booked';s.flight='booked';}
const clauses=t.split(/[,;.，。；]|\bbut\b|\band\b/i);for(const c of clauses){if(/flight|机票/i.test(c)){if(/not.{0,15}book|haven.t.{0,10}book|unbooked|no flight|未订|没.{0,6}订/i.test(c)){s.flight='unbooked';s.stage='planning';}else if(/booked|bought|已订|订好/i.test(c))s.flight='booked';}if(/hotel|room|酒店|住宿/i.test(c)){if(/not.{0,15}book|haven.t.{0,10}book|unbooked|no hotel|未订|没.{0,6}订/i.test(c))s.hotel='unbooked';else if(/booked|reserved|已订|订好/i.test(c))s.hotel='booked';}}
const h=t.match(/(?:my hotel is|hotel name(?: is)?|酒店名(?:字)?(?:是)?|我住在)\s*[:：]?\s*([^\n.。]{2,80})/i);if(h&&!/^(?:unbooked|not booked|booked|unknown)$/i.test(h[1].trim())){s.hotelName=h[1].trim();s.hotel='booked';}
const b=t.match(/(\d{1,3})\s*%/);if(b)s.battery=Math.min(100,+b[1]);if(/no (?:internet|network)|offline|没网|断网/i.test(t))s.network='offline';else if(/poor connection|weak signal|弱网|信号差/i.test(t))s.network='poor';else if(/internet works|online now|good network|网络正常/i.test(t))s.network='online';if(/no (?:alipay|wallet)|没有.{0,3}(支付宝|钱包)/i.test(t))s.wallet='unavailable';else if(/wallet works|alipay works|支付宝能用/i.test(t))s.wallet='available';
if(/skip|later|稍后|跳过/i.test(t)){s.skip=[...new Set([...s.skip,s.ask])];s.topic='general';}else if(/resolved|problem solved|解决了|好了谢谢/i.test(t)){s.topic='general';}else{const topic=detect(t);if(topic!=='general')s.topic=topic;else if(/flight|hotel.{0,10}book|机票|酒店已订|酒店未订/i.test(t))s.topic='general';}
for(const [k,re]of Object.entries(patterns))if(k!=='emergency'&&re.test(t))s.needs=[...new Set([...s.needs,k])].slice(-8);if(/parents|wheelchair|stroller|vegetarian|special|poster|父母|轮椅|婴儿|素食|特殊|海报/i.test(t))s.special=[...s.special,t].slice(-5);return s;}
function reply(s,p=baseline){const z=s.language==='zh',T=(en,zh)=>z?zh:en;let text='',question='',chips=[],cards=[],sources=[],ask='general',mode='guided',priority='normal';
if(s.topic==='emergency')return{text:T('Seek immediate on-site help. In mainland China: medical 120, police 110, fire 119. Give your actual location or ask staff to call. No call has been placed.','请立即寻求现场帮助。在中国境内：医疗急救120、警方110、火警119。告知实际位置，无法拨打时请工作人员协助。这里尚未拨打电话。'),question:'',chips:[],cards:['emergency'],sources:['urgent'],ask:'emergency',priority:'urgent',mode};
if(s.battery!==null&&s.battery<=p.battery)return{text:T('Let’s preserve your battery first. Pause maps and photos. Show the help card to staff already near you; QR rental may not be usable without a wallet or connection.','先保住手机电量，暂停地图和照片加载。向眼前工作人员出示求助卡；没有钱包或网络时不继续扫码租借。'),question:T('Can you see a staffed service desk?','你现在能看到有人值守的服务台吗？'),chips:[T('I am at a service desk','我在服务台旁'),T('My internet is also offline','我的网络也断了')],cards:['help-power'],sources:[],ask:'power',priority:'recovery',mode};
if(s.network==='offline'||s.topic==='connection'){text=T('Restore connectivity before trying another app. Use a saved address or ask the service desk about available connection options.','先恢复连接，不要继续反复下载应用。查看已保存地址，或询问服务台可用的联网方式。');question=T('Are you at the airport or at your hotel?','你还在机场，还是已经到酒店？');cards=['help-connection'];sources=s.city==='Shanghai'?['pvg-arrival']:s.city==='Beijing'?['beijing-arrival']:[];ask='connection';}
else if(s.topic==='policy'){text=T('Let’s separate operator fees from entry and document rules. Use the relevant issuer or authority; do not apply Weixin terms to Alipay.','先区分钱包收费与入境、证件规定。引用对应运营商或主管机构，不能把微信规则直接套用于支付宝。');question=T('Is this about Weixin fees, Alipay, or entry/document guidance?','你问的是微信手续费、支付宝，还是入境或证件指引？');cards=['policy'];sources=['wechat-fee','immigration'];ask='policy';}
else if(['metro','rail','cash','power','luggage','transfer','explore'].includes(s.topic)){const content={metro:['Let’s find a ticket method that works for you, then choose the right direction.','先找适合你的购票方式，再确认方向。'],rail:['Start with the departure station and issuing channel. Bring the valid identity document used for the ticket.','先确认出发站与出票渠道，携带购票所用有效证件。'],cash:['Compare an exchange counter and an ATM only after confirming your location and the transaction fees.','先确认你所在位置，再比较换汇柜台与ATM的实际费用。'],power:['Compare staffed help and rental options. Nearby charging POIs do not tell us how many batteries are available.','比较现场协助与租借方式。地图上的充电点不代表有可借库存。'],luggage:['Ask your hotel about storage first, then compare nearby options and pickup deadlines.','先问酒店能否暂存，再比较附近寄存点和取回时间。'],transfer:['Compare metro, a licensed taxi and a pre-booked driver. You choose the provider; nothing is booked here.','可以比较地铁、正规出租车和预约司机接送，由你选择服务方；这里没有下单。'],explore:['Your hotel and interests can be the starting point. A poster can add ideas, but its details still need checking.','围绕酒店和兴趣安排，也可以把海报作为灵感；具体信息仍需核对。']};text=T(...content[s.topic]);cards=[s.topic];question=s.topic==='metro'?T('Which station or hotel are you heading to?','你要去哪个站或酒店？'):s.topic==='rail'?T('Have you booked the train ticket already?','你已经买好火车票了吗？'):s.topic==='explore'?T('What is your hotel or a nearby landmark?','你的酒店名或附近地标是什么？'):T('Should we look near your hotel or near the airport?','你希望找酒店附近，还是机场附近？');const ids={metro:['sh-metro'],rail:['rail-passport'],cash:['pvg-arrival'],power:['pvg-arrival'],luggage:['storage','metro-storage','storage-experience'],transfer:[],explore:[]};sources=ids[s.topic].filter(id=>s.city==='Shanghai'||id==='rail-passport');ask=s.topic;}
else if(!s.city){text=T('Hi, I’m your travel companion. We can figure this out a little at a time.','你好，我是你的旅程助手，不用一次把需求说完。');question=T('Where would you like to go, and have you already started your trip?','你想去哪里玩，现在已经出发了吗？');chips=['I want to visit Shanghai','I want to visit Beijing'];ask='city';}
else if(s.flight==='unknown'&&s.stage==='unknown'&&!s.skip.includes('flight')){text=T('Great, '+s.city+'. I’ll start from what you have already arranged.','好的，目的地是'+s.city+'。从你已经完成的步骤接着做。');question=T('Is your flight unbooked, booked, or have you already arrived?','机票还没订、已经订好，还是你已经到了？');chips=T(['My flight is unbooked','My flight is booked','I already arrived'],['机票未订','机票已订','我已经到了']);ask='flight';}
else if(s.flight==='unbooked'&&!s.skip.includes('flight')){text=T('We can compare flights without booking anything automatically.','可以先比较机票，不会自动下单。');question=T('Where will you fly from? You can also skip flights for now.','从哪个城市出发？也可以先跳过机票。');chips=T(['Skip flights for now','I booked my flight'],['稍后再看机票','机票已订']);cards=['flight'];ask='flight';}
else if(s.hotel==='unbooked'&&!s.skip.includes('hotel')){text=T('A hotel location will shape both airport transport and nearby activities.','住宿位置会影响机场交通和周边游玩安排。');question=T('Is budget, easy metro access, or a particular neighborhood most important?','你更看重预算、地铁方便，还是某个区域？');cards=['hotel'];ask='hotel';}
else if(s.stage==='in_city'){text=T('You are already settled in. Let’s work outward from your hotel.','你已经入住，可以从酒店周边继续安排。');question=T('Would you prefer food, architecture or an idea from a poster?','想看美食、建筑，还是海报上的一个地点？');cards=['explore','luggage'];ask='explore';}
else{const next=p.priority==='transport'||s.hotel==='booked'||s.skip.includes('hotel');text=T('No need to repeat completed steps. We can arrange what comes after landing, or handle a special request.','不用重复已经完成的事情。可以安排落地后的交通，也可以直接处理你的特别需求。');question=next?T('Compare transport to your accommodation, or is there something else you need?','比较到住宿地的交通，还是你有其他需求？'):T('Is your hotel already booked?','酒店已经订好了吗？');cards=next?['transfer']:[];chips=T(['My hotel is booked','My hotel is unbooked','I have a special request'],['酒店已订','酒店未订','我有特别需求']);ask=next?'transfer':'hotel';}
if(!chips.length)chips=T(['Skip for now','I have a special request'],['稍后再说','我有特别需求']);return{text,question,chips,cards,sources,ask,priority,mode};}
function policy(x){if(!x||![5,10,15,20].includes(x.battery)||![2,3].includes(x.failures)||!['hotel','transport'].includes(x.priority))throw Error('INVALID_POLICY');return{battery:x.battery,failures:x.failures,priority:x.priority};}
function validate(out,local,sources,s){if(!out||typeof out.text!=='string'||!out.text.trim())throw Error('MODEL_SCHEMA');const text=out.text.trim().slice(0,700),q=typeof out.question==='string'?out.question.slice(0,180):local.question;if((q.match(/[?？]/g)||[]).length>1||/https?:|已(?:出票|扣款|预订成功)|booking confirmed|send.{0,20}(passport|otp|password)/i.test(text+' '+q))throw Error('UNAUTHORIZED_CLAIM');if(/\d/.test(text+' '+q))throw Error('SPECIFIC_NUMBERS_REQUIRE_GUIDE');const ids=Array.isArray(out.sources)?out.sources:[];if(ids.some(i=>!sources.includes(i)))throw Error('CITATION_NOT_SUPPLIED');const allowed=['flight','hotel','transfer','explore','luggage','metro','rail','cash','power'];let cards=Array.isArray(out.cards)?out.cards.filter(x=>allowed.includes(x)).slice(0,3):local.cards;if(s.flight==='booked')cards=cards.filter(x=>x!=='flight');if(s.hotel==='booked')cards=cards.filter(x=>x!=='hotel');return{...local,text,question:q,chips:Array.isArray(out.chips)?out.chips.filter(x=>typeof x==='string'&&!/https?:/i.test(x)).slice(0,3).map(x=>x.slice(0,100)):local.chips,cards,sources:ids,mode:'deepseek-conversation'};}
function replay(p){policy(p);const cases=[['I cannot breathe in Shanghai',r=>r.priority==='urgent'],['上海着火了',r=>r.priority==='urgent'],['Shanghai battery 3%',r=>r.priority==='recovery'],['Shanghai battery 12%',r=>!r.cards.includes('flight')],['Shanghai battery 60% offline',r=>r.ask==='connection'],['I am at my hotel in Shanghai',r=>!r.cards.includes('hotel')],['I booked my flight to Shanghai but have not booked my hotel',r=>r.cards.includes('hotel')],['My hotel is booked in Shanghai',r=>!r.cards.includes('hotel')],['Weixin service fee in Shanghai',r=>r.sources.includes('wechat-fee')],['I want to store luggage in Shanghai',r=>r.cards.includes('luggage')]];const rows=cases.map(([t,test],i)=>{const s=update(initial(),t),a=reply(s,baseline),b=reply(s,p);return{id:i+1,input:t,before:a.ask,after:b.ask,changed:JSON.stringify(a)!==JSON.stringify(b),passed:!!test(b)};});return{rows,passed:rows.filter(x=>x.passed).length,total:rows.length,eligible:rows.every(x=>x.passed),scope:'Self-authored development regression, not independent evaluation.'};}
return{initial,clean,detect,update,reply,baseline,policy,validate,replay};});
