/* Shared station/place catalog. Distance labels are network stops, never GPS distance. */
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./metro'),require('./metro-data'),require('./place-data'));else r.TravelDiscovery=f(r.TravelMetro,r.ShanghaiMetroData,r.ShanghaiPlaces);})(globalThis,function(M,D,P){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stationId=s=>'station-'+D.stations.findIndex(x=>x.id===M.resolve(s));
const stationRecords=D.stations.map((s,i)=>{const lineNames=[...new Set(D.lines.filter(l=>l.stations.includes(s.id)).map(l=>l.name))];return{id:'station-'+i,title:s.zh+' / '+s.en,city:'Shanghai',publisher:'高德公开地铁路网',url:'https://map.amap.com/subway/index.html?city=3100',sourceType:'operator',kind:'operator_primary',recordType:'station',station:s.id,topics:[s.zh,s.en,'地铁','metro'],summaryZh:s.zh+'站，路网包含 '+lineNames.join('、')+'。站点及换乘关系来自公开快照；未核验出入口、无障碍、实时停运或末班车。',summary:s.en+' station. Lines: '+lineNames.join(', ')+'. Public network snapshot; no live exits, accessibility, disruptions or last-train data.',reviewedAt:D.retrievedAt.slice(0,10),reviewDays:30,active:true};});
const placeRecords=P.places.map(p=>({id:p.id,title:p.zh+' / '+p.en,city:'Shanghai',publisher:'上海市政府国际服务门户',url:p.url,sourceType:'official',kind:'official_portal',recordType:'place',station:p.station,placeId:p.id,topics:[p.zh,p.en,p.station,'附近','景点',p.category],summaryZh:p.summaryZh+' 地址：'+p.address+'。建议使用 '+p.station+' 站再查步行导航；站点关联为编辑整理，不是实时最近出口。',summary:p.summary+' Address: '+p.addressEn+'. Suggested metro anchor: '+p.station+'; check walking navigation. Station association is editorial, not a nearest-exit guarantee.',reviewedAt:P.checkedAt,reviewDays:30,active:true}));
function records(){return [...stationRecords,...placeRecords];}
const cache=new Map();function stops(a,b){const key=a+'|'+b;if(!cache.has(key)){try{cache.set(key,M.plan({origin:a,destination:b}).segments.reduce((n,s)=>n+s.stations.length-1,0));}catch(_){cache.set(key,Infinity);}}return cache.get(key);}
function mentioned(text){const t=String(text||'').toLowerCase();const matches=P.places.filter(p=>t.includes(p.zh.toLowerCase())||t.includes(p.en.toLowerCase()));return matches.filter(p=>!matches.some(x=>x.id!==p.id&&(x.zh.toLowerCase().includes(p.zh.toLowerCase())||x.en.toLowerCase().includes(p.en.toLowerCase()))));}
function stationForPlace(v){return M.resolve(v)||M.resolve(mentioned(v)[0]?.station)||null;}
function context(state){const h=state.history.at(-1);if(!h)return{origin:null,destination:null,route:null};const mi=h.assistance?.intent,local=M.intent(h.text,h.context?.city,state.history.slice(0,-1));let route=mi?(mi.kind==='metro'?h.assistance.tool?.metro:null):local;const mentionedPlace=mentioned(h.text).at(-1);const direct=mentionedPlace?.station||M.hits(h.text).at(-1);const previous=[...state.history.slice(0,-1)].reverse().find(x=>x.assistance?.intent?.destination||M.hits(x.text).length);
 const near=/附近|周边|吃|玩|景点|广场|nearby|near |around|eat|food|sight|visit|park/i.test(h.text);
 const oldDestination=previous?.assistance?.intent?.destination||M.hits(previous?.text).at(-1);
 return{origin:M.resolve(route?.origin||mi?.origin),destination:stationForPlace(route?.destination||mi?.destination)||direct||(near?stationForPlace(oldDestination):null),route,kind:mi?.kind||local?.kind||'other'};
}
function nearby(destination,route,limit=6,pool=placeRecords){const to=M.resolve(destination);if(!to)return[];const viaStations=new Set();try{if(route?.origin&&route?.destination)for(const s of M.plan(route).segments)for(const id of [s.stations[0],s.stations.at(-1)])viaStations.add(id);}catch(_){}
 return P.places.map(p=>({...p,stops:stops(to,p.station),onRoute:viaStations.has(p.station)})).filter(p=>{const row=pool.find(r=>r.id===p.id);return row&&!row.publicationHash&&row.active!==false&&row.reviewedAt&&Date.now()-Date.parse(row.reviewedAt)<=Number(row.reviewDays||14)*86400000&&(p.stops<=2||p.onRoute);}).sort((a,b)=>(a.stops===0?-10:a.stops)-(b.stops===0?-10:b.stops)||(['museum','park','art','food','square','walk','garden','shopping'].indexOf(a.category)-['museum','park','art','food','square','walk','garden','shopping'].indexOf(b.category))||a.id.localeCompare(b.id)).slice(0,limit);
}
function mapUrl(p){return 'https://uri.amap.com/search?keyword='+encodeURIComponent('上海 '+p.zh+' '+p.address)+'&city=310000&view=map&src=visit-china';}
function card(p,zh=true){return '<article class="nearby-place" data-place-id="'+p.id+'" data-metric-kind="nearby" data-metric-item="'+p.id+'"><small>'+esc(({food:'吃点什么 / Food',park:'公园 / Park',museum:'博物馆 / Museum',square:'广场 / Square',walk:'漫步 / Walk',art:'艺术 / Art',garden:'园林 / Garden',shopping:'街区 / Browse'})[p.category])+'</small><h3>'+esc(zh?p.zh:p.en)+'</h3><p>'+esc(zh?p.summaryZh:p.summary)+'</p><p class="place-address">'+esc(zh?p.address:p.addressEn)+'</p><p class="place-distance">'+esc(p.station)+' · '+(p.stops===0?(zh?'与目的地同站片区':'Same station area'):p.onRoute&&p.stops>2?(zh?'本次换乘点附近':'Near a transfer on this route'):(zh?'距目的地 '+p.stops+' 个地铁站间区段':'About '+p.stops+' metro stop segments from destination'))+'</p><div class="place-actions"><button class="light" data-place-route="'+p.id+'">'+(zh?'＋ 加入路线':'＋ Add to route')+'</button><button class="light" data-place-ask="'+p.id+'">'+(zh?'问这个地方':'Ask about this place')+'</button><a data-product-kind="nearby" data-product-item="'+p.id+'" href="'+mapUrl(p)+'" target="_blank" rel="noopener noreferrer">'+(zh?'查看地图 ↗':'Map ↗')+'</a><button class="light" data-source-detail="'+p.id+'">'+(zh?'资料来源':'Source')+'</button></div></article>';}
function questions(state){const c=context(state),zh=state.language==='zh',to=c.destination;if(!to)return zh?['我在人民广场，附近有什么可以逛的？','从浦东机场到上海火车站的地铁怎么坐？']:['What can I visit near People’s Square?','Metro from Pudong Airport to Shanghai Railway Station?'];return zh?[to+'附近有什么可以玩？',to+'附近有什么可以吃？','从'+to+'坐地铁到豫园怎么走？']:[`What can I visit near ${to}?`,`Where can I eat near ${to}?`,`Metro from ${to} to Yuyuan?`];}
function reply(text,state,pool=placeRecords){const ps=mentioned(text);if(ps.length===1&&!/地铁|怎么去|怎么走|metro|route|how.{0,8}get/i.test(text)){const p=ps[0],r=pool.find(r=>r.id===p.id);if(r&&!r.publicationHash&&r.active!==false&&r.reviewedAt&&Date.now()-Date.parse(r.reviewedAt)<=Number(r.reviewDays||14)*86400000)return{kind:'nearby',text:state.language==='zh'?p.zh+'：'+p.summaryZh+' 地址：'+p.address+'。可从'+p.station+'站继续步行导航；营业、预约和票价请看原文。':p.en+': '+p.summary+' Address: '+p.addressEn+'. Use '+p.station+' as a metro anchor and check walking directions, opening and booking details.',sourceIds:[p.id],places:[p.id]};}
 if(!/附近|周边|景点|广场|好玩|吃饭|美食|推荐.{0,8}玩|nearby|near |around|where to eat|places to|sightsee/i.test(text))return null;const c=context(state),food=/吃|美食|饭店|餐厅|food|eat|restaurant/i.test(text),all=nearby(c.destination,c.route,19,pool),p=all.filter(p=>!food||p.category==='food').slice(0,3);const zh=state.language==='zh';return{kind:'nearby',text:!c.destination?(zh?'你想看哪个地铁站或景点附近？告诉我地点，我会按实际收录地点推荐。':'Which station or attraction should I search around?'):!p.length?(zh?'当前资料库还没有'+c.destination+'附近已核对的'+(food?'餐饮':'去处')+'，我不会把其他区域当成附近。可以换个地点，或在资料库补充来源。':'No reviewed '+(food?'food places':'places')+' are currently covered near '+c.destination+'. Choose another area or add a source.'):(zh?'按'+c.destination+'及邻近站点，可以考虑：':'Around '+c.destination+' and nearby stops, consider: ')+p.map(x=>zh?x.zh+'（'+x.station+'）':x.en+' ('+x.station+')').join('；')+(zh?'。下方和右侧可查看真实地址、来源并加入路线。步行距离及当前营业请打开地图核对。':'. View addresses, sources and add a stop below or on the right. Check walking directions and current opening on the map.'),sourceIds:p.map(p=>p.id),places:p.map(p=>p.id)};
}
return{records,placeRecords,stationRecords,stationId,places:P.places,context,nearby,card,questions,reply,mentioned,stationForPlace,mapUrl};
});
