/* Shared deterministic state contract. Models propose facts; they never execute bookings. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelEngine=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='6.0.0';
const BASE={version:'wf-1',maxSpokenChars:220,questionOrder:['stage','flight','hotel','transfer','interests'],proactiveExtensions:true,promptSuffix:'Ask one useful question at a time. Accept a click as an answer. Never require listening to finish.'};
const FIELDS={city:80,stage:['planning','arriving','exploring'],flight:['booked','not_booked','skip'],hotel:['booked','not_booked','skip'],transfer:['metro','taxi','driver','skip'],hotelName:120,area:100,interests:240,party:120,airport:12,terminal:8,zone:['public','restricted','baggage'],network:['online','poor','offline'],battery:'number'};
const TASKS=['flight','hotel','transfer','explore','power','connection','metro','cash','payment','rail','luggage','help','restaurant'];
const PREFS={budget:['economy','comfort'],pace:['relaxed','full'],diet:['vegetarian','local']};
function preferences(value={}){if(!value||typeof value!=='object'||Array.isArray(value))throw Error('PREFERENCES_OBJECT');const out={};for(const [key,val]of Object.entries(value)){if(!PREFS[key]||!PREFS[key].includes(val))throw Error('PREFERENCE_VALUE');out[key]=val;}return out;}
const TITLES={restaurant:['吃饭安排','Places to eat'],flight:['选择机票','Choose a flight'],hotel:['安排住宿','Find a place to stay'],transfer:['安排到店交通','Get to the hotel'],explore:['探索周边','Explore nearby'],power:['先恢复电量','Restore power first'],connection:['恢复网络','Restore connectivity'],metro:['地铁乘车指引','Metro boarding guide'],cash:['现金与换汇','Cash and exchange'],payment:['核对支付规则','Check payment rules'],rail:['火车购票与乘车','Rail and boarding'],luggage:['安排寄存','Find luggage storage'],help:['找到现场帮助','Find staffed help']};
const URLS={restaurant:'https://www.trip.com/travel-guide/',flight:'https://www.trip.com/flights/',hotel:'https://www.trip.com/hotels/',transfer:'https://www.trip.com/airport-transfers/',taxi:'https://www.didiglobal.com/',rail:'https://www.12306.cn/en/',luggage:'https://usebounce.com/',explore:'https://www.trip.com/travel-guide/destination/shanghai-2/'};
function clean(value,max=2000){return String(value||'').replace(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi,'[email removed]').replace(/\b(?:\d[ -]?){13,19}\b/g,'[number removed]').replace(/(?:passport|护照号|password|密码|otp|验证码)\s*[:：]\s*\S+/gi,'[secret removed]').trim().slice(0,max);}
function sourceIds(value){return [...new Set((Array.isArray(value)?value:[]).filter(x=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(x)))].slice(0,3);}
function copy(x){return JSON.parse(JSON.stringify(x));}
function state(policy=BASE){return{schema:5,revision:0,language:'en',outputLanguage:'auto',preferences:{},facts:{},tasks:[],confirmedRevision:null,history:[],initialRequest:null,answered:[],lastQuestion:null,policy:copy(policy),currentIssue:null,outcomes:{},lastReply:null};}
function validatePatch(p){if(!p||typeof p!=='object'||Array.isArray(p))throw Error('FACTS_OBJECT');const out={};for(const[k,v]of Object.entries(p)){const rule=FIELDS[k];if(!rule)throw Error('FIELD_NOT_ALLOWED');if(Array.isArray(rule)){if(!rule.includes(v))throw Error('FIELD_VALUE');out[k]=v;}else if(rule==='number'){if(!Number.isInteger(v)||v<0||v>100)throw Error('BATTERY_RANGE');out[k]=v;}else {if(typeof v!=='string'||!v.trim()||v.length>rule||/https?:|[<>]/i.test(v))throw Error('FIELD_TEXT');out[k]=clean(v,rule);}}return out;}
function parse(text,previous){const s=clean(text),p={},tasks=[];
 if(['flight','hotel'].includes(previous.lastQuestion)){if(/^(?:yes[, .!]*|already booked|booked|yes it is|已订|订好了|已经订好了)[.!。！\s]*$/i.test(s))p[previous.lastQuestion]='booked';if(/^(?:no|not yet|not booked|还没|还没订|没有|没订)[.!。！\s]*$/i.test(s))p[previous.lastQuestion]='not_booked';}
 if(/上海|shanghai|\bpvg\b|浦东/i.test(s))p.city='Shanghai';if(/北京|beijing|\bpek\b|\bpkx\b/i.test(s))p.city='Beijing';
 if(/boston|波士顿/i.test(s))p.city='Boston';else if(/new york|纽约|\bnyc\b/i.test(s))p.city='New York';
 const destination=s.match(/(?:to |到|去|飞往)(上海|shanghai|北京|beijing|波士顿|boston|纽约|new york)/i);if(destination)p.city=({'上海':'Shanghai','shanghai':'Shanghai','北京':'Beijing','beijing':'Beijing','波士顿':'Boston','boston':'Boston','纽约':'New York','new york':'New York'})[destination[1].toLowerCase()];
 const other=s.match(/(?:going to|visit|heading to|去|想去)\s*(Tokyo|Paris|London|Chengdu|Hangzhou|Xi.an|东京|巴黎|伦敦|成都|杭州|西安)/i);if(other)p.city=other[1];
 if(/planning|next (?:month|week)|haven.t started|还没出发|准备去|计划去|下个月/i.test(s))p.stage='planning';
 if(/just (?:landed|arrived)|at (?:the )?airport|刚到|刚落地|在机场|public arrivals/i.test(s))p.stage='arriving';
 if(/already exploring|in (?:the )?(?:city|metro|subway)|在地铁|已经在玩|在市区/i.test(s))p.stage='exploring';
 if(/\bpvg\b|浦东/i.test(s))p.airport='PVG';if(/\bsha\b|虹桥/i.test(s)&&!/虹桥(?:火车站|站)|hongqiao (?:railway|train)/i.test(s))p.airport='SHA';if(/\bpek\b|首都机场/i.test(s))p.airport='PEK';if(/\bpkx\b|大兴机场/i.test(s))p.airport='PKX';const terminal=s.match(/\bT\s*([123])\b|([123])号航站楼/i);if(terminal)p.terminal='T'+(terminal[1]||terminal[2]);
 if(/public arrivals|landside|公共到达|公共区域/i.test(s))p.zone='public';if(/airside|restricted|安检内/i.test(s))p.zone='restricted';if(/baggage claim|行李提取/i.test(s))p.zone='baggage';
 for(const [field,word]of [['flight','flight|air ticket|机票'],['hotel','hotel|accommodation|酒店|住宿']]){
  if(new RegExp('(?:booked|reserved|already have).{0,28}(?:'+word+')|(?:'+word+').{0,15}(?:is booked|already booked|已订|已经订|订好了)|(?:已订|订好).{0,8}(?:'+word+')','i').test(s))p[field]='booked';
  if(new RegExp('(?:haven.t|have not|not|no|need to).{0,22}(?:booked? |reserved? |chosen |a |my |the )?(?:'+word+')|(?:'+word+').{0,10}(?:not booked|未订|没订)|(?:未订|没订|还没订).{0,6}(?:'+word+')','i').test(s))p[field]='not_booked';
 }
 const hn=s.match(/(?:staying at|my hotel is|住在|酒店是)\s*([^。.!?\n,，]{2,90})/i);if(hn&&!/^(?:booked|not booked|already booked|已订|未订|没订)$/i.test(hn[1].trim())){p.hotelName=hn[1].trim();p.hotel='booked';}
 if(/with my parents|with parents|父母|爸妈|老人/i.test(s))p.party='with parents';if(/with (?:my )?(?:kids|children)|带孩子|带娃/i.test(s))p.party='with children';if(/travelling alone|traveling alone|solo|一个人/i.test(s))p.party='solo';
 const b=s.match(/(?:battery|电量|只剩|剩)[^\d]{0,12}(\d{1,3})\s*%|(\d{1,3})\s*%\s*(?:battery|电)/i);if(b)p.battery=Math.min(100,Number(b[1]||b[2]));
 if(/no (?:internet|network|data)|offline|没网|断网/i.test(s))p.network='offline';else if(/weak|poor connection|弱网/i.test(s))p.network='poor';else if(/online now|good network|网络恢复|网络正常/i.test(s))p.network='online';
 if(/prefer (?:the )?metro|take (?:the )?metro|选地铁|坐地铁去/i.test(s))p.transfer='metro';if(/prefer (?:a )?taxi|take (?:a )?taxi|想打车|选出租车/i.test(s))p.transfer='taxi';if(/private driver|airport pickup|司机接送|预约接机/i.test(s))p.transfer='driver';
 const interests=[];for(const [rx,name]of [[/architecture|建筑/i,'architecture'],[/food|美食/i,'food'],[/museum|博物馆/i,'museums'],[/garden|公园|园林/i,'gardens'],[/shopping|购物/i,'shopping']])if(rx.test(s))interests.push(name);if(interests.length)p.interests=interests.join(', ');
 for(const [id,rx]of [['restaurant',/restaurant|where to eat|dining|餐厅|饭店|吃饭|美食推荐/i],['power',/充电|battery|power bank/i],['connection',/网络|internet|sim card|esim|offline|没网/i],['metro',/subway|metro (?:station|ticket)|地铁站|地铁票/i],['cash',/exchange|换汇|现金|硬币|need cash/i],['payment',/支付|手续费|alipay|wechat|weixin|fee/i],['rail',/train|rail|火车|高铁/i],['luggage',/luggage storage|store.{0,10}bag|寄存/i],['help',/staff|help desk|工作人员|求助/i]])if(rx.test(s))tasks.push(id);
 if(/豫园|yuyuan|yu garden/i.test(s)){p.city='Shanghai';if(!tasks.includes('metro'))tasks.push('metro');if(!/火车票|高铁票|train tickets|rail tickets/i.test(s)){const i=tasks.indexOf('rail');if(i>=0)tasks.splice(i,1);}}
 if(/地铁|metro|subway/i.test(s)){if(!tasks.includes('metro'))tasks.push('metro');if(!/火车票|高铁票|train tickets?|rail tickets?/i.test(s)){const i=tasks.indexOf('rail');if(i>=0)tasks.splice(i,1);}}
 const requested=s.match(/(?:需要|想订|帮我找|推荐)(?:一家|一个|一间|一张)?(?:酒店|住宿|机票|飞机票|火车票|高铁票|饭店|餐厅)(?:[和与、，,\s]+(?:酒店|住宿|机票|飞机票|火车票|高铁票|饭店|餐厅))*/g)||[];
 if(/need (?:a|an) hotel\b|(?:需要|想订|帮我找)(?:一家|一个|一间)?(?:酒店|住宿)(?=和|与|推荐|[、，,。.!?\s]|$)/i.test(s)||requested.some(x=>/酒店|住宿/.test(x)))p.hotel='not_booked';if(/need (?:a|an) flight\b|(?:需要|想订|帮我找)(?:一张)?(?:机票|飞机票)/i.test(s)||requested.some(x=>/机票/.test(x)))p.flight='not_booked';if(p.flight==='not_booked'||(/机票|飞机票|flight tickets?|air tickets?/i.test(s)&&p.flight!=='booked'))tasks.push('flight');if(p.hotel==='not_booked')tasks.push('hotel');if(p.transfer)tasks.push('transfer');if(p.interests)tasks.push('explore');
 // A comma-separated request must not swallow an explicit booked status for
 // the following service (e.g. 需要酒店，机票已订).
 for(const [field,word]of [['flight','机票|飞机票'],['hotel','酒店|住宿']])if(new RegExp('(?:'+word+')(?:已经|早就|已)?(?:订好了|订好|订了|订妥|预订好了)|(?:'+word+')已订').test(s)){p[field]='booked';const i=tasks.indexOf(field);if(i>=0)tasks.splice(i,1);}
 if(/taxi|cab\b|打车|出租车|车费/i.test(s)){p.transfer='taxi';if(!tasks.includes('transfer'))tasks.push('transfer');if(/火车站|railway station|train station/i.test(s)&&!/火车票|高铁|坐火车|乘火车|train tickets?|take .{0,10}train/i.test(s)){const i=tasks.indexOf('rail');if(i>=0)tasks.splice(i,1);}}
 if(previous.lastQuestion==='interests'&&!p.interests&&s&&!/^skip|跳过|随便$/i.test(s))p.interests=clean(s,240);
 return{patch:p,tasks};}
function speechDecision(text,s=state(),semantic=false){
 const t=clean(text,2000).replace(/[\s，。！？,.!?…]/g,'').toLowerCase();
 if(t.length<2)return{accepted:false,reason:'too-short'};
 if(/^(?:t[12]|[12]号航站楼)$/i.test(t)&&s.facts?.airport)return{accepted:true,reason:'terminal-answer'};
 if(/^(?:嗯|啊|哦|呃|额|唉|诶|喂|哈|嘿|uh|um|hmm|ah|oh)+$/i.test(t)||/^(.)\1{2,}$/u.test(t))return{accepted:false,reason:'filler'};
 const context=['flight','hotel','confirm','issue','stage','transfer','interests'].includes(s.lastQuestion);
 if(/^(?:yes|no|ok|okay|confirm|done|好的|确认|可以|对的|不是|没有|还没|已订|订好了|跳过|稍后|稍后再说)$/i.test(t))return{accepted:context,reason:context?'context-answer':'no-context'};
 if(/^(?:你好|您好|hello|hi)$/i.test(t))return{accepted:!s.history?.length,reason:'greeting'};
 const travel=/上海|北京|杭州|南京|苏州|广州|深圳|成都|西安|东京|巴黎|伦敦|纽约|波士顿|上海虹桥|豫园|城隍庙|人民广场|陆家嘴|南京东路|机场|地铁|酒店|住宿|机票|飞机|航班|火车|高铁|车票|打车|出租车|车费|公里|分钟|预算|出发|抵达|落地|出行|旅游|旅行|游玩|预订|餐厅|饭店|吃饭|美食|博物馆|建筑|公园|园林|购物|行李|寄存|支付|签证|护照|网络|电量|充电|父母|孩子|没网|工作人员|求助|吃素|素食|轻松|慢游|经济实惠|舒适|省钱|当地风味|明天|后天|下周|周末|天气|路线|怎么走|换乘|shanghai|beijing|hangzhou|nanjing|suzhou|guangzhou|shenzhen|chengdu|xi.an|tokyo|paris|london|boston|new york|hongqiao|yuyuan|yu garden|lujiazui|nanjing road|airport|metro|subway|hotel|flight|plane|train|rail|ticket|taxi|cab\b|budget|travel|trip|arriv|depart|book|restaurant|food|museum|architecture|garden|luggage|payment|visa|passport|internet|network|battery|power|parents|children|vegetarian|relaxed|comfort|kilomet|\bkm\b|tomorrow|weekend|weather|route|transfer/i;
 if(semantic&&t.length>=4)return{accepted:true,reason:'model-intent-pending'};
 return{accepted:travel.test(text),reason:travel.test(text)?'travel-intent':'unclear-intent'};
}
function apply(previous,event){const s=copy(previous);if(!event||typeof event!=='object')throw Error('EVENT_REQUIRED');const before=copy(s.facts);if(event.type==='preferences'){s.preferences=preferences(event.preferences);s.revision++;s.confirmedRevision=null;return s;}if(event.type==='language'){if(!['auto','zh','en'].includes(event.language))throw Error('LANGUAGE_VALUE');s.outputLanguage=event.language;if(event.language!=='auto')s.language=event.language;else {const last=[...s.history].reverse().find(h=>h.channel!=='click');if(last)s.language=/[\u4e00-\u9fff]/.test(last.text)?'zh':'en';}s.revision++;if(previous.confirmedRevision===previous.revision)s.confirmedRevision=s.revision;s.lastReply=reply(s).say;return s;}s.revision++;s.confirmedRevision=null;let message='',patch={},tasks=[];
 if(event.type==='text'){message=clean(event.text);if(!message)throw Error('EMPTY_MESSAGE');s.language=s.outputLanguage&&s.outputLanguage!=='auto'?s.outputLanguage:/[\u4e00-\u9fff]/.test(message)?'zh':/[a-z]/i.test(message)?'en':s.language;if(!s.initialRequest&&!/^(?:hi|hello|你好|您好|yes|no|好的|确认)[!！.。\s]*$/i.test(message))s.initialRequest={text:message,channel:event.channel||'text'};const parsed=parse(message,s);patch=parsed.patch;tasks=parsed.tasks;s.preferences=s.preferences||{};if(/预算低|经济实惠|便宜一点|省钱|low budget|budget friendly/i.test(message))s.preferences.budget='economy';if(/舒适优先|住好一点|comfort first/i.test(message))s.preferences.budget='comfort';if(/轻松|慢游|慢一点|relaxed pace|take it slow/i.test(message))s.preferences.pace='relaxed';if(/多看多玩|行程紧凑|packed itinerary/i.test(message))s.preferences.pace='full';if(/吃素|素食|vegetarian/i.test(message)&&!/不吃素|不要素食|not vegetarian/i.test(message))s.preferences.diet='vegetarian';if(/当地风味|local food/i.test(message))s.preferences.diet='local';if(/不吃素|不要素食|not vegetarian/i.test(message))delete s.preferences.diet;
  if(/^(?:yes|yes,? that.s right|confirm|confirmed|go ahead|好的|确认|可以|对的)[.!。！\s]*$/i.test(message)&&s.lastQuestion==='confirm')s.confirmedRevision=s.revision;
  if(/^(skip|later|稍后|跳过)[.!。！\s]*$/i.test(message)&&s.lastQuestion)s.answered.push(s.lastQuestion);
 }else if(event.type==='choice'){
  const options=reply(previous).options;const item=options.find(x=>x.id===event.id);if(!item)throw Error('CHOICE_NOT_CURRENT');patch=item.patch||{};tasks=item.tasks||[];message=item.label;
  if(item.clearIssue)s.currentIssue=null;if(item.skip)s.answered.push(s.lastQuestion);if(item.confirm)s.confirmedRevision=s.revision;
 }else if(event.type==='facts'){patch=validatePatch(event.patch);message='Confirmed structured facts';}else if(event.type==='confirm'){s.confirmedRevision=s.revision;message=s.language==='zh'?'确认这些需求':'Confirm these needs';}else if(event.type==='outcome'){if(!reply(previous).plan.some(x=>x.id===event.task))throw Error('TASK_NOT_PRESENT');s.outcomes[event.task]='done';message='User confirmed task complete: '+event.task;s.confirmedRevision=previous.confirmedRevision===previous.revision?s.revision:null;}else throw Error('EVENT_NOT_ALLOWED');
 patch=validatePatch(patch);if(patch.city&&patch.city!==s.facts.city){delete s.facts.airport;delete s.facts.terminal;delete s.facts.zone;delete s.facts.hotelName;delete s.facts.area;delete s.facts.transfer;delete s.facts.hotel;delete s.facts.flight;s.outcomes={};s.answered=[];}
 if(patch.airport&&patch.airport!==s.facts.airport){delete s.facts.terminal;delete s.facts.zone;}
 Object.assign(s.facts,patch);if(patch.stage==='arriving')s.facts.flight='booked';
 if(event.type==='text'){const issue=['power','connection','metro','cash','payment','rail','luggage','help'].find(x=>tasks.includes(x));if(issue)s.currentIssue=issue;else if(/^(?:yes|done|resolved|好了|解决了)[.!。！\s]*$/i.test(message))s.currentIssue=null;}
 if(patch.battery>5&&s.currentIssue==='power')s.currentIssue=null;if(patch.network==='online'&&s.currentIssue==='connection')s.currentIssue=null;
 for(const task of tasks)if(TASKS.includes(task)&&!s.tasks.includes(task))s.tasks.push(task);
 if(patch.hotel==='booked')s.tasks=s.tasks.filter(t=>t!=='hotel');if(patch.flight==='booked')s.tasks=s.tasks.filter(t=>t!=='flight');
 s.history.push({revision:s.revision,sourceIds:sourceIds(event.sourceIds),text:message,channel:event.channel||'text',language:s.language,context:{city:s.facts.city||'',preferences:s.preferences||{}},offers:tasks.filter(t=>['hotel','flight','rail','restaurant'].includes(t)),factsChanged:Object.keys(s.facts).filter(k=>s.facts[k]!==before[k])});s.history=s.history.slice(-30);
 const result=reply(s);s.lastQuestion=result.question;s.lastReply=result.say;s.history.at(-1).reply=result.say;return s;}
function reply(s){const zh=s.language==='zh',f=s.facts,p=s.policy||BASE,tr=(a,b)=>zh?a:b;const summary=[];
 if(f.city)summary.push(tr('目的地：','Destination: ')+f.city);if(f.stage)summary.push(tr('旅程阶段：','Stage: ')+({planning:tr('准备出发','planning'),arriving:tr('刚刚抵达','arriving'),exploring:tr('正在游玩','exploring')}[f.stage]));
 if(f.flight)summary.push(tr('机票：','Flight: ')+({booked:tr('已订（你提供）','booked, self-reported'),not_booked:tr('未订','not booked'),skip:tr('稍后','later')}[f.flight]));if(f.hotel)summary.push(tr('住宿：','Hotel: ')+({booked:tr('已订（你提供）','booked, self-reported'),not_booked:tr('需要安排','needed'),skip:tr('稍后','later')}[f.hotel])+(f.hotelName?' · '+f.hotelName:''));if(f.party)summary.push(tr('同行：','Party: ')+(zh?({'with parents':'和父母','with children':'带孩子',solo:'独自出行'}[f.party]||f.party):f.party));if(f.interests)summary.push(tr('偏好：','Interests: ')+f.interests);
 const opt=(id,a,b,patch={},extra={})=>({id,label:tr(a,b),patch,...extra});let question,say,options=[];
 const urgent=f.battery!==undefined&&f.battery<=5;
 if(urgent){question='power';say=tr('先保住电量。我暂停语音和图片，给你一张可以出示给现场工作人员的中文求助卡。','Let’s save your battery. I will pause audio and images and show a Chinese help card for staff.');options=[opt('power-restored','电量已恢复','Power restored',{battery:60}),opt('help-now','仍需要帮助','Still need help',{}, {tasks:['help']})];}
 else if(f.network==='offline'){question='connection';say=tr('先解决网络。你可以继续用这里的文字卡向现场人员求助；不会让你反复扫码或下载应用。','Let’s handle connectivity first. Use the text help card with staff; I won’t send you into another download or QR loop.');options=[opt('network-restored','网络已恢复','Back online',{network:'online'}),opt('need-help','找现场人员','Ask staff',{}, {tasks:['help']})];}
 else if(p.needsFirst){question='needs';say=tr('你好，有什么具体需求？可以问地铁路线、车费、高铁，或直接说你的安排。','Hi! What specifically would you like help with? Ask about a metro route, taxi fare, train, or your plans.');if(s.history.length)say=tr('这次问题还缺少可执行的信息。请补充要查询的地点或站名；我会继续处理这一问。','I need a place or station to answer this request. Please add that detail so I can continue with the same question.');options=[];}
 else if(s.currentIssue==='rail'){question='issue';say=tr('火车票示例已放在这轮对话下方。你打算从哪一站到哪一站、哪天出发？可先看示例，再补充实际行程。','Train examples are below this message. What are your departure and arrival stations, and travel date? You can browse the examples first.');options=[opt('issue-resolved','继续其他需求','Continue my other needs',{}, {clearIssue:true})];}
 else if(s.currentIssue){question='issue';const issue=s.currentIssue;say=tr('先处理：'+TITLES[issue][0]+'。相关行动卡和来源已经放在右边。你可以边看边说；需要先找现场人员协助吗？','Let’s handle '+TITLES[issue][1].toLowerCase()+' first. The action and source cards are ready beside this call. Need help from staff, or shall we return to your plan?');options=[opt('issue-help','找现场人员','Ask staff',{}, {tasks:['help'],clearIssue:true}),opt('issue-resolved','已解决，继续旅程','Resolved, continue',{}, {clearIssue:true})];}
 else if(!f.city){question='city';say=tr('你好！你想去哪里玩？已经出发了吗？可以直接说，也可以随时点选。','Hi! Where would you like to go, and have you started your trip? You can speak or choose on screen.');options=[opt('city-sh','上海','Shanghai',{city:'Shanghai'}),opt('city-bj','北京','Beijing',{city:'Beijing'})];}
 else {
  for(const key of p.questionOrder){if(s.answered.includes(key)||f[key])continue;if(key==='flight'&&f.stage!=='planning')continue;question=key;break;}
  const questions={stage:tr('你现在是在准备出发、刚刚落地，还是已经在游玩？','Are you planning ahead, arriving now, or already exploring?'),flight:tr('机票订好了吗？没有的话可以先去搜索；也可以先聊其他需求。','Is your flight booked? We can search for one, or start somewhere else.'),hotel:tr('住宿安排好了吗？你也可以直接告诉我酒店名或希望住的区域。','Have you arranged a hotel? You can tell me its name or the area you prefer.'),transfer:tr('到店交通你更偏好地铁、正规出租车，还是带司机的预约接送？也可以先跳过。','For getting to your hotel, would you prefer metro, a taxi, or a prebooked driver? You can also skip this.'),interests:tr('有没有特别想体验的？例如建筑、美食、博物馆；也可以直接讲你的想法。','Anything special you want to experience—architecture, food, museums, or something else?')};
  const choices={stage:[opt('planning','还在准备','Planning ahead',{stage:'planning'}),opt('arriving','刚刚抵达','Just arrived',{stage:'arriving'}),opt('exploring','正在游玩','Exploring',{stage:'exploring'})],flight:[opt('flight-booked','机票已订','Flight booked',{flight:'booked'}),opt('flight-needed','还没订','Need a flight',{flight:'not_booked'},{tasks:['flight']})],hotel:[opt('hotel-booked','酒店已订','Hotel booked',{hotel:'booked'}),opt('hotel-needed','还没订','Need a hotel',{hotel:'not_booked'},{tasks:['hotel']})],transfer:[opt('metro','地铁','Metro',{transfer:'metro'},{tasks:['transfer']}),opt('taxi','出租车','Taxi',{transfer:'taxi'},{tasks:['transfer']}),opt('driver','预约接送','Private driver',{transfer:'driver'},{tasks:['transfer']})],interests:[opt('architecture','建筑与街区','Architecture',{interests:'architecture'},{tasks:['explore']}),opt('food','美食','Food',{interests:'food'},{tasks:['explore']}),opt('museums','博物馆','Museums',{interests:'museums'},{tasks:['explore']})]};
  if(question){say=questions[question];options=choices[question]||[];options.push(opt('skip-'+question,'稍后再说','Later',{}, {skip:true}));}
  else if(s.confirmedRevision!==s.revision){question='confirm';say=tr('我理解你有屏幕上这几件事要做。确认后我会组织下一步；你可以说“确认”，也可以继续补充。','I understand the tasks listed on screen. Shall I organize the next steps? Say confirm, tap, or add anything I missed.');options=[opt('confirm-needs','确认并整理','Confirm and organize',{}, {confirm:true})];}
  else {question='open';say=tr('需求已确认。行动卡已更新，没有替你预订。你可以继续说，也可以边看卡片边选择。','Your needs are confirmed and the action cards are ready. Nothing has been booked. Keep talking or explore the cards.');options=[opt('add-rail','火车指南','Rail guide',{}, {tasks:['rail']}),opt('add-luggage','行李寄存','Luggage storage',{}, {tasks:['luggage']})];}
 }
 const tasks=[...new Set([...s.tasks,...(f.hotel==='booked'?['transfer']:[]),...(f.interests?['explore']:[])])];
 const plan=tasks.map(t=>({id:t,title:TITLES[t][zh?0:1],status:s.outcomes[t]||'suggested',reason:tr('依据你已提供的需求；不是已完成的预订或已联系商户。','Based on your stated needs; not a booking or a contacted merchant.'),url:t==='rail'&&['Boston','New York'].includes(f.city)?'https://www.amtrak.com/home.html':t==='transfer'?(f.transfer==='metro'?null:f.transfer==='taxi'?URLS.taxi:URLS.transfer):t==='explore'&&f.city!=='Shanghai'?'https://www.trip.com/travel-guide/':URLS[t]||null,sourceKind:['payment','rail','metro','cash','help'].includes(t)?'official-required':'suggestion'}));
 const suggestions=[];if(!urgent&&f.network!=='offline'&&p.proactiveExtensions){if(f.hotel==='booked'&&!tasks.includes('luggage'))suggestions.push({task:'luggage',text:tr('提前到店？考虑行李寄存','Early check-in? Explore luggage storage'),url:URLS.luggage});if(f.hotel&&f.city==='Shanghai'&&!tasks.includes('explore'))suggestions.push({task:'explore',text:tr('看看住宿附近想玩的地方','Ideas near your stay'),url:URLS.explore});}
 const nextQuestion=say;const last=s.history.at(-1);if(last?.offers?.length&&last.revision===s.revision&&!urgent&&f.network!=='offline'){const names=last.offers.map(t=>TITLES[t]?.[zh?0:1]).filter(Boolean);say=tr('我先把你需要的'+names.join('、')+'放在下面，供你比较。这些是模拟示例。','I have added '+names.join(', ').toLowerCase()+' examples below for comparison. These are simulated options. ')+say;}
 return{question,say,spoken:(say.length<=p.maxSpokenChars?say:nextQuestion).slice(0,p.maxSpokenChars),options,summary,plan,suggestions,urgent,policyVersion:p.version,mode:'deterministic'};
}
// Browser memory is display/input data, never workflow or confirmation authority.
function restoreMemory(saved,policy=BASE){
 const s=state(policy);s.facts=validatePatch(saved.facts||{});s.tasks=Array.isArray(saved.tasks)?[...new Set(saved.tasks.filter(t=>TASKS.includes(t)))]:[];s.language=saved.language==='zh'?'zh':'en';s.outputLanguage=['zh','en'].includes(saved.outputLanguage)?saved.outputLanguage:'auto';s.preferences=preferences(saved.preferences||{});
 s.history=(Array.isArray(saved.history)?saved.history:[]).slice(-30).filter(h=>h&&typeof h.text==='string').map((h,i)=>({revision:i+1,answerId:typeof h.answerId==='string'&&/^[-\w]{8,90}$/.test(h.answerId)?h.answerId:undefined,resolution:['solved','unsolved'].includes(h.resolution?.outcome)?{outcome:h.resolution.outcome,reason:['wrong_intent','wrong_route','missing_detail','other'].includes(h.resolution.reason)?h.resolution.reason:null}:undefined,sourceIds:sourceIds(h.sourceIds),assistance:h.assistance&&typeof h.assistance.text==='string'?{text:clean(h.assistance.text,900),sourceIds:sourceIds(h.assistance.sourceIds),mode:'restored',notice:'not-reverified',intent:['metro','rail','taxi','flight','hotel','charging','luggage','metro_ticket','restaurant','nearby','other','unclear'].includes(h.assistance.intent?.kind)?{kind:h.assistance.intent.kind,...Object.fromEntries(['origin','destination','via','city'].map(k=>[k,typeof h.assistance.intent[k]==='string'?clean(h.assistance.intent[k],100):null]))}:undefined,tool:h.assistance.tool?.kind==='metro'&&h.assistance.tool.metro?{kind:'metro',metro:Object.fromEntries(['origin','destination','via'].map(k=>[k,typeof h.assistance.tool.metro[k]==='string'?clean(h.assistance.tool.metro[k],100):null]))}:undefined}:undefined,text:clean(h.text),channel:['voice','text','click'].includes(h.channel)?h.channel:'text',reply:typeof h.reply==='string'?clean(h.reply):undefined,language:h.language==='zh'?'zh':'en',offers:Array.isArray(h.offers)?h.offers.filter(t=>['hotel','flight','rail','restaurant'].includes(t)):[],context:{city:typeof h.context?.city==='string'?clean(h.context.city,80):'',preferences:preferences(h.context?.preferences||{})},factsChanged:[]}));
 s.revision=s.history.length;s.initialRequest=saved.initialRequest&&typeof saved.initialRequest.text==='string'?{text:clean(saved.initialRequest.text),channel:saved.initialRequest.channel==='voice'?'voice':'text'}:null;
 s.answered=Array.isArray(saved.answered)?saved.answered.filter(x=>BASE.questionOrder.includes(x)):[];s.currentIssue=TASKS.includes(saved.currentIssue)?saved.currentIssue:null;s.outcomes=Object.fromEntries(Object.entries(saved.outcomes||{}).filter(([k,v])=>TASKS.includes(k)&&v==='done'));
 s.lastQuestion=reply(s).question;s.lastReply=reply(s).say;return s;
}
function memory(s){return{facts:s.facts,tasks:s.tasks,language:s.language,outputLanguage:s.outputLanguage,preferences:s.preferences||{},history:s.history,initialRequest:s.initialRequest,answered:s.answered,currentIssue:s.currentIssue,outcomes:s.outcomes};}
function proposal(p,state){if(!p||!p.facts||!Array.isArray(p.evidence))throw Error('PROPOSAL_SCHEMA');const facts=validatePatch(p.facts),messages=state.history.map(x=>x.text).join('\n');for(const key of Object.keys(facts)){const e=p.evidence.find(e=>e.field===key);if(!e||typeof e.quote!=='string'||!e.quote.trim()||!messages.includes(e.quote))throw Error('PROPOSAL_UNGROUNDED');}return facts;}
return{VERSION,BASE,PREFS,preferences,FIELDS,TASKS,TITLES,URLS,clean,state,parse,speechDecision,apply,reply,validatePatch,proposal,restoreMemory,memory};
});
