'use strict';
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;try{
if(b.dataset.tab){tab=b.dataset.tab;location.hash=tab;render();return;}if(b.dataset.say){tab='chat';await send(b.dataset.say);return;}if(b.dataset.source){source(b.dataset.source);return;}if(b.dataset.guide){guide(b.dataset.guide);return;}if(b.dataset.help){help(b.dataset.help);return;}if(b.dataset.p oster)return;
if(b.dataset.poster){poster();return;}if(b.dataset.voice){voiceDialog();return;}if(b.dataset.near){tab='nearby';render();$('#category').value=b.dataset.near;return;}if(b.dataset.provider){toast(T('Opened the provider. Nothing is booked in this app.','已打开服务方；本应用未生成订单。'));return;}
if(b.dataset.check){$('#source-result').textContent='Checking…';if(!status.server){$('#source-result').textContent='Live inspection requires the local or cloud API.';return;}const r=await api('source',{id:b.dataset.check});$('#source-result').textContent=JSON.stringify(r,null,2);return;}
if(b.dataset.photo){if((state.battery!==null&&state.battery<=10)||['poor','offline'].includes(state.network)){toast('Image loading paused during recovery.');return;}const s=D.sources.find(x=>x.id===b.dataset.photo),m=s?.media?.[Number(b.dataset.index)];if(!m)return;const img=document.createElement('img');img.src=m.url;img.alt=m.alt;img.className='photo';img.referrerPolicy='no-referrer';img.onerror=()=>img.replaceWith(document.createTextNode('Image unavailable; open the publisher page.'));$('#modal-content').append(img);return;}
if(b.dataset.feedback){if(!status.server||status.cloud){toast('Persistent feedback requires local Operations or a shared cloud review store.');return;}const m=messages.find(x=>x.trace===b.dataset.trace);await api('feedback',{trace:m.trace,receipt:m.receipt,category:b.dataset.feedback,note:''});b.disabled=true;toast('Feedback saved to local review queue.');return;}
if(b.dataset.geocode!==undefined){const x=near.candidates[Number(b.dataset.geocode)];locationChoice={coords:x.coords,system:'GCJ02'};$('#place').value=x.label;$('#location-note').textContent='Chosen geocoding result. Search again to find nearby services.';return;}
if(b.dataset.place!==undefined){const x=near.rows[Number(b.dataset.place)],u=new URL('https://uri.amap.com/marker');u.searchParams.set('position',x.coords.join(','));u.searchParams.set('name',x.name);u.searchParams.set('coordinate','gaode');modal(`<h2>${E(x.name)}</h2><p>${E(x.address)}</p><span class="badge warn">POI_ONLY · availability unknown</span><p class="fine">Amap · ${E(near.checkedAt)} · GCJ-02 coordinates. This is not a contracted partner or confirmed reservation.</p><a href="${E(u.href)}" target="_blank" rel="noopener noreferrer">Open in Amap ↗</a>`);return;}
if(b.dataset.replay){await api('replay',{id:b.dataset.replay});operations();return;}if(b.dataset.publish){if(confirm('Publish this candidate after the displayed development replay? This is not independent user validation.')){await api('publish',{id:b.dataset.publish,confirm:true});status=await api('status');operations();}return;}
switch(b.id){
case 'send':await send();break;
case 'language':lang=lang==='en'?'zh':'en';render();break;
case 'reset':if(!confirm('Clear this in-memory conversation?'))break;voice.stop();pending?.abort();revision++;state=C.initial();messages=[];history=[];near=null;locationChoice=null;tab='chat';render();break;
case 'close-modal':voice.stop();$('#modal').close();break;
case 'voice-open':voiceDialog();break;
case 'voice-start':if((state.battery!==null&&state.battery<=10)||['offline','poor'].includes(state.network)){toast('Voice paused during power/connectivity recovery.');break;}const greet=C.reply({...state,language:lang});await voice.start({consent:$('#voice-consent').checked,language:lang==='zh'?'zh-CN':'en-US',greeting:greet.text+' '+greet.question,auto:$('#voice-auto').checked});break;
case 'voice-interrupt':voice.interrupt();break;case 'voice-pause':voice.pause();break;case 'voice-resume':voice.resume();break;case 'voice-stop':voice.stop();break;
case 'voice-send':const a=await send($('#voice-input').value);$('#voice-caption').textContent=a;if(voice.active){await voice.say(a);voice.resume();}break;
case 'connection':modal(`<h2>Connection settings</h2><p>${status.server?(status.cloud?'Cloud endpoints':'Local Node service'):'Standalone frontend preview'}</p><label>Access code — not your API key<input class="full" id="access" type="password" autocomplete="off"></label><button id="save-access">Use for this tab</button><p class="fine">Keys go in local Operations or Vercel environment variables. Access codes stay in tab memory. A cloud site cannot read your localhost.</p>`);break;
case 'save-access':access=$('#access').value;$('#access').value='';$('#modal').close();toast('Access code set in tab memory.');break;
case 'poster-add':const t=$('#poster-text').value.trim();if(!t){toast('Type a readable place name or detail first.');break;}$('#modal').close();tab='chat';await send(T('An unverified hotel poster idea: ','酒店海报的待核实线索：')+t);break;
case 'print':window.print();break;
case 'locate':if(!$('#location-consent').checked){toast('Location consent required.');break;}if(!navigator.geolocation){toast('Use a landmark instead.');break;}navigator.geolocation.getCurrentPosition(p=>{locationChoice={coords:[p.coords.longitude,p.coords.latitude],system:'GPS'};$('#location-note').textContent='Location received in this tab. Press Search to send it to Amap.';},()=>toast('Location unavailable or denied. Enter a landmark.'),{enableHighAccuracy:false,timeout:8000,maximumAge:60000});break;
case 'near-search':if(!$('#location-consent').checked){toast('Location consent required.');break;}if(!status.server){toast('Real search needs the local or configured cloud backend.');break;}b.disabled=true;near=await api('nearby',{category:$('#category').value,place:$('#place').value,city:state.city||'Shanghai',...locationChoice,consent:true});places();break;
case 'load-map':if(!near?.receipt)break;const r=await fetch('/api/arrival?action=map',{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Access':access},credentials:'same-origin',body:JSON.stringify({receipt:near.receipt,consent:true}),signal:AbortSignal.timeout(10000)});if(!r.ok){const x=await r.json();throw Error(x.error);}if(mapURL)URL.revokeObjectURL(mapURL);mapURL=URL.createObjectURL(await r.blob());$('#map').className='';$('#map').innerHTML=`<img class="map-image" src="${mapURL}" alt="Provider map showing the returned numbered places"><p class="fine">Amap attribution remains in the image. Numbered POIs are not guaranteed available services.</p>`;break;
case 'export':const data={...state,notes:'User-reported plans, not verified orders. Credentials, audio and image bytes are omitted.'};const a2=document.createElement('a');a2.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a2.download='arrival-journey.json';a2.click();setTimeout(()=>URL.revokeObjectURL(a2.href),1000);break;
case 'corpus-search':if(!status.server){toast('Index search is available in the full source runtime.');break;}const response=await fetch('/api/arrival?action=search&q='+encodeURIComponent($('#corpus-query').value)+'&city='+encodeURIComponent(state.city||'Unknown'));const data2=await response.json();$('#corpus-results').innerHTML=(data2.results||[]).map(s=>`<div class="place"><a href="${E(s.url)}" target="_blank" rel="noopener noreferrer">${E(s.title)}</a><p>${E(s.excerpt||s.summary||'')}<br>${E(s.publication_date||'date unknown')} · fetched index, not policy approval</p></div>`).join('');break;
case 'login':try{await api('login',{username:$('#username').value,password:$('#password').value});status=await api('status');operations();}catch(x){$('#login-error').textContent=x.message;}break;
case 'logout':await api('logout',{});status=await api('status');operations();break;
case 'save-model':const config={model:$('#model-name').value,maxTokens:Number($('#tokens').value)};if($('#model-key').value)config.key=$('#model-key').value;await api('settings',{model:config});$('#model-key').value='';status=await api('status');operations();break;
case 'clear-model':await api('settings',{model:{clear:true}});status=await api('status');operations();break;
case 'save-map':await api('settings',{mapKey:$('#map-key').value});$('#map-key').value='';status=await api('status');operations();break;
case 'propose':await api('propose',{policy:{battery:Number($('#policy-battery').value),failures:Number($('#policy-failures').value),priority:$('#policy-priority').value},reason:$('#policy-reason').value});operations();break;
case 'rollback':if(confirm('Restore the previous published policy?')){await api('rollback',{confirm:true});status=await api('status');operations();}break;
}
}catch(err){toast(err.message||'Operation failed');}finally{if(b.id==='near-search')b.disabled=false;}});
document.addEventListener('change',e=>{if(e.target.id==='model-consent')modelConsent=e.target.checked;if(e.target.id==='live')live=e.target.checked;if(e.target.id==='place')locationChoice=null;if(e.target.id==='poster-file'){const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type)){toast('Use PNG/JPEG/WebP under 8 MB.');return;}if(posterURL)URL.revokeObjectURL(posterURL);posterURL=URL.createObjectURL(f);$('#poster-preview').src=posterURL;}});
document.addEventListener('keydown',e=>{if(e.target.id==='input'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});$('#modal').addEventListener('cancel',()=>voice.stop());document.addEventListener('visibilitychange',()=>{if(document.hidden)voice.pause();});window.addEventListener('pagehide',()=>voice.stop());
const chosenTab=location.hash.slice(1);if(['chat','nearby','trip','guides','ops','operations'].includes(chosenTab))tab=chosenTab==='operations'?'ops':chosenTab;render();if(location.protocol==='file:')$('#runtime').textContent='Standalone preview';else api('status').then(x=>{status=x;$('#runtime').textContent=x.cloud?'Cloud · protected APIs':'Local Node · connected';if(tab==='ops')operations();}).catch(()=>{$('#runtime').textContent='Frontend only · no backend';});
