(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelEvents=factory();})(globalThis,function(){
'use strict';
const records=[
{id:'event-sh-snacks-2026',title:'上海小吃嘉年华 / Shanghai Snack Carnival',url:'https://english.shanghai.gov.cn/en-Events/20260918/34a075bf3cb74b0eadcffdbca9ddb7c8.html',startDate:'2026-09-17',endDate:'2026-09-27',district:'普陀',districtEn:'Putuo',locationZh:'环球港南广场',locationEn:'Global Harbor South Square',topics:['活动','外国游客','美食','普陀','小吃','events','food','international'],summaryZh:'9月17日至27日，普陀区环球港南广场有上海小吃嘉年华，集合中国地方小吃及国际风味。官方英语页面可供外国游客查阅；未核对外语现场服务和每日具体时段。',summary:'September 17–27 at Global Harbor South Square, Putuo: Chinese regional snacks and international flavors. An official English page is available; on-site language support and daily hours are not verified.',published:'2026-09-18'},
{id:'event-sh-design-2026',title:'世界设计之都大会展览 / World Design Cities exhibition',url:'https://english.shanghai.gov.cn/en-Events/20260924/7782fae8d4974b249e6f085654bc403c.html',startDate:'2026-09-26',endDate:'2026-09-30',district:'黄浦',districtEn:'Huangpu',locationZh:'局门路689号',locationEn:'689 Jumen Road',topics:['活动','外国游客','展览','设计','黄浦','events','design','international'],summaryZh:'展览9月26日至30日，9月28日上午不开放；地点黄浦区局门路689号。官方说明免费，展览与论坛须在“世界设计之都大会WDCC”官方微信小程序提前登记。具国际设计内容和官方英文介绍，不承诺现场外语服务。',summary:'Exhibition September 26–30, closed on the morning of September 28, at 689 Jumen Road, Huangpu. Free, with advance registration via the official 世界设计之都大会WDCC WeChat mini program. International design content and an official English guide; on-site language support is not confirmed.',published:'2026-09-24'},
{id:'event-sh-light-2026',title:'上海国际光影节 / Shanghai International Light Festival',url:'https://en.shio.gov.cn/TrueCMS/shxwbgs/newss/content/20260908201822130.html',startDate:'2026-09-17',endDate:'2026-10-16',district:'全市',districtEn:'Citywide',locationZh:'各区分会场，按官方活动表选择',locationEn:'Venues across Shanghai; choose from the official programme',topics:['活动','外国游客','光影节','夜游','events','light festival','international'],summaryZh:'上海市政府新闻办介绍，2026年上海国际光影节9月17日至10月16日举办，面向本地和海内外游客，覆盖全市各区。请在官方安排中选择具体场地与日期；不能把整体节期当作每场演出的每天营业时间。',summary:'Shanghai’s official announcement schedules the light festival from September 17 to October 16, 2026, welcoming residents and visitors from China and abroad. Select the exact district venue and date from the programme; the overall festival dates do not establish daily opening for every show.',published:'2026-09-08'}
].map(r=>({...r,publisher:'Shanghai Government',sourceType:'official',recordType:'event',kind:'reviewed_reference',city:'Shanghai',reviewedAt:'2026-09-25',reviewDays:7,active:true,foreignVisitorNote:'Official English information; on-site language and admission conditions vary.'}));
function active(rows=records,now=Date.now()){return rows.filter(r=>r.recordType==='event'&&r.active!==false&&r.lastCheck?.status!=='changed'&&Number.isFinite(Date.parse(r.startDate))&&Number.isFinite(Date.parse(r.endDate))&&Date.parse(r.endDate+'T23:59:59+08:00')>=now&&Date.parse(r.startDate+'T00:00:00+08:00')<=now+14*86400000);}
return{records,active};
});
