/* Optional, previewable transcript sharing. Quick ratings remain anonymous events. */
(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('click',e=>{const button=e.target.closest('[data-feedback-detail]');if(!button)return;const state=TravelApp.getState(),h=state.history.find(h=>h.revision===Number(button.dataset.feedbackDetail));if(!h)return;
 const context=TravelFeedback.snapshot(state,h.revision),zh=h.language==='zh';let d=document.getElementById('feedback-detail-dialog');if(!d){d=document.createElement('dialog');d.id='feedback-detail-dialog';document.body.append(d);}
 d.innerHTML='<div class="dialog-head"><h2>'+(zh?'把问题定位清楚':'Help locate this issue')+'</h2><button data-close class="light">'+(zh?'关闭':'Close')+'</button></div><p>'+esc(context.at(-1)?.question)+'</p><form><label>'+(zh?'问题类型':'Issue category')+'<select name="category">'+Object.entries(TravelFeedback.labels).map(([k,v])=>'<option value="'+k+'">'+esc(v)+'</option>').join('')+'</select></label><label>'+(zh?'哪里不对，或者期望得到什么？':'What was wrong, or what did you expect?')+'<textarea name="comment" rows="3" maxlength="1500" required></textarea></label><label><input name="share" type="checkbox">'+(zh?'附上下面这些相关对话（最多 8 轮）':'Include the relevant conversation below (up to 8 turns)')+'</label><p class="muted">'+(zh?'只在提交后上传。已尝试隐藏密钥、邮箱和长号码，请检查预览，仍有私人信息时不要勾选。保存最多 30 天；可以撤回。':'Uploaded only when submitted. Keys, emails and long numbers are masked; inspect the preview and leave unchecked if it still contains private information. Retained up to 30 days; you can withdraw it.')+'</p><details><summary>'+(zh?'查看待分享内容':'Preview shared context')+'</summary><div class="feedback-context">'+context.map(r=>'<article><strong>'+esc(r.question)+'</strong><p>'+esc(r.answer)+'</p><small>'+esc(r.sourceIds.join(' · '))+'</small></article>').join('')+'</div></details><button class="primary" type="submit">'+(zh?'提交问题供排查':'Submit issue')+'</button><p role="status" data-note></p></form>';
 const f=d.querySelector('form'),note=d.querySelector('[data-note]');f.elements.category.value=({wrong_intent:'intent_error',wrong_route:'wrong_route',missing_detail:'missing_detail'}[h.resolution?.reason]||'other');
 f.elements.comment.onchange=()=>{if(f.elements.category.value==='other')f.elements.category.value=TravelFeedback.classify(f.elements.comment.value);};d.querySelector('[data-close]').onclick=()=>d.close();
 f.onsubmit=async event=>{event.preventDefault();const submit=f.querySelector('[type=submit]');submit.disabled=true;try{const shared=f.elements.share.checked,r=await TravelOpsClient.report(h,{category:f.elements.category.value,comment:f.elements.comment.value,shareContext:shared,context:shared?context:[]});note.textContent=(zh?'已提交工单；运营可定位、回放和创建技能候选。':'Issue saved for review, replay and skill improvements.')+' #'+r.result.id.slice(0,8);const withdraw=document.createElement('button');withdraw.type='button';withdraw.className='light';withdraw.textContent=zh?'撤回此问题和对话':'Withdraw issue and context';note.append(withdraw);withdraw.onclick=async()=>{withdraw.disabled=true;try{await CloudOps.api({action:'feedback-case-delete',id:r.result.id});note.textContent=zh?'已撤回并删除。':'Withdrawn and deleted.';}catch(err){withdraw.disabled=false;note.textContent=err.message;}};}catch(err){submit.disabled=false;note.textContent=(zh?'尚未保存：':'Not saved: ')+err.message;}};d.showModal();
});
})();
