'use strict';
const crypto=require('node:crypto'),F=require('./feedback-shared');
const statuses=['open','investigating','awaiting_evidence','fix_proposed','closed'];
const category=v=>({wrong_intent:'intent_error',wrong_route:'wrong_route',missing_detail:'missing_detail',other:'other'}[v]||v);
const fingerprint=row=>crypto.createHash('sha256').update(JSON.stringify({category:row.category,comment:row.comment,context:row.context})).digest('hex');
function summarize(row){const last=row.context?.at(-1);return{need:last?.question||'未附上原始问题',problem:row.comment||F.labels[row.category],observed:last?.answer||'未附上回答',hypothesis:row.category,scope:'根据用户提交的记录提取；分类为待核对假设，不代表已证实错误。'};}
function submit(s,visitor,input,now=Date.now()){
 if(!/^[-\w]{8,90}$/.test(input.chat)||!/^[-\w]{8,90}$/.test(input.answerId))throw Error('CASE_SCHEMA');
 const reason=category(input.category||'other');if(!F.labels[reason]||typeof input.comment!=='string'||input.comment.length>1500)throw Error('CASE_SCHEMA');
 const key=visitor+':'+input.chat+':'+input.answerId;const ctx=input.shareContext===true&&Array.isArray(input.context)?input.context.slice(-8).map((h,i)=>({revision:Number.isSafeInteger(h.revision)?h.revision:i+1,question:F.redact(h.question,600),answer:F.redact(h.answer,1400),language:h.language==='en'?'en':'zh',kind:String(h.kind||'other').replace(/[^a-z_]/g,'').slice(0,30),sourceIds:(Array.isArray(h.sourceIds)?h.sourceIds:[]).filter(x=>typeof x==='string'&&/^[-\w]{1,100}$/.test(x)).slice(0,8),executionId:/^[-\w]{8,90}$/.test(h.executionId)?h.executionId:null})):[];
 s.feedbackCases=(s.feedbackCases||[]).filter(r=>now-r.createdAt<30*86400000);let row=s.feedbackCases.find(r=>r.key===key);const isNew=!row;if(!row){if(s.feedbackCases.length>=200)throw Error('CASE_CAPACITY');const own=s.feedbackCases.filter(r=>r.session.startsWith(visitor+':'));if(own.filter(r=>r.status!=='closed').length>=10||own.filter(r=>now-r.createdAt<86400000).length>=20)throw Error('CASE_SUBMISSION_LIMIT');row={id:crypto.randomUUID(),key,answerId:input.answerId,session:visitor+':'+input.chat,createdAt:now,version:0,status:'open',actions:[],replays:[]};s.feedbackCases.push(row);}
 Object.assign(row,{updatedAt:now,version:row.version+1,category:reason,suggestedCategory:F.classify(input.comment),comment:F.redact(input.comment,1500),context:ctx,contextOrigin:ctx.length?'traveler-shared-redacted':'not-shared',shareContext:input.shareContext===true,kind:ctx.at(-1)?.kind||'other'});const contentHash=fingerprint(row);if(row.contentHash!==contentHash){delete row.modelSummary;delete row.skillCandidateId;}row.contentHash=contentHash;row.summary=summarize(row);if(!isNew&&row.status==='closed')row.status='open';s.feedbackCases=s.feedbackCases.slice(-200);return{id:row.id,version:row.version,category:row.category,contextTurns:ctx.length};
}
function get(s,id){const row=(s.feedbackCases||[]).find(r=>r.id===id);if(!row)throw Error('CASE_NOT_FOUND');return row;}
function update(s,input,actor,now=Date.now()){const row=get(s,input.id);if(input.version!==row.version)throw Error('STALE_CASE');if(!statuses.includes(input.status)||!F.labels[input.category])throw Error('CASE_SCHEMA');if(typeof input.note!=='string'||input.note.length>2000)throw Error('CASE_SCHEMA');const nextHash=fingerprint({...row,category:input.category});if(input.status==='closed'&&(!input.note.trim()||!row.replays?.some(r=>r.answer&&r.contentHash===nextHash)))throw Error('CASE_REPLAY_REQUIRED');if(row.contentHash!==nextHash){delete row.modelSummary;delete row.skillCandidateId;}row.contentHash=nextHash;row.status=input.status;row.category=input.category;row.summary=summarize(row);row.version++;row.updatedAt=now;row.actions.push({at:now,actor,type:'manual',note:F.redact(input.note),status:input.status,category:input.category});row.actions=row.actions.slice(-30);return row;}
function suggestedSkill(row,active){const directions={intent_error:'先识别当前想办的服务，再处理附近等地点修饰。保留否定和纠正，不能答非所问。',fact_error:'只引用适用的已核对资料。未知的价格、电话、地址不猜测，说明待补资料。',stale_info:'优先日期最新且仍有效的来源；历史新闻不能作为现行条件。',wrong_route:'核对起点、终点和出行方式，地铁与城际铁路分开，缺少端点再问。',missing_detail:'先直接回答当前问题，再指出确实缺少的细节，避免通用追问。',process_issue:'保留已知需求，下一步只问缺失信息；已确认的内容不重复询问。',language_issue:'严格跟随用户选择的输出语言，资料语言不改变输出语言。',connection_issue:'无法连接时准确说明体验码与API Key的区别，不把连接失败当作需求不明。',other:'优先处理当前明确问题；证据不足时说明具体缺口。'};return{...active,guidance:directions[row.category],...(row.category==='missing_detail'?{topK:Math.min(12,active.topK+2)}:{})};}
function board(s,now=Date.now()){const rows=(s.feedbackCases||[]).filter(r=>now-r.createdAt<30*86400000),closed=rows.filter(r=>r.status==='closed'),kinds=Object.keys(F.labels).map(key=>({key,label:F.labels[key],count:rows.filter(r=>r.category===key).length}));return{total:rows.length,open:rows.filter(r=>r.status!=='closed').length,contextAttached:rows.filter(r=>r.context.length).length,replayed:rows.filter(r=>r.replays?.length).length,closed:closed.length,meanClosureHours:closed.length?closed.reduce((a,r)=>a+(r.updatedAt-r.createdAt)/3600000,0)/closed.length:null,categories:kinds,retention:'仅用户提交排查的相关对话，最多8轮；脱敏，保存30天/最近200单。',scope:'工单关闭不改写用户解决评价；摘要和分类需人工核对。'};}
module.exports={...F,submit,get,update,suggestedSkill,summarize,board,statuses,category};
