'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const L=require('./library'),E=require('./engine'),A=require('./assistant'),{createApp}=require('./server');
test('unified catalog preserves original curated entries, deduplicates URLs and filters cities',()=>{const report=require('../data/official/collection-report.json');assert.equal(L.indexCount,report.unique_index_urls);assert.ok(L.indexCount>=5000);assert.equal(report.preserved_prior_rows,1114);assert.equal(new Set(L.records.filter(r=>!r.recordType).map(r=>r.url)).size,L.records.filter(r=>!r.recordType).length);assert.equal(L.get('sh-metro').city,'Shanghai');assert.ok(L.search('metro','Shanghai').length);assert.ok(L.search('metro','Beijing').every(r=>!r.city||['China','Beijing'].includes(r.city)));assert.ok(L.search('','Unknown','index').every(r=>!r.summary&&!r.summaryZh));});
test('selecting a source is context, not traveler facts; memory keeps per-turn citations',()=>{let s=E.apply(E.state(),{type:'text',text:'Boston hotel please',sourceIds:['sh-metro','sh-metro','fake-id','<script>']});assert.equal(s.facts.city,'Boston');assert.deepEqual(s.history[0].sourceIds,['sh-metro','fake-id']);assert.deepEqual(L.ids(s.history[0].sourceIds),['sh-metro']);s.history[0].assistance={text:'Stored answer',sourceIds:['sh-metro'],mode:'deepseek'};const restored=E.restoreMemory(E.memory(s));assert.equal(restored.history[0].assistance.mode,'restored');assert.equal(restored.confirmedRevision,null);assert.deepEqual(E.state().history,[]);});
test('answer validation rejects invented citations, numbers, bookings, URLs and secret requests',()=>{const evidence=[{id:'s',summary:'The route has 3 stops.'}];assert.equal(A.validate({text:'Check the 3 stops.',source_ids:['s']},evidence,[]).mode,'deepseek');for(const value of [{text:'test',source_ids:['invented']},{text:'9 stops',source_ids:['s']},{text:'已出票',source_ids:['s']},{text:'https://bad.example',source_ids:['s']},{text:'请上传护照',source_ids:['s']},{text:'An answer',source_ids:[]}])assert.throws(()=>A.validate(value,evidence,[]));});
test('index-only, foreign-city and fee questions do not call the model',async()=>{let n=0;const model={call:async()=>{n++;throw Error('should not call');}};const index=L.records.find(r=>!r.summary&&!r.summaryZh);for(const [text,sourceIds,mode]of [['请解释这份资料',[index.id],'source-gap'],['Boston metro please',['sh-metro'],'source-gap'],['去上海的签证条件',[],'source-gap'],['上海打车多少钱',[],'fixed-guidance']]){const state=E.apply(E.state(),{type:'text',text,sourceIds});const out=await A.assist({state,model,signal:new AbortController().signal});assert.equal(out.mode,mode);}assert.equal(n,0);});
async function fixture(t,provider){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vc55-library-'));const app=createApp({runtimeDir:dir,env:{ADMIN_PASSWORD:'test-admin',DEEPSEEK_API_KEY:'test-key-not-real'},fetch:provider});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(async()=>{app.server.closeAllConnections();await new Promise(r=>app.server.close(r));assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(dir,{recursive:true,force:true});});let cookie='';const request=async(p,b)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/v5/'+p,{method:b===undefined?'GET':'POST',headers:{cookie,...(b===undefined?{}:{'Content-Type':'application/json'})},body:b===undefined?undefined:JSON.stringify(b)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,body:await r.json()};};return{app,request};}
const response=value=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({intent:{kind:'other'},...value})}}],usage:{prompt_tokens:50,completion_tokens:20,total_tokens:70}}),{headers:{'Content-Type':'application/json'}});
test('disabled source from original library cannot be used by the shared model',async()=>{const state=E.apply(E.state(),{type:'text',text:'上海地铁怎么坐',sourceIds:['sh-metro']});const out=await A.assist({state,records:[],model:{call:()=>{throw Error('unexpected call');}},signal:new AbortController().signal});assert.equal(out.mode,'source-gap');});
test('voice and text share the configured model, consent, references and durable answers',async t=>{const calls=[];const {app,request:c}=await fixture(t,async(url,opts)=>{calls.push({url,payload:JSON.parse(JSON.parse(opts.body).messages[1].content)});return response({text:'可先按地铁出行偏好安排路线，请核对站点和出口。',source_ids:['sh-metro']});});await c('status');await c('turn',{requestId:'one',expectedRevision:0,event:{type:'text',text:'上海地铁怎么乘坐',sourceIds:['sh-metro']}});assert.equal((await c('assist',{revision:1,modelConsent:true})).status,403);await c('login',{username:'admin',password:'test-admin'});assert.equal((await c('assist',{revision:1,modelConsent:false})).body.mode,'default');let out=await c('assist',{revision:1,modelConsent:true});assert.equal(out.body.answer.mode,'deepseek');assert.deepEqual(out.body.answer.sourceIds,['sh-metro']);await c('assist',{revision:1,modelConsent:true});assert.equal(calls.length,1);const begin=(await c('begin',{})).body;await c('turn',{requestId:'two',expectedRevision:1,session_id:begin.session_id,event:{type:'text',channel:'voice',text:'我在上海，继续看看地铁',sourceIds:['sh-metro']}});out=await c('assist',{revision:2,modelConsent:true});assert.equal(out.body.answer.mode,'deepseek');assert.equal(calls.length,2);assert.equal(calls[1].payload.history.length,2);assert.ok(calls[1].payload.evidence.some(e=>e.id==='sh-metro'));assert.equal(calls[1].url,'https://api.deepseek.com/chat/completions');assert.equal(app.base.model.status().totalTokens,140);const status=(await c('status')).body;assert.equal(status.state.history[1].assistance.mode,'deepseek');assert.equal(status.state.facts.city,'Shanghai');assert.ok(!JSON.stringify(status).includes('test-key-not-real'));});
test('slow shared model output cannot overwrite a newer turn or a reset chat',async t=>{let release,started;const reached=new Promise(r=>started=r);const {request:c}=await fixture(t,async()=>{started();await new Promise(r=>release=r);return response({text:'A relaxed trip sounds good.',source_ids:[]});});await c('login',{username:'admin',password:'test-admin'});await c('turn',{requestId:'one',expectedRevision:0,event:{type:'text',text:'Shanghai hotel please'}});const pending=c('assist',{revision:1,modelConsent:true});await reached;await c('begin',{reset:true,language:'zh'});release();const out=await pending;assert.equal(out.status,409);assert.equal((await c('status')).body.state.history.length,0);});
test('low power keeps shared assistant off even when configured and authorized',async t=>{let calls=0;const {request:c}=await fixture(t,async()=>{calls++;throw Error('no');});await c('login',{username:'admin',password:'test-admin'});await c('turn',{requestId:'one',expectedRevision:0,event:{type:'text',text:'Shanghai battery 3%'}});assert.equal((await c('assist',{revision:1,modelConsent:true})).body.mode,'context-limited');assert.equal(calls,0);});

test('numeric grounding ignores formatting whitespace and uses whole tokens and cited review dates',()=>{
 const evidence=[{id:'s',summary:'Line 2、Line 11; 3% discount.',reviewedAt:'2026-09-25'}];
 assert.equal(A.validate({text:'Line 2 and Line 11. Reviewed 2026-09-25. 3 %.',source_ids:['s']},evidence,[]).mode,'deepseek');
 assert.throws(()=>A.validate({text:'Line 1 or 30%.',source_ids:['s']},evidence,[]),/ANSWER_NUMBER/);
 assert.throws(()=>A.validate({text:'Reviewed 2030.',source_ids:['s']},evidence,[]),/ANSWER_NUMBER/);
});
