'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),L=require('./loop-evolution'),O=require('./operations'),{catalog}=require('./ops-api'),H=require('./harness');
const actor={name:'admin',role:'admin'};
function fixture(){let state=O.initial();return{get state(){return state;},store:{read:async()=>structuredClone(state),mutate:async f=>{const copy=structuredClone(state),out=f(copy);assert.ok(!out?.then,'synchronous CAS');state=copy;return out;}}};}
test('new wording ranges are deterministic, unique, and preserve independent seed labels and provenance',()=>{const seen=new Set();for(let n=0;n<24000;n++){const c=L.item(n);assert.ok(!seen.has(c.queryHash));seen.add(c.queryHash);assert.equal(c.type,'rag');assert.equal(c.provenance.type,'authored-template-variation');assert.ok(c.provenance.seedId);assert.ok(c.expect.sourceId);assert.equal(c.split,'generated-development');}assert.deepEqual(L.item(13579),L.item(13579));assert.throws(()=>L.item(L.poolSize),/EXHAUSTED/);});
test('start requires admin and 10k minimum, reserves inputs before work, and cannot replace a running job',async()=>{const f=fixture();await assert.rejects(L.start(f.store,{role:'reviewer'},{},catalog),/ADMIN/);await assert.rejects(L.start(f.store,actor,{count:9999},catalog),/OPTIONS/);const run=await L.start(f.store,actor,{count:10000,seed:'test'},catalog);assert.equal(run.start,L.summary({}).pool.reserved);assert.equal(L.summary(f.state).pool.reserved,run.start+10000);await assert.rejects(L.start(f.store,actor,{},catalog),/BUSY/);assert.equal(H.state(f.state).active.version,'skill-1');});
test('step evaluates a bounded batch without publishing and resumes exact progress after reload',async()=>{const f=fixture(),run=await L.start(f.store,actor,{count:10000},catalog),rows=[];const first=await L.step(f.store,actor,{id:run.id},catalog,entry=>rows.push(...entry.checks));assert.equal(first.index,L.BATCH);assert.equal(first.baseline.total,L.BATCH);assert.equal(rows.length,L.BATCH);assert.ok(!('baselineBits'in first));assert.equal(H.state(f.state).active.version,'skill-1');const second=await L.step(f.store,actor,{id:run.id},catalog);assert.equal(second.index,2*L.BATCH);assert.equal(second.baseline.total,2*L.BATCH);assert.equal(second.paidModelCalls,0);});
test('source changes invalidate an in-progress run and new rounds consume a different wording range',async()=>{const f=fixture(),run=await L.start(f.store,actor,{count:10000},catalog);await f.store.mutate(s=>{s.sources[0].summaryZh+=' 资料发生变化。';});const ended=await L.step(f.store,actor,{id:run.id},catalog);assert.equal(ended.status,'invalidated');const next=await L.start(f.store,actor,{count:10000},catalog);assert.equal(next.start,run.start+10000);assert.notEqual(L.item(run.start).queryHash,L.item(next.start).queryHash);assert.equal(L.summary(f.state).history.length,1);});
test('a changed active skill version invalidates even when numerical parameters match',async()=>{const f=fixture(),run=await L.start(f.store,actor,{count:10000},catalog);await f.store.mutate(s=>{s.harness={active:{...H.DEFAULT,version:'new-release'},candidates:[]};});assert.equal((await L.step(f.store,actor,{id:run.id},catalog)).status,'invalidated');});

test('changed evaluation code invalidates resumable evidence',async()=>{const f=fixture(),run=await L.start(f.store,actor,{count:10000},catalog);await f.store.mutate(s=>{s.loopEvolution.current.evaluatorHash='old-code';});assert.equal((await L.step(f.store,actor,{id:run.id},catalog)).status,'invalidated');});
