/* Public network routing, shared by server and browser. No live dispatch feed. */
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./metro-data'));else r.TravelMetro=f(r.ShanghaiMetroData);})(globalThis,function(D){
'use strict';
const source='https://english.shanghai.gov.cn/en-Latest-WhatsNew/20240924/b625d488216241f78f743cd87a40df0c.html',service='https://service.shmetro.com/';
const stations=new Map(D.stations.map(s=>[s.id,s])),lines=new Map(D.lines.map(l=>[l.id,l])),aliases=new Map(),rawAliases=new Map(),graph=new Map(),stationLines=new Map();
const norm=s=>String(s||'').toLowerCase().replace(/(?:地铁站|地铁|站$|metro station|station$)|[\s·•&（）()'’'-]/g,'');
const literal=s=>String(s||'').toLowerCase().replace(/[\s·•&（）()'’'-]/g,'');
function alias(a,id){aliases.set(norm(a),id);rawAliases.set(literal(a),id);}
for(const s of stations.values())for(const a of [s.id,s.zh,s.en])alias(a,s.id);
for(const [id,as]of Object.entries({'浦东1号2号航站楼':['浦东机场','浦东国际机场','Pudong airport','PVG','Pudong International Airport','Pudong T1','Pudong T2'],'上海火车站':['上海站','Shanghai railway station','Shanghai train station'],'虹桥火车站':['上海虹桥站','Shanghai Hongqiao','Hongqiao railway station','Hongqiao train station'],'豫园':['城隍庙','Yu Garden','Yuyuan Garden','Yuyuan'],'南京东路':['East Nanjing Road','Nanjing East Road'],'人民广场':["People's Square",'Peoples Square'],'陆家嘴':['Lujiazui'],'国家会展中心(2号线)':['徐泾东','Xujing East'],'浦东南路(原东昌路)':['东昌路','Dongchang Road']}))for(const a of as)alias(a,id);
for(const s of D.stations){const duplicates=D.stations.filter(x=>x.en===s.en);if(duplicates.length>1){rawAliases.delete(literal(s.en));aliases.delete(norm(s.en));const ns=D.lines.filter(l=>l.stations.includes(s.id));for(const line of ns)alias(s.en+' (Line '+line.name.replace('号线','')+')',s.id);}}
alias('新天地','一大会址·新天地');
const origins={hongqiao:{zh:'虹桥火车站',en:'Hongqiao Railway Station'},nanjing:{zh:'南京东路',en:'East Nanjing Road'},lujiazui:{zh:'陆家嘴',en:'Lujiazui'}};
function resolve(v){return stations.has(v)?v:aliases.get(norm(v))||null;}
function hits(text){const t=literal(text),found=[];for(const [alias,id]of rawAliases){if(alias.length>1)for(let i=t.indexOf(alias);i>=0;i=t.indexOf(alias,i+1))found.push({id,i,n:alias.length});}found.sort((a,b)=>a.i-b.i||b.n-a.n);const used=[];for(const h of found)if(!used.some(a=>a.id===h.id||(h.i>=a.i&&h.i<a.i+a.n)))used.push(h);return used.map(h=>h.id);}
function intent(text,city,history=[]){const t=String(text||''),ids=hits(t);if(city&&!/^(Shanghai|上海)$/i.test(city)&&ids.length<2)return null;const previous=history.at(-1),prior=previous?.assistance?.intent?.kind==='metro'?previous.assistance.intent:previous?intent(previous.text,previous.context?.city,[]):null;const positive=t.replace(/(?:不要|不是|不坐|不乘|不想|不|not|no|don't|do not)\s*(?:.{0,4}?)?(?:出租车|打车|taxi|cab\b|高铁|火车票|train tickets?|rail tickets?)/gi,'');if(/出租车|打车|taxi|cab\b|高铁|火车票|train tickets?|rail tickets?/i.test(positive))return null;if(/(?:不坐|不要|不是|not|no)\s*(?:the\s+)?(?:地铁|metro|subway)/i.test(t))return null;const explicit=/地铁|metro|subway|豫园|yuyuan|yu garden/i.test(t);if(!explicit&&!(prior&&ids.length))return null;let origin=ids.length>1?ids[0]:null,destination=ids.length>1?ids.at(-1):ids[0]||null,via=null;if(prior&&ids.length===1){if(/(?:终点|目的地).{0,3}(?:改|换)|(?:改|换).{0,3}(?:终点|目的地)|destination.{0,12}(?:now|is|to)|(?:change|arrival).{0,20}destination/i.test(t)){origin=prior.origin;destination=ids[0];}else if(/从|出发|from|start/i.test(t)){origin=ids[0];destination=prior.destination;}else{origin=prior.origin;destination=ids[0];}if(!prior.origin&&prior.destination&&!/改|终点|目的地|instead|destination/i.test(t)){origin=ids[0];destination=prior.destination;}}if(/途经|经过|via|stop at/i.test(t)&&ids.length){via=ids.at(-1);if(ids.length>=3){origin=ids[0];destination=ids[1];}else if(prior){origin=prior.origin;destination=prior.destination;}}return{kind:'metro',origin,destination,via};}
function edge(a,b,e){if(!graph.has(a))graph.set(a,[]);graph.get(a).push({to:b,...e});}
for(const l of lines.values()){if(/市域|磁浮/.test(l.name))continue;for(const id of l.stations){if(!stationLines.has(id))stationLines.set(id,[]);stationLines.get(id).push(l.id);}const pairs=l.stations.slice(1).map((b,i)=>[l.stations[i],b]);if(l.loop)pairs.push([l.stations.at(-1),l.stations[0]]);for(const [a,b]of pairs){edge(l.id+'|'+a,l.id+'|'+b,{cost:1,line:l.id,from:a,station:b});edge(l.id+'|'+b,l.id+'|'+a,{cost:1,line:l.id,from:b,station:a});}}
for(const [station,ids]of stationLines)for(const a of ids)for(const b of ids)if(a!==b)edge(a+'|'+station,b+'|'+station,{cost:100,line:b,transfer:true,station,from:station});
function path(from,to){const dist=new Map(),prev=new Map(),pending=new Set();for(const l of stationLines.get(from)||[]){const k=l+'|'+from;dist.set(k,0);pending.add(k);}let end;while(pending.size){let key;for(const k of pending)if(key===undefined||dist.get(k)<dist.get(key))key=k;pending.delete(key);if(key.split('|')[1]===to){end=key;break;}for(const e of graph.get(key)||[]){const n=dist.get(key)+e.cost;if(n<(dist.get(e.to)??Infinity)){dist.set(e.to,n);prev.set(e.to,{key,e});pending.add(e.to);}}}if(!end)throw Error('METRO_ROUTE_UNAVAILABLE');const edges=[];while(prev.has(end)){const p=prev.get(end);edges.unshift(p.e);end=p.key;}const segments=[];for(const e of edges){if(e.transfer)continue;let s=segments.at(-1);if(!s||s.lineId!==e.line){s={lineId:e.line,stations:[e.from]};segments.push(s);}s.stations.push(e.station);}return segments;}
function plan(request,language='zh'){const from=resolve(origins[request.origin]?.zh||request.origin),to=resolve(request.destination||'豫园'),via=request.via?resolve(request.via):null;if(!from)throw Error('METRO_ORIGIN_REQUIRED');if(!to)throw Error('METRO_DESTINATION_REQUIRED');if(request.via&&!via)throw Error('METRO_VIA_REQUIRED');if(![from,to,via].filter(Boolean).every(id=>stationLines.has(id)))throw Error('METRO_ONLY_SCOPE');const raw=via&&via!==from&&via!==to?[...path(from,via),...path(via,to)]:path(from,to);const segments=raw.map(s=>{const l=lines.get(s.lineId),a=l.stations.indexOf(s.stations[0]),b=l.stations.indexOf(s.stations[1]),end=l.loop?null:stations.get(l.stations[b>a?l.stations.length-1:0]);return{...s,line:l.name,color:l.color,direction:end?[end.zh,end.en]:[s.stations[1],stations.get(s.stations[1])?.en],bilingualNodes:s.stations.map(id=>{const s=stations.get(id);return[s.zh,s.en];})};});const a=stations.get(from),b=stations.get(to),title=a.zh+' / '+a.en+' → '+b.zh+' / '+b.en,zh=language==='zh';return{origin:from,destination:to,via,segments,title,bilingualTitle:title,line:segments[0]?.line.replace('号线','')||'',direction:segments[0]?.direction[zh?0:1]||'',bilingualNodes:[[a.zh,a.en],[b.zh,b.en]],nodes:[a.zh,b.zh],checkedAt:D.retrievedAt,source,service,notice:zh?'线路示意，非按比例地图。优先少换乘、其次少站点；不代表最快路线。未接入实时运营、末班车、票价和出口状态。':'Schematic, not to scale. Fewer transfers, then fewer stops; not a fastest-route claim. No live service, last-train, fare or exit data.',walk:to==='豫园'?(zh?'豫园站与景区入口不同：出站后按“豫园 / 城隍庙”导向步行，出口开放以现场为准。':'Yuyuan Garden station is separate from the attraction: follow Yu Garden / City God Temple signs and check the open exits.'):to==='上海火车站'?(zh?'到站后按“铁路上海站 / 火车站”标识前往对应广场及铁路进站口；地铁出口与铁路检票口不同。':'Follow signs for Shanghai Railway Station and your railway entrance; metro exits are separate from train check-in gates.'):(zh?'到站后按现场导向前往目的地；此图不包含地面步行导航。':'Follow station signs to your destination. This diagram does not include street walking navigation.')};}
function route(origin,language='zh'){return plan({origin,destination:'豫园'},language);}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function answer(request,language='zh'){const zh=language==='zh';if(!resolve(origins[request.origin]?.zh||request.origin)||!resolve(request.destination))return zh?'请补充或选择出发站和到达站，我会在这条对话里画出换乘路线。':'Choose a departure and arrival station to see the route here.';if(![resolve(request.origin),resolve(request.destination),resolve(request.via)].filter(Boolean).every(id=>stationLines.has(id)))return zh?'这次包含市域机场线专用站，不能当成普通地铁路线。当前工具仅规划地铁；请改选地铁站，或查询机场线运营方。':'This request includes a suburban airport-rail-only station, not an ordinary metro route. Choose metro stations or consult the airport rail operator.';const r=plan(request,language);if(!r.segments.length)return zh?'起点和终点是同一地铁站，无需乘车。':'The departure and arrival are the same station; no metro ride is needed.';return r.segments.map((s,i)=>zh?(i?'在':'从')+s.stations[0]+(i?'换乘':'乘坐')+s.line+'（往'+s.direction[0]+'方向），到'+s.stations.at(-1)+'下车。':(i?'Change at ':'Start at ')+stations.get(s.stations[0]).en+'; take Line '+s.line.replace('号线','')+' towards '+s.direction[1]+' to '+stations.get(s.stations.at(-1)).en+'.').join(' ')+(zh?' 路线图和途经站在下方。':' The route diagram and stops are below.');}
function diagram(r){let y=36;const parts=[];for(const [i,s]of r.segments.entries()){const a=s.bilingualNodes[0],b=s.bilingualNodes.at(-1);parts.push('<path d="M 25 '+y+' V '+(y+100)+'" stroke="'+s.color+'" stroke-width="8"/><circle cx="25" cy="'+y+'" r="9" fill="white" stroke="'+s.color+'" stroke-width="4"/><text x="50" y="'+(y+4)+'">'+esc(a[0])+' / '+esc(a[1])+'</text><text class="metro-svg-line" x="50" y="'+(y+36)+'">'+esc(s.line)+' / Line '+esc(s.line.replace('号线',''))+' · '+(s.stations.length-1)+' 站 / stops</text><text class="metro-svg-direction" x="50" y="'+(y+59)+'">往 '+esc(s.direction[0])+'</text><text class="metro-svg-direction" x="50" y="'+(y+80)+'">towards '+esc(s.direction[1])+'</text>'+(i===r.segments.length-1?'<circle cx="25" cy="'+(y+100)+'" r="9" fill="white" stroke="'+s.color+'" stroke-width="4"/><text x="50" y="'+(y+105)+'">'+esc(b[0])+' / '+esc(b[1])+'</text>':''));y+=100;}return '<div class="metro-route-title">'+esc(r.title)+'</div><svg class="metro-map" viewBox="0 0 680 '+Math.max(120,y+30)+'" role="img" aria-label="'+esc(r.title)+'">'+parts.join('')+'</svg>';}
function network(r){const selected=new Set((r?.segments||[]).map(s=>s.lineId));return '<svg class="metro-network-map" viewBox="0 0 3400 3100" role="img" aria-label="上海地铁网络示意 / Shanghai metro network">'+D.lines.map(l=>'<polyline points="'+l.stations.map(id=>stations.get(id).xy.join(',')).join(' ')+'" fill="none" stroke="'+(selected.size&&!selected.has(l.id)?'#dde2e8':l.color)+'" stroke-width="8"/>').join('')+(r?.segments||[]).map(s=>'<polyline points="'+s.stations.map(id=>stations.get(id).xy.join(',')).join(' ')+'" fill="none" stroke="'+s.color+'" stroke-width="20"/>').join('')+[...new Set((r?.segments||[]).flatMap(s=>[s.stations[0],s.stations.at(-1)]))].map(id=>{const s=stations.get(id);return '<circle cx="'+s.xy[0]+'" cy="'+s.xy[1]+'" r="18" fill="white" stroke="#152f3e" stroke-width="7"/><text x="'+(s.xy[0]+28)+'" y="'+(s.xy[1]-20)+'" font-size="42" fill="#152f3e">'+esc(s.zh)+'</text><text x="'+(s.xy[0]+28)+'" y="'+(s.xy[1]+25)+'" font-size="32">'+esc(s.en)+'</text>';}).join('')+'</svg>';}
function html(request,language='zh',turn=0){const zh=language==='zh',from=resolve(origins[request.origin]?.zh||request.origin),to=resolve(request.destination);let r=null;try{if(from&&to)r=plan({...request,origin:from,destination:to},language);}catch(_){}const list='metro-stations-'+turn;return '<section class="metro-card" data-metric-kind="metro" data-metric-item="metro-'+turn+'"><div class="offer-heading"><strong>Ⓜ '+(zh?'上海地铁路线':'Shanghai metro route')+'</strong><span class="demo-tag">'+(zh?'站点路线图':'Station route')+'</span></div>'+(r?diagram(r)+'<p>'+esc(r.walk)+'</p>':'<p>'+(zh?'请选择起点和终点；不会把火车站当成购票需求。':'Choose the endpoints to show your metro route.')+'</p>')+'<form class="metro-edit"><label>起点 / From<input name="origin" list="'+list+'" value="'+esc(from||request.origin||'')+'" required autocomplete="off"></label><label>终点 / To<input name="destination" list="'+list+'" value="'+esc(to||request.destination||'')+'" required autocomplete="off"></label><label>＋ 途经站 / Via (optional)<input name="via" list="'+list+'" value="'+esc(request.via||'')+'" placeholder="'+(zh?'添加想去的地方对应地铁站':'Add a station to visit')+'" autocomplete="off"></label><button class="outline">'+(zh?'更新路线图':'Update route')+'</button><datalist id="'+list+'">'+D.stations.map(s=>'<option value="'+esc(s.zh)+'">'+esc(s.en)+'</option>').join('')+'</datalist></form><div class="metro-origins">'+Object.entries(origins).map(([id,s])=>'<button type="button" data-metro-origin="'+id+'">'+esc(s.zh+' / '+s.en)+'</button>').join('')+'</div>'+(r?'<details class="metro-stops"><summary>'+(zh?'展开全部途经站':'Show all stops')+'</summary>'+r.segments.map(s=>'<p><strong>'+esc(s.line)+'</strong></p><ol>'+s.bilingualNodes.map(n=>'<li><button type="button" data-metro-via="'+esc(n[0])+'" title="'+(zh?'设为途经站':'Use as a via station')+'">'+esc(n.join(' / '))+'</button></li>').join('')+'</ol>').join('')+'</details><p class="muted">'+esc(r.notice)+'</p>':'')+'<details class="metro-network"><summary>'+(zh?'展开上海地铁网络与本次路线':'Shanghai network and this route')+'</summary>'+network(r)+'</details><p class="muted">'+(zh?'站点数据：高德公开网络快照':'Station data: Amap public network snapshot')+' · '+D.retrievedAt+' · '+D.stations.length+' '+(zh?'站':'stations')+'</p><div class="metro-links"><a href="'+service+'" target="_blank" rel="noopener noreferrer">官方运营信息 ↗</a><a href="'+source+'" target="_blank" rel="noopener noreferrer">官方参考图（2024）↗</a><a href="https://map.amap.com/subway/index.html?city=3100" target="_blank" rel="noopener noreferrer">高德地铁图 ↗</a><a href="skills/shanghai-metro-guide/SKILL.md" target="_blank" rel="noopener">地铁出行 Skill ↗</a></div></section>';}
return{origins,intent,resolve,hits,plan,route,answer,diagram,html,source,service,stations:D.stations,isMetroStation:id=>stationLines.has(resolve(id)),version:D.version};
});
