/* A small, explicitly schematic route guide. No live location, timetable or exit guarantee. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelMetro=factory();})(globalThis,function(){
'use strict';
const source='https://english.shanghai.gov.cn/en-Latest-WhatsNew/20240924/b625d488216241f78f743cd87a40df0c.html';
const service='https://service.shmetro.com/';
const origins={hongqiao:{zh:'虹桥火车站',en:'Hongqiao Railway Station',line:'10',direction:['基隆路方向','towards Jilong Road'],nodes:[['虹桥火车站','Hongqiao Railway Station'],['… 中间站省略','… intermediate stops'],['豫园站','Yuyuan Garden station']]},nanjing:{zh:'南京东路站',en:'East Nanjing Road',line:'10',direction:['虹桥火车站 / 航中路方向','towards Hongqiao Railway Station / Hangzhong Road'],nodes:[['南京东路站','East Nanjing Road'],['豫园站','Yuyuan Garden station']]},lujiazui:{zh:'陆家嘴站',en:'Lujiazui',line:'14',direction:['封浜方向','towards Fengbang'],nodes:[['陆家嘴站','Lujiazui'],['豫园站','Yuyuan Garden station']]}};
function intent(text,city){if(city&&city!=='Shanghai')return null;if(!/豫园|城隍庙|yuyuan|yu garden/i.test(text||''))return null;let origin=/虹桥(?:火车站|站)|hongqiao (?:railway|train)/i.test(text)?'hongqiao':/南京东路|east nanjing|nanjing east/i.test(text)?'nanjing':/陆家嘴|lujiazui/i.test(text)?'lujiazui':null;return{destination:'yuyuan',origin};}
function route(origin,language='zh'){const r=origins[origin];if(!r)throw Error('METRO_ORIGIN_REQUIRED');const zh=language==='zh';return{origin,line:r.line,direction:r.direction[zh?0:1],title:(zh?r.zh:r.en)+(zh?' → 豫园':' → Yu Garden'),nodes:r.nodes.map(n=>n[zh?0:1]),bilingualNodes:r.nodes,bilingualDirection:r.direction,bilingualTitle:r.zh+' / '+r.en+' → 豫园 / Yu Garden',walk:zh?'到达豫园地铁站后，按站内“豫园 / 城隍庙”导向出站，再步行前往景区。出口开放情况以现场为准。':'At Yuyuan Garden station, follow signs for Yu Garden / City God Temple, then walk to the attraction. Check the available exits on site.',notice:zh?'线路示意，非按比例地图；未获取实时运营、票价、定位或步行导航。':'Schematic, not to scale. No live service, fare, location or walking navigation.',source,service,checkedAt:'2026-09-25'};}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function diagram(r){const color=r.line==='10'?'#a586bd':'#659b80',nodes=r.bilingualNodes||r.nodes.map(n=>[n,n]);return '<div class="metro-route-title">'+esc(r.bilingualTitle||r.title)+'</div><svg class="metro-map" viewBox="0 0 660 170" role="img" aria-label="'+esc(r.bilingualTitle||r.title)+'"><path d="M 45 64 H 615" fill="none" stroke="'+color+'" stroke-width="9" stroke-linecap="round"/>'+nodes.map((pair,i)=>{const x=45+i*570/(nodes.length-1),anchor=i===0?'start':i===nodes.length-1?'end':'middle';return '<circle cx="'+x+'" cy="64" r="9" fill="white" stroke="'+color+'" stroke-width="4"/><text x="'+x+'" y="100" text-anchor="'+anchor+'" font-size="15" fill="#355466">'+esc(pair[0])+'</text><text x="'+x+'" y="124" text-anchor="'+anchor+'" font-size="12" fill="#355466">'+esc(pair[1])+'</text>';}).join('')+'<text x="330" y="22" text-anchor="middle" font-size="14" fill="'+color+'">'+r.line+' 号线 / Line '+r.line+' · '+esc(r.bilingualDirection?.[0]||r.direction)+'</text><text x="330" y="43" text-anchor="middle" font-size="12" fill="'+color+'">'+esc(r.bilingualDirection?.[1]||r.direction)+'</text></svg>';}

function html(request,language='zh',turn=0){const zh=language==='zh',selected=request.origin;const buttons=Object.entries(origins).map(([id,r])=>'<button data-metro-origin="'+id+'" data-metro-turn="'+turn+'" aria-pressed="'+(id===selected)+'">'+esc(r.zh+' / '+r.en)+'</button>').join('');const r=selected?route(selected,language):null;return '<section class="metro-card"><div class="offer-heading"><strong>Ⓜ '+(zh?'地铁到豫园':'Metro to Yu Garden')+'</strong><span class="demo-tag">'+(zh?'路线示意':'Route guide')+'</span></div><p>'+(zh?'从哪一站出发？请选择或直接告诉我。':'Which station are you leaving from? Choose or tell me.')+'</p><div class="metro-origins">'+buttons+'</div>'+(r?diagram(r)+'<p>'+esc(r.walk)+'</p><p class="muted">'+esc(r.notice)+'</p>':'')+'<div class="metro-links"><a href="'+service+'" target="_blank" rel="noopener noreferrer">'+(zh?'官方全网图 / 运营信息 ↗':'Official network / service ↗')+'</a><a href="'+source+'" target="_blank" rel="noopener noreferrer">'+(zh?'路线依据（2024 年版图）':'Map source (2024 edition)')+'</a><a href="skills/shanghai-metro-guide/SKILL.md" target="_blank" rel="noopener">'+(zh?'查看地铁出行 Skill':'Metro guidance skill')+'</a></div><details class="metro-network"><summary>'+(zh?'展开上海地铁全网图（2024 年版）':'View Shanghai network map (2024 edition)')+'</summary><a href="https://english.shanghai.gov.cn/cmsres/06/064cda3a1df440ddb6035fd46311a74e/35aa516725ca558fea71522489cbc876.jpg" target="_blank" rel="noopener noreferrer"><img loading="lazy" src="https://english.shanghai.gov.cn/cmsres/06/064cda3a1df440ddb6035fd46311a74e/35aa516725ca558fea71522489cbc876.jpg" alt="Shanghai Metro network, 2024 edition"></a><p>'+(zh?'历史版本供路线参考；当前线路和运营请核对上方官方入口。':'Historical map for reference. Check current routes and service at the official link above.')+'</p></details></section>';}
return{origins,intent,route,diagram,html,source,service};
});
