'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createMongoStore}=require('./ops-mongo-store');
function fake(){let row=null;const clone=x=>structuredClone(x),col={async findOne(){return clone(row);},async insertOne(x){if(row)throw Object.assign(Error(),{code:11000});row=clone(x);},async replaceOne(filter,x){if(row?.revision!==filter.revision)return{modifiedCount:0};row=clone(x);return{modifiedCount:1};}};return class {db(){return{collection:()=>col};}async close(){}};}
test('Mongo CAS retries preserve concurrent approvals and revision',async()=>{const C=fake(),env={MONGODB_URI:'mock'},a=createMongoStore(env,x=>x,C),b=createMongoStore(env,x=>x,C);await Promise.all([a.mutate(s=>s.audit.push({event:'a'})),b.mutate(s=>s.audit.push({event:'b'}))]);const row=await a.read();assert.equal(row.revision,2);assert.equal(row.audit.length,2);});
test('read-only migration refuses writes without changing source',async()=>{const a=createMongoStore({MONGODB_URI:'mock',OPS_STORE_READ_ONLY:'1'},x=>x,fake());await assert.rejects(a.mutate(s=>s.audit.push({})),/STORE_READ_ONLY/);assert.equal(await a.read(),null);});
test('Mongo backend is opt-in and does not silently fall back on missing URI',()=>{assert.throws(()=>require('./ops-store').createStore({OPS_STORE:'mongo'}),/MONGODB_URI_REQUIRED/);});
test('compressed historical corpus preserves every record across platform newlines',()=>{const fs=require('node:fs'),z=require('node:zlib');const hash=require('../tools/migrate-ops-store.cjs').hash;assert.equal(hash(JSON.parse(z.gunzipSync(fs.readFileSync('data/evaluation/v6.1-cases.json.gz')).toString('utf8'))),hash(JSON.parse(fs.readFileSync('data/evaluation/v6.1-cases.json','utf8'))));});
test('public download redirects go to existing version-pinned GitHub assets',()=>{const c=require('../vercel.json');assert.equal(c.redirects.length,3);for(const r of c.redirects)assert.match(r.destination,/^https:\/\/github.com\/cxy-peter\/visit-china-ai-agent\/releases\/download\/v6.6-public-data-20260926\//);});
