/* Primary pages opened 2026-09-25. News is dated evidence, not a policy replacement. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelNews=factory();})(globalThis,function(){
'use strict';
const records=[
 {id:'news-tenpaygo-20260924',title:'TenPayGo · 来华支付与生活服务新应用',url:'https://tenpaygo.com/',publisher:'Tencent / Weixin Pay',sourceType:'operator',city:'China',publishedAt:'2026-09-24',publicationDate:'2026-09-24',recordType:'news',topics:['TenPayGo','tenpaygo','tenpay go','Tengopay','TengoPay','tengopay','微信','Weixin Pay','WeChat Pay','入境支付','境外银行卡','Apple Pay','foreign card','payment','新支付应用'],summaryZh:'你说的 Tengopay 可能是 TenPayGo，请核对产品名称。TenPayGo 是腾讯面向来华访客的支付应用；官方页面介绍可用国际银行卡、Apple Pay 或支持的境外钱包，在微信支付商户付款，无需中国手机号或微信账号。腾讯 App Store 正文确认支持日常消费并可查看交易记录，更多本地交通与生活服务逐步推出。不要据此认定它已支持上海地铁闸机、所有境外钱包或免收所有手续费；卡种、资格、费率和城市服务请看应用当下页面。',summary:'If you said Tengopay, you may mean TenPayGo; please check the product name. Tencent’s visitor app offers payments at Weixin Pay merchants using supported international cards, Apple Pay or e-wallets, without a Chinese phone number or Weixin account. Its official App Store listing describes transaction history and gradual rollout of more local services. This does not establish Shanghai metro gate support, universal wallet eligibility or zero fees; check current in-app availability and terms.',corroboratingUrls:['https://apps.apple.com/us/app/tenpaygo/id6778755338'],publicationEvidenceUrl:'https://mp.weixin.qq.com/s/Xk95ohQHyVr4ul27yyvLvQ',publicationEvidenceStatus:'Official announcement URL identified through multiple press reports; its body was inaccessible in this verification. Product facts independently checked on official website metadata and Tencent App Store listing.',changeType:'new_service',policyOverride:false},
 {id:'news-nihao-china-shanghai-20260817',title:'Nihao China · 上海入境支付、交通与便民服务',url:'https://sww.sh.gov.cn/swdt/20260819/e184b804c7c141ae80d5d4f2c3e80d25.html',publisher:'Shanghai Municipal Commission of Commerce',sourceType:'official',city:'Shanghai',publishedAt:'2026-08-17',publicationDate:'2026-08-17',recordType:'news',topics:['Nihao China','你好中国','银联','UnionPay','入境支付','外卡','公共交通','地铁','mobile payments','tourist services'],summaryZh:'上海市商务委 2026年8月17日的报道介绍银联 Nihao China：境外游客可在应用中使用支持的外卡充值，并在上海支持的商户付款；在上海也可通过乘车码使用地铁和公交。应用提供附近 ATM、外币兑换点检索和翻译等服务。报道描述的是平台能力，不代表本站已接入其支付、地图或实时库存；开通资格、费率、优惠及乘车码当前范围以应用和运营方为准。',summary:'A Shanghai commerce authority report dated August 17, 2026 describes UnionPay’s Nihao China app: visitors can fund it with eligible foreign cards, pay at supported Shanghai merchants and use its transit code for Shanghai metro and buses. It also offers ATM/currency-exchange discovery and translation. These are provider capabilities, not integrations operated by this website; check current eligibility, fees, offers and transit coverage in the app.',corroboratingUrls:['https://www.unionpayintl.com/ZT/en/NHCAPP/','https://www.shanghai.gov.cn/nw31406/20251230/add4a4de4d5f4412b18b529f145b321a.html'],changeType:'service_update',policyOverride:false},
 {id:'news-go-beijing-20260430',title:'GO BEIJING · 入境游客一站式服务',url:'https://english.beijing.gov.cn/specials/paymentservices/news/202604/t20260430_4624215.html',publisher:'International Web Portal of Beijing',sourceType:'official',city:'Beijing',publishedAt:'2026-04-30',publicationDate:'2026-04-30',recordType:'news',topics:['GO BEIJING','北京','旅行钱包','Travel Wallet','入境支付','public services','hotel booking','ride hailing','多语种'],summaryZh:'北京市英文门户 2026年4月30日报道 GO BEIJING 一站式服务，覆盖打车、订票、酒店和公共服务，并提供多语种入口及 Travel Wallet。报道说钱包可通过跨境汇款入金，无需绑卡。适用国家、费率和办理要求可能变化，使用前应核对平台当前条款；这条北京服务资料不能证明上海同样可用。',summary:'The Beijing government portal’s April 30, 2026 report introduces GO BEIJING for ride-hailing, tickets, hotels and public services, with multilingual access and a Travel Wallet funded through cross-border remittances without card linking. Confirm current country eligibility, fees and application requirements with the platform. This Beijing service record does not establish equivalent availability in Shanghai.',changeType:'new_service',policyOverride:false},
 {id:'news-shanghai-transit-code-guide',title:'上海公共交通乘车码 · 开通与异常行程处理',url:'https://jtw.sh.gov.cn/zsk/20240424/f502895cea0f46bea5975842cfbfac16.html',publisher:'Shanghai Municipal Transportation Commission',sourceType:'official',city:'Shanghai',publishedAt:'2024-04-24',publicationDate:'2024-04-24',recordType:'service',topics:['乘车码','上海公共交通','地铁票','支付宝','微信','metro ticket','transit code','行程补登'],summaryZh:'上海市交通委的乘车码问答说明，上海公共交通乘车码可用于公交、地铁、轮渡，采用先乘车后付费。可从支付宝出行或微信乘车码等入口按提示开通，通常需授权相应扣费方式。进出站记录缺失时，可到支付宝对应乘车码的行程补登入口处理。页面发布时间为2024年4月24日；如应用入口已改变，请以当前平台页面或车站服务人员为准。',summary:'Shanghai’s transportation authority explains that the local transit code supports buses, metro and ferries with payment after travel. Activate it through supported Alipay or WeChat transit entry points and authorize the relevant payment method. Missing entry/exit records can be addressed through Alipay’s trip-completion flow. The guide was published on April 24, 2024; current app screens and station staff take precedence if the interface has changed.',changeType:'service_guide',policyOverride:false}
].map(r=>({...r,kind:'reviewed_reference',reviewedAt:'2026-09-25',verifiedAt:'2026-09-25',reviewDays:3,active:true,verificationMethod:'primary-page-content-opened',newsDoesNotSupersedePolicy:true}));
// These feed URLs were read from the respective publisher list-page code.
// Scheduler consumers must emit candidates, not publish a title as a fact.
const discoveryFeeds=[
 {id:'govcn-public-news',url:'https://www.gov.cn/lianbo/YAOWENLIEBIAO.json',discoveredOn:'https://www.gov.cn/lianbo/',format:'govcn-json',city:'China',fields:{title:'TITLE',url:'URL',publishedAt:'DOCRELPUBTIME'},topics:['交通','出行','旅游','支付','便民','入境','公共服务','外卡','地铁','机场','退税','酒店','餐饮','充电','寄存','高铁','铁路'],intervalDays:3,outputStatus:'candidate',requiresBodyFetch:true},
 {id:'govcn-policy-news',url:'https://www.gov.cn/zhengce/zuixin/ZUIXINZHENGCE.json',discoveredOn:'https://www.gov.cn/zhengce/zuixin/',format:'govcn-json',city:'China',fields:{title:'TITLE',url:'URL',publishedAt:'DOCRELPUBTIME'},topics:['交通','出行','旅游','支付','便民','入境','公共服务','外卡','地铁','机场','退税','酒店','餐饮','充电','寄存','高铁','铁路'],intervalDays:3,outputStatus:'candidate',requiresBodyFetch:true}
];
return{records,discoveryFeeds};
});
