'use strict';
const crypto=require('node:crypto'),E=require('./engine'),G=require('./governance'),L=require('./library'),seeds=require('./source-seeds');
const copy=x=>JSON.parse(JSON.stringify(x)),stamp=()=>new Date().toISOString();
function initial(){return{schema:1,revision:0,sources:[...L.records.filter(r=>r.summary||r.summaryZh),...seeds].map(copy),proposals:[],checks:[],events:[],runs:[],audit:[],governance:{...G.newStore(),active:{...E.BASE,needsFirst:true}},refresh:{lastStartedAt:null,lastCompletedAt:null,nextDueAt:null,leaseUntil:0},applied:[]};}
function log(s,type,actor,detail={}){s.audit.push({at:stamp(),type,actor,...detail});s.audit=s.audit.slice(-500);}
function validateSource(value){const v=value||{},text=(k,max,required=false)=>{if(typeof v[k]!=='string'||v[k].length>max||(required&&!v[k].trim()))throw Error('SOURCE_FIELD_'+k.toUpperCase());return E.clean(v[k],max);};
 const u=new URL(text('url',700,true));if(u.protocol!=='https:'||u.username||u.password||u.port||!/[a-z]/i.test(u.hostname)||/localhost|\.local$|^127\.|^10\.|^192\.168\./i.test(u.hostname))throw Error('SOURCE_URL');
 const record={title:text('title',160,true),url:u.href,publisher:text('publisher',120,true),city:text('city',60,true),summaryZh:text('summaryZh',2200,true),summary:text('summary',2200),sourceType:['official','operator','note'].includes(v.sourceType)?v.sourceType:'note',topics:Array.isArray(v.topics)?v.topics.map(t=>E.clean(t,30)).filter(Boolean).slice(0,12):[],published:typeof v.published==='string'?v.published.slice(0,10):null};
 return record;
}
function propose(s,actor,input){if(s.proposals.length>=200)throw Error('SOURCE_QUEUE_FULL');const record=validateSource(input.record),sourceId=input.sourceId||'community-'+crypto.randomUUID(),old=s.sources.find(r=>r.id===sourceId);const p={id:crypto.randomUUID(),sourceId,record,author:actor,baseHash:old?G.digest(old):null,revision:1,status:'review',votes:[],createdAt:stamp()};p.hash=G.digest({sourceId,record,revision:p.revision,baseHash:p.baseHash});s.proposals.push(p);log(s,'source_submitted',actor,{id:p.id});return p;}
function edit(s,id,actor,input,admin){const p=s.proposals.find(p=>p.id===id);if(!p)throw Error('SOURCE_NOT_FOUND');if(p.status==='published')throw Error('IMMUTABLE_RELEASE');if(p.author!==actor&&!admin)throw Error('AUTHOR_REQUIRED');p.record=validateSource(input);if(p.contentChange)p.contentChange.requiresEdit=false;p.revision++;p.votes=[];p.status='review';p.hash=G.digest({sourceId:p.sourceId,record:p.record,revision:p.revision,baseHash:p.baseHash});log(s,'source_edited_votes_reset',actor,{id,hash:p.hash});return p;}
function vote(s,id,actor,decision,hash,reviewers){const p=s.proposals.find(p=>p.id===id);if(!p)throw Error('SOURCE_NOT_FOUND');if(!reviewers.has(actor))throw Error('REVIEWER_REQUIRED');if(actor===p.author)throw Error('AUTHOR_CANNOT_APPROVE');if(p.hash!==hash)throw Error('STALE_HASH');if(!['review','blocked'].includes(p.status))throw Error('NOT_IN_REVIEW');if(decision==='approve'&&p.contentChange?.requiresEdit)throw Error('SOURCE_EDIT_REQUIRED');if(!['approve','reject','withdraw'].includes(decision))throw Error('VOTE_VALUE');const old=s.sources.find(r=>r.id===p.sourceId);if((old?G.digest(old):null)!==p.baseHash)throw Error('STALE_BASE');
 p.votes=p.votes.filter(v=>v.actor!==actor);if(decision!=='withdraw')p.votes.push({actor,decision,hash,at:stamp()});p.status=p.votes.some(v=>v.decision==='reject')?'blocked':'review';
 if(p.status==='review'&&new Set(p.votes.filter(v=>v.decision==='approve'&&v.hash===hash&&reviewers.has(v.actor)).map(v=>v.actor)).size>=5){p.previous=old?copy(old):null;const record={...p.record,id:p.sourceId,active:true,reviewedAt:stamp().slice(0,10),reviewDays:30,kind:p.record.sourceType==='note'?'community_note':'reviewed_reference',publicationHash:p.hash};s.sources=s.sources.filter(r=>r.id!==p.sourceId);s.sources.push(record);p.status='published';p.publishedAt=stamp();}
 log(s,'source_vote',actor,{id,decision,hash,status:p.status});return p;
}
function rollback(s,id,actor){const p=s.proposals.find(p=>p.id===id);if(!p||p.status!=='published'||s.sources.find(r=>r.id===p.sourceId)?.publicationHash!==p.hash)throw Error('ROLLBACK_NOT_CURRENT');s.sources=s.sources.filter(r=>r.id!==p.sourceId);if(p.previous)s.sources.push(p.previous);p.status='rolled_back';log(s,'source_rollback',actor,{id});}
const eventTypes=new Set(['chat_started','user_message','source_used','offer_view','product_click','calculator_used','source_open','feedback','answer_shown']);
function ingest(s,visitor,events,now=Date.now()){if(!Array.isArray(events)||events.length>30)throw Error('EVENT_BATCH');let added=0;const seen=new Set(s.events.map(e=>e.id));for(const e of events){if(!eventTypes.has(e.type)||!/^[-\w]{8,90}$/.test(e.id)||!/^[-\w]{8,90}$/.test(e.chat)||!Number.isFinite(e.at)||Math.abs(e.at-now)>86400000)throw Error('EVENT_SCHEMA');if(seen.has(e.id))continue;const row={id:e.id,session:visitor+':'+e.chat,at:e.at,receivedAt:now,type:e.type,kind:['rail','flight','hotel','restaurant','taxi','metro','other'].includes(e.kind)?e.kind:'other',item:String(e.item||'').replace(/[^\w.-]/g,'').slice(0,100)};s.events.push(row);seen.add(row.id);added++;}s.events=s.events.filter(e=>e.at>now-30*86400000).slice(-8000);return added;}
function demoEvents(now=Date.now()){const rows=[];for(let i=0;i<120;i++){const session='synthetic-'+i,at=now-(i%7)*86400000-3600000;const add=(type,offset,kind='rail',item='rail-example')=>rows.push({id:session+type,session,at:at+offset,type,kind,item});add('chat_started',0);if(i<92)add('user_message',2000);if(i<76)add('source_used',3000);if(i<64)add('offer_view',4000);if(i<29)add('product_click',6000);if(i%5===0&&i<92)add('calculator_used',8000,'taxi','taxi-estimate');}return rows;}
function metrics(events,now=Date.now(),days=7,kind='rail'){const filtered=events.filter(e=>e.at>=now-days*86400000&&e.at<=now),sessions=new Map();for(const e of filtered){if(!sessions.has(e.session))sessions.set(e.session,[]);sessions.get(e.session).push(e);}const funnel=[0,0,0,0],products={};let sourceSessions=0,calculators=0;for(const rows of sessions.values()){rows.sort((a,b)=>a.at-b.at);let start,asked,seen;const views=new Map(),clicked=new Set();for(const e of rows){if(e.type==='chat_started'&&start===undefined)start=e.at;if(e.type==='user_message'&&start!==undefined&&e.at-start<=1800000&&asked===undefined)asked=e.at;if(e.type==='offer_view'){views.set(e.kind+':'+e.item,e.at);if(e.kind===kind&&asked!==undefined&&e.at-start<=1800000&&seen===undefined)seen=e.at;}if(e.type==='product_click'&&views.has(e.kind+':'+e.item)&&e.at-views.get(e.kind+':'+e.item)<=1800000)clicked.add(e.kind+':'+e.item);}
  if(start!==undefined)funnel[0]++;if(asked!==undefined)funnel[1]++;if(seen!==undefined)funnel[2]++;if(seen!==undefined&&rows.some(e=>e.type==='product_click'&&e.kind===kind&&e.at>=seen&&e.at-start<=1800000&&clicked.has(e.kind+':'+e.item)))funnel[3]++;
  if(rows.some(e=>e.type==='source_used'))sourceSessions++;if(rows.some(e=>e.type==='calculator_used'))calculators++;
  for(const key of views.keys()){const k=key.split(':')[0];products[k]||={views:0,clicks:0};products[k].views++;if(clicked.has(key))products[k].clicks++;}
 }
 const trend=Array.from({length:days},(_,i)=>{const date=new Date(now-(days-1-i)*86400000).toISOString().slice(0,10);return{date,chats:new Set(filtered.filter(e=>e.type==='chat_started'&&new Date(e.at).toISOString().slice(0,10)===date).map(e=>e.session)).size};});
 return{sessions:sessions.size,funnel,sourceSessions,calculators,products,trend,events:filtered.length,days,kind,definitions:'Session = anonymous conversation, not a person. Ordered 30-minute funnel; product CTR uses matching viewed-card/session pairs. Platform click is not a purchase. Client events can be incomplete or forged. Retained: 30 days / latest 8,000 events.'};
}
function resolution(s,visitor,input,now=Date.now()){
 const {chat,answerId,outcome}=input;if(!/^[-\w]{8,90}$/.test(chat)||!/^[-\w]{8,90}$/.test(answerId)||!['solved','unsolved'].includes(outcome))throw Error('RESOLUTION_SCHEMA');
 const kinds=['rail','flight','hotel','restaurant','taxi','metro','other'];if(!kinds.includes(input.kind)||!['wrong_intent','wrong_route','missing_detail','other',null,undefined].includes(input.reason))throw Error('RESOLUTION_SCHEMA');
 const M=require('./metro'),route=input.route?{origin:M.resolve(input.route.origin),destination:M.resolve(input.route.destination),via:M.resolve(input.route.via)}:null;
 const key=visitor+':'+chat+':'+answerId;s.resolutions=(s.resolutions||[]).filter(r=>r.at>=now-30*86400000);const old=s.resolutions.find(r=>r.key===key);
 const fields={key,session:visitor+':'+chat,answerId,outcome,reason:outcome==='unsolved'?input.reason||'other':null,kind:input.kind,provider:input.provider==='deepseek'?'deepseek':'local',route,at:now};
 if(old){const changed=old.outcome!==outcome||old.reason!==fields.reason;Object.assign(old,fields);if(changed){old.status=outcome==='solved'?'resolved':'open';old.handledAt=null;}}else{s.resolutions.push({...fields,id:crypto.randomUUID(),status:outcome==='solved'?'resolved':'open'});}s.resolutions=s.resolutions.slice(-2000);return{saved:true};
}
function quality(s,now=Date.now(),days=7,kind='all'){
 const rows=(s.resolutions||[]).filter(r=>r.at>=now-days*86400000&&r.at<=now&&(kind==='all'||r.kind===kind));const shown=new Set(s.events.filter(e=>e.type==='answer_shown'&&e.at>=now-days*86400000&&(kind==='all'||e.kind===kind)).map(e=>e.session+':'+e.item));const rated=rows.filter(r=>shown.has(r.key));const solved=rows.filter(r=>r.outcome==='solved').length;
 return{rated:rows.length,solved,unsolved:rows.length-solved,rate:rows.length?solved/rows.length:null,shown:shown.size,coverage:shown.size?rated.length/shown.size:null,reasons:rows.filter(r=>r.outcome==='unsolved').reduce((a,r)=>{a[r.reason]=(a[r.reason]||0)+1;return a;},{}),rows:rows.slice().sort((a,b)=>b.at-a.at).slice(0,100),scope:'Latest response per anonymous visitor/conversation/answer. Solved rate = solved / rated, not all answers. No response is not a failure. 30 days, latest 2000 ratings.'};
}
function resolveReview(s,id,actor,status){const r=(s.resolutions||[]).find(r=>r.id===id);if(!r||!['open','reviewed'].includes(status))throw Error('RESOLUTION_REVIEW');r.status=status;r.handledAt=stamp();log(s,'resolution_review',actor,{id,status});return{saved:true};}
module.exports={initial,log,validateSource,propose,edit,vote,rollback,ingest,metrics,demoEvents,resolution,quality,resolveReview};
