/* Business measurement definitions; missing instrumentation is never displayed as zero. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.OpsMetrics=factory();})(globalThis,function(){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finite=n=>typeof n==='number'&&Number.isFinite(n),pct=n=>finite(n)?(n*100).toFixed(1)+'%':'—';
function rows(data){const q=data.quality||{},m=data.metrics||{},i=data.insights||{},b=data.caseBoard||{},f=m.funnel||[],find=part=>(i.metrics||[]).find(r=>r.name.includes(part));
 const ratio=(key,label,n,d,formula,events,meaning,window='当前筛选范围',target=null)=>({key,label,value:finite(n)&&finite(d)&&d>0?n/d:null,n:finite(n)?n:null,d:finite(d)?d:null,unit:'percent',formula,events,meaning,window,target,status:!finite(n)||!finite(d)?'未接入':d===0?'暂无样本':d<30?'样本不足':'可观察'});
 const missing=(key,label,formula,events,meaning)=>({key,label,value:null,n:null,d:null,unit:'percent',formula,events,meaning,window:'待接入',target:null,status:'未接入'});
 const measured=(key,label,metric,events,meaning)=>ratio(key,label,metric?.n,metric?.d,'分子 / 分母，按同一去重粒度统计',events,meaning,'近 '+(i.days||7)+' 天',metric?.target??null);
 const out=[
  ratio('resolution','用户确认解决率',q.solved,q.rated,'最新评价为“已解决”的回答 / 有评价的回答','answer_shown + resolution，visitor/chat/answerId/outcome','无反馈不算失败；不是订单或完整旅行任务完成率。','近 '+(m.days||7)+' 天',.4),
  {key:'feedback_coverage',label:'解决反馈覆盖率',value:finite(q.coverage)?q.coverage:null,n:finite(q.coverage)&&finite(q.shown)?Math.round(q.coverage*q.shown):null,d:finite(q.shown)?q.shown:null,unit:'percent',formula:'能匹配展示事件的已评价回答 / 已展示回答',events:'answer_shown + resolution，匹配 session/answerId',meaning:'区分没收到评价与没有解决，防止选择偏差被隐藏。',window:'近 '+(m.days||7)+' 天',target:null,status:!finite(q.shown)?'未接入':q.shown<1?'暂无样本':q.shown<30?'样本不足':'可观察'},
  measured('csat','回答满意度（CSAT）',find('满意'),'csat_up/csat_down，session/answerId/at；每个回答保留最新评价','点赞比例与“是否解决”分开，不用工单关闭代替满意。'),
  measured('intent_accuracy','人工标注意图准确率',find('意图准确'),'executionId + intentCorrect + reviewer + reviewedAt','只计算人工核对过原问题的执行，模型自评不作真值。'),
  measured('retrieval_nonempty','检索有结果率',find('检索有结果'),'executionId + retrieval.hits + dataset + at','有片段不代表片段正确；需要配合召回标注和回答验收。'),
  missing('retrieval_relevance','检索正确命中率','召回正确资料的标注问题 / 已标注检索问题','queryId + expectedSourceIds + retrievedSourceIds + judge','需要独立正确资料标签；20,000 条离线回归不能充当线上命中率。'),
  measured('suggestion_ctr','猜你想问点击率',find('猜你想问'),'suggestion_view/click，session/item/at；至少50%可见，点击需在曝光后30分钟内','按会话＋建议卡片去重，不能拿点击总数除页面访问总数。'),
  ratio('provider_funnel','推荐到平台入口转化',f[3],f[2],'按序看到推荐且点击平台的会话 / 按序看到推荐的会话','chat_started → user_message → offer_view → product_click，session/kind/item/at','同一会话、30分钟窗口；只到平台外跳，不代表购票或成交。','近 '+(m.days||7)+' 天'),
  {key:'answer_p95',label:'完整回答耗时 P95',value:finite(i.p95)?i.p95:null,unit:'ms',n:finite(i.runs)?i.runs:null,d:null,formula:'已记录服务端完整回答耗时的95分位数',events:'executionId + stages.ms + totalMs + dataset',meaning:'不含所有网络等待；不是首字延迟，3秒是待验证目标。',window:'近 '+(i.days||7)+' 天',target:null,status:!finite(i.runs)?'未接入':!finite(i.p95)?'暂无样本':i.runs<30?'样本不足':'可观察'},
  data.failureMetrics?ratio('request_failure','已留存执行失败率',data.failureMetrics.total,finite(data.failureMetrics.total)&&finite(i.runs)?data.failureMetrics.total+i.runs:null,'已留存失败 /（已留存失败＋已记录成功执行）','服务端已授权请求 failure + executionId/errorCode/stage/dataset','仅留存窗口样本，失败与成功各有保留上限；不代表全站请求失败率或访问码登录失败率。','近 '+(i.days||7)+' 天'):missing('request_failure','服务请求失败率','失败请求 / 所有已开始请求','request_started/request_failed/request_completed + requestId/errorCode/stage','当前执行记录以已返回回答为主；分母不全时不能显示0%失败。'),
  missing('escalation','转人工率','实际进入人工服务的会话 / 服务会话','handoff_started/accepted + chatId/queueId/at','提交反馈工单不等于已转入人工会话。'),
  missing('dropoff','会话中途退出率','符合退出定义且未完成的会话 / 合格会话','session_started/heartbeat/ended + reason + outcome','需要先定义超时、主动结束和窗口；缺少结尾事件不能断言流失。'),
  missing('sentiment','情绪识别准确率','情绪预测与独立标签一致 / 已标注样本','messageId + sentimentPrediction + humanSentiment + reviewer','问题分类标签不等于情绪标签，尚未接入单独情绪识别。'),
  ratio('case_context','排查记录上下文附带率',b.contextAttached,b.total,'附带用户同意分享上下文的工单 / 反馈工单','case-submit + shareContext + redactedContextCount','用户可不分享原对话；此指标衡量定位材料完整度。','近30天／最近200单'),
  ratio('case_replay','问题回放覆盖率',b.replayed,b.total,'至少有一次回放的工单 / 反馈工单','case-replay + caseId + skillVersion + answer + sourceIds','回放有输出不自动等于修复有效，需要人工核对。','近30天／最近200单'),
  ratio('case_closure','排查工单关闭率',b.closed,b.total,'已关闭工单 / 反馈工单','case-update + caseId/status/version/note','关闭需处理记录与回放；不改写原始用户“未解决”评价。','近30天／最近200单'),
  {key:'case_closure_time',label:'工单平均处理时长',value:finite(b.meanClosureHours)?b.meanClosureHours:null,n:finite(b.closed)?b.closed:null,d:null,unit:'hours',formula:'已关闭工单的（关闭时间−创建时间）平均值',events:'caseId + createdAt + updatedAt + closed status',meaning:'目前用最后更新时间作为关闭时间；不表示用户等待人工响应时长。',window:'近30天／最近200单',target:null,status:!finite(b.closed)?'未接入':b.closed===0?'暂无样本':b.closed<30?'样本不足':'可观察'},
  missing('paid_order','购票、订单、GMV / ROI','订单需真实支付回执；ROI还需要可归因成本','provider_callback/orderId/paidAt/amount/currency/refund + attributableCost','未接供应商订单回传。不把外跳点击、示例价格或模拟数据当成交。')
 ];
 for(const [kind,p] of Object.entries(m.products||{}))out.push(ratio('product_'+kind,kind+' 推荐卡点击率',p.clicks,p.views,'该类卡片发生匹配点击的会话卡片 / 该类已曝光会话卡片','offer_view/product_click + session/kind/item/at','至少50%可见，30分钟内匹配；点击率不是购买率。','近 '+(m.days||7)+' 天'));
 return out;
}
function render(data){const items=rows(data),known=items.filter(r=>r.status!=='未接入'),window=data.metrics?.days||7;return (data.dataset==='synthetic'?'<p class="ops-warning">模拟演示数据：仅用于展示计算，不能作为真实经营成绩。真实质量、反馈和执行指标不会填入模拟值。</p>':'')+'<section class="ops-section-intro"><span class="eyebrow">METRICS / 指标、口径、回传数据</span><h3>运营大表：先看有没有证据，再看数字</h3><p>每一项都保留分母、时间范围和采集事件。近 '+esc(window)+' 天行为数据与近30天排查工单分别标注；未接入和暂无样本分开显示。</p></section><div class="ops-kpis">'+[['已接入指标',known.length],['待补采集',items.length-known.length],['问题解决反馈',data.quality?.rated??'—'],['排查工单',data.caseBoard?.total??'—']].map(([label,value])=>'<article><small>'+label+'</small><strong>'+esc(value)+'</strong></article>').join('')+'</div><section class="ops-panel"><div class="ops-table-wrap"><table><thead><tr><th>指标</th><th>当前值 / 样本</th><th>状态 / 时间范围</th><th>计算口径</th><th>需要回传的数据</th><th>解读边界</th></tr></thead><tbody>'+items.map(r=>{const value=r.status==='未接入'?'未接入':r.unit==='percent'?pct(r.value):finite(r.value)?r.unit==='ms'?(r.value/1000).toFixed(2)+' 秒':r.value.toFixed(2)+' 小时':'—';return '<tr><td><strong>'+esc(r.label)+'</strong>'+(finite(r.target)?'<small>参考目标 '+pct(r.target)+'</small>':'')+'</td><td>'+esc(value)+'<small>'+(finite(r.n)?esc(r.n)+(finite(r.d)?' / '+esc(r.d):' 个记录'):'没有可用样本')+'</small></td><td><span class="ops-badge">'+esc(r.status)+'</span><small>'+esc(r.window)+'</small></td><td>'+esc(r.formula)+'</td><td>'+esc(r.events)+'</td><td>'+esc(r.meaning)+'</td></tr>';}).join('')+'</tbody></table></div><p class="muted">参考目标来自产品验收设想，不是已经达到的成绩。少于30个样本先标“样本不足”，不做显著性或因果结论。匿名会话不是独立用户。</p></section><section class="ops-panel"><h3>已记录失败 · 按原因定位</h3><p class="muted">'+esc(data.failureMetrics?.scope||'尚未接入服务端失败记录。')+'</p><ul>'+(data.failureMetrics?.byCode||[]).map(r=>'<li>'+esc(r.code)+' · '+esc(r.count)+' 次</li>').join('')+'</ul></section><section class="ops-panel"><h3>问题类型分布 → 对应的改进动作</h3><div class="ops-table-wrap"><table><thead><tr><th>问题类型</th><th>工单数</th><th>下一步</th></tr></thead><tbody>'+(data.caseBoard?.categories||[]).map(r=>'<tr><td>'+esc(r.label)+'</td><td>'+esc(r.count)+'</td><td>'+esc({intent_error:'核对原问题与被识别意图，回放否定和多轮纠正。',fact_error:'核对来源正文、地址、电话和数值；补资料再回放。',stale_info:'检查发布日期与适用范围，更新资料并保留旧版本。',wrong_route:'核对起终点、换乘与出行方式。',missing_detail:'定位未答到的字段，补引用或定向追问。',process_issue:'检查重复追问、中断、确认和下一步状态。',language_issue:'核对输出语言设置与资料语言干扰。',connection_issue:'检查体验码状态、额度和失败环节。',other:'先还原上下文，再人工确认分类。'}[r.key]||'人工核对问题说明。')+'</td></tr>').join('')+'</tbody></table></div></section>';}
return{rows,render,metrics:render};
});
