/* The UI never supplies a reviewer identity for a vote: the server owns identity. */
window.TravelOps=(function(){let ctx,loop;const $=id=>document.getElementById(id);const html=s=>ctx.esc(s);function error(e){ctx.toast(e.message);}
async function open(c){ctx=c;$('ops-dialog').showModal();if(!ctx.server){$('ops-body').innerHTML='<div class="banner">当前是浏览器体验，不能冒充真实五人审核。请运行 Node 后端，并为五名审核者分别配置账号。公共预览不写入生产工作流。</div><p><code>npm start</code> → <code>http://127.0.0.1:8787</code></p><p><code>node v5/provision.js reviewer1 reviewer2 reviewer3 reviewer4 reviewer5</code></p>';return;}await refresh();}
async function refresh(){try{const s=await ctx.api('status');ctx.onActor(s.actor,s.model);if(!s.actor){login(s);return;}loop=await ctx.api('loop');const metrics=await ctx.api('metrics');render(s,metrics);}catch(e){$('ops-body').innerHTML='<p class="error">'+html(e.message)+'</p>';}}
function login(s){if(s.auth?.mode==='oidc'){$('ops-body').innerHTML='<p>使用组织账号登录；审核权限按组织身份名单分配。</p><a href="/api/v5/auth/start">组织账号登录</a>';return;}$('ops-body').innerHTML='<p>本机登录方式由服务端确认；默认演示密码会填入下方输入框，自定义密码不会被覆盖。审核员使用各自账号。</p><form id="ops-login-form"><label>用户名<input id="ops-user" autocomplete="username" value="admin"></label><label>密码<input id="ops-password" type="password" autocomplete="current-password" placeholder="输入实际密码"></label><button class="primary" id="ops-login">登录</button><p id="ops-login-error" class="error"></p></form>';$('ops-login-form').onsubmit=async e=>{e.preventDefault();try{await ctx.api('login',{username:$('ops-user').value,password:$('ops-password').value});$('ops-password').value='';await refresh();}catch(err){$('ops-login-error').textContent=err.message;}};}
function render(s,m){$('ops-body').innerHTML='<div class="ops-row"><span class="pill" style="color:#376077">'+html(s.actor)+'</span><span>当前工作流 <b>'+html(loop.active.version)+'</b></span><button id="ops-logout" class="light">切换账号 / 退出</button></div><div class="banner">五个不同的已配置审核账号批准同一版本、回归测试通过且无人否决后，自动纳入新通话。作者不能自批。账号去重不等于已证明五位自然人；组织登录可通过 OIDC 配置。现有通话保持原版本。</div><div class="metrics"><div class="metric"><strong>'+m.feedback+'</strong><span>反馈记录 · 本机</span></div><div class="metric"><strong>'+loop.eligibleReviewers.length+'</strong><span>已配置审核账号</span></div><div class="metric"><strong>'+m.published+'</strong><span>发布记录 · 非效果提升</span></div></div><details><summary>模型设置与真实返回的 Token 用量</summary><p class="muted">'+html(JSON.stringify(m.model))+'</p>'+(s.admin?'<label>DeepSeek Key（留空不修改）<input id="ops-key" type="password" autocomplete="off"></label><div class="ops-row"><select id="ops-model"><option>deepseek-flash</option><option>deepseek-v4-pro</option></select><button id="ops-save-key" class="light">保存到服务进程</button><button id="ops-clear-key" class="light">清除 Key</button></div>':'<p>仅管理员可修改模型凭据。</p>')+'</details><hr><h3>反馈 → 候选 → 回归 → 五人同意 → 发布</h3><div class="ops-row"><select id="ops-category"><option value="too_long">播报太长</option><option value="repeated_question">重复追问</option><option value="irrelevant_extension">推荐不相关</option><option value="missed_requirement">遗漏需求</option></select><label><input id="ops-ai" type="checkbox">允许模型处理聚合反馈</label><button id="ops-propose" class="primary">生成待审核候选</button></div><p class="muted">无 Key 时明确使用默认模板。AI 只能提议受限配置，不可改写政策、执行代码、增加任意工具或发布自己。</p><div id="candidate-list">'+loop.candidates.slice().reverse().map(row=>candidate(row,s.actor,s.admin)).join('')+'</div><details><summary>审计日志与指标口径</summary><pre class="audit">'+html(JSON.stringify({counts:m.counts,scope:m.scope,audit:loop.audit},null,2))+'</pre></details>';
$('ops-logout').onclick=async()=>{await ctx.api('logout',{});refresh();};$('ops-propose').onclick=async()=>{const b=$('ops-propose');b.disabled=true;try{await ctx.api('candidate',{category:$('ops-category').value,modelConsent:$('ops-ai').checked});await refresh();}catch(e){error(e);b.disabled=false;}};
if(s.admin){$('ops-save-key').onclick=async()=>{try{const key=$('ops-key').value.trim(),payload={model:$('ops-model').value};if(key)payload.key=key;await ctx.api('config',payload);$('ops-key').value='';ctx.toast('已配置；未自动调用付费模型。');refresh();}catch(e){error(e);}};$('ops-clear-key').onclick=async()=>{await ctx.api('config',{clear:true});refresh();};}
$('candidate-list').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;const row=loop.candidates.find(x=>x.id===b.dataset.id);b.disabled=true;try{const a=b.dataset.action;if(a==='evaluate')await ctx.api('evaluate',{id:row.id});else if(['approve','reject','withdraw'].includes(a))await ctx.api('vote',{id:row.id,decision:a,hash:row.hash});else if(a==='rollback'){if(!confirm('回滚当前已发布配置？仅影响此后开始的通话。'))return;await ctx.api('rollback',{id:row.id});}else if(a==='edit'){const area=document.getElementById('edit-'+row.id);await ctx.api('edit',{id:row.id,config:JSON.parse(area.value)});}await refresh();}catch(err){error(err);b.disabled=false;}};
}
function candidate(r,actor,admin){const approvals=r.votes.filter(x=>x.decision==='approve'&&x.hash===r.hash),votes=r.votes.map(v=>'<span class="vote">'+html(v.reviewer)+' · '+html(v.decision)+'</span>').join('');const review=['review','blocked'].includes(r.status),canVote=review&&loop.eligibleReviewers.includes(actor)&&actor!==r.author;const btn=(action,title,disabled=false,cls='')=>'<button class="'+cls+'" data-action="'+action+'" data-id="'+r.id+'" '+(disabled?'disabled':'')+'>'+title+'</button>';
return'<article class="candidate"><header><h3>'+html(r.mode)+' · '+html(r.explanation)+'</h3><span class="status">'+html(r.status)+'</span></header><p class="muted">作者 '+html(r.author)+' · rev '+r.revision+' · 基线 '+html(r.baseVersion)+' · '+approvals.length+'/5</p><p class="muted">版本哈希 '+html(r.hash)+'</p><details><summary>查看配置差异与可编辑内容</summary><pre>当前\n'+html(JSON.stringify(loop.active,null,2))+'</pre><textarea id="edit-'+r.id+'" rows="8">'+html(JSON.stringify(r.config,null,2))+'</textarea>'+btn('edit','保存修改：清空投票和评测',!['draft','review','blocked','failed'].includes(r.status)||!(admin||actor===r.author))+'</details><p class="muted">'+(r.evaluation?html((r.evaluation.passed?'通过':'未通过')+' · '+r.evaluation.checks.length+'条自编回归检查 · 非模型效果评估'):'尚未运行回归，不可批准')+'</p><details><summary>检查明细</summary><pre class="audit">'+html(JSON.stringify(r.evaluation?.checks||[],null,2))+'</pre></details><div>'+votes+'</div><div class="buttons">'+btn('evaluate','运行回归／回放',['published','rolled_back'].includes(r.status))+btn('approve','同意此版本',!canVote,'primary')+btn('reject','否决此版本',!canVote)+btn('withdraw','撤回我的票',!canVote)+btn('rollback','回滚',!admin||r.status!=='published'||loop.active.version!==r.publishedVersion)+'</div></article>';
}
return{open};})();
