'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),C=require('./core');
function point(a){if(!Array.isArray(a)||a.length!==2||!a.every(Number.isFinite)||a[0]<-180||a[0]>180||a[1]<-90||a[1]>90)throw Error('INVALID_COORDINATES');return a;}
function maps(env={},fetcher=fetch){let key=env.AMAP_WEB_KEY||'',calls=0;const status=()=>({configured:!!key,calls,inventory:false});function configure(k){if(typeof k!=='string'||(k&&!/^[\w-]{8,150}$/.test(k)))throw Error('INVALID_MAP_KEY');key=k;return status();}
async function get(p,params){if(!key)throw Error('AMAP_NOT_CONFIGURED');const u=new URL('https://restapi.amap.com/v3/'+p);for(const[k,v]of Object.entries({...params,key,output:'JSON'}))u.searchParams.set(k,String(v));calls++;const r=await fetcher(u,{redirect:'error',signal:AbortSignal.timeout(7000)});if(!r.ok)throw Error('MAP_HTTP_'+r.status);const raw=await r.text();if(raw.length>1000000)throw Error('MAP_RESPONSE_SIZE');const j=JSON.parse(raw);if(j.status!=='1')throw Error('MAP_PROVIDER_'+String(j.infocode||'ERROR').slice(0,10));return j;}
async function nearby(b){if(b.consent!==true)throw Error('LOCATION_CONSENT_REQUIRED');const cats={luggage:'行李寄存',power:'共享充电宝',cash:'外币兑换',hotel:'酒店',explore:'景点'};if(!cats[b.category])throw Error('INVALID_SERVICE');let center;
if(b.coords){center=point(b.coords);if(b.system!=='GCJ02'){const c=await get('assistant/coordinate/convert',{locations:center.join(','),coordsys:'gps'});center=point(String(c.locations).split(';')[0].split(',').map(Number));}}
else{if(typeof b.place!=='string'||b.place.trim().length<2||b.place.length>150)throw Error('LOCATION_REQUIRED');const a=await get('geocode/geo',{address:b.place,city:String(b.city||'Shanghai').slice(0,50)});if(!a.geocodes?.length)throw Error('LOCATION_NOT_FOUND');if(a.geocodes.length!==1)return{mode:'choose_location',candidates:a.geocodes.slice(0,5).map(x=>({label:x.formatted_address,coords:point(x.location.split(',').map(Number))})),rows:[]};center=point(a.geocodes[0].location.split(',').map(Number));}
const d=await get('place/around',{location:center.join(','),keywords:cats[b.category],radius:2000,offset:9,page:1,sortrule:'distance',extensions:'base'});const rows=(d.pois||[]).slice(0,9).flatMap(x=>{try{return[{id:String(x.id),name:String(x.name).slice(0,100),address:Array.isArray(x.address)?'':String(x.address||'').slice(0,160),coords:point(x.location.split(',').map(Number)),distance:Number(x.distance)||null,status:'POI_ONLY',availability:'unknown',partner:false,booking:false}];}catch{return[];}});return{mode:'live-poi',center,system:'GCJ02',rows,checkedAt:new Date().toISOString(),provider:'Amap',note:'A place record does not establish stock, hours, currency service, partnership or reservation.'};}
async function image(b){if(b.consent!==true)throw Error('LOCATION_CONSENT_REQUIRED');if(!key)throw Error('AMAP_NOT_CONFIGURED');const center=point(b.center),rows=(b.rows||[]).slice(0,9);if(!rows.length)throw Error('MAP_POINTS_REQUIRED');const u=new URL('https://restapi.amap.com/v3/staticmap');const p={key,location:center.join(','),zoom:14,size:'640*420',scale:2,markers:rows.map((r,i)=>'mid,0x196455,'+(i+1)+':'+point(r.coords).join(',')).join('|')};for(const[k,v]of Object.entries(p))u.searchParams.set(k,String(v));calls++;const r=await fetcher(u,{redirect:'error',signal:AbortSignal.timeout(7000)});if(!r.ok||!r.headers.get('content-type')?.startsWith('image/'))throw Error('MAP_IMAGE_UNAVAILABLE');const chunks=[];let n=0;for await(const c of r.body){n+=c.length;if(n>4000000)throw Error('MAP_IMAGE_SIZE');chunks.push(Buffer.from(c));}return{body:Buffer.concat(chunks),type:r.headers.get('content-type')};}return{nearby,image,configure,status};}
function operations(dir=null){const file=dir?path.join(dir,'operations.json'):null;let data={policy:{...C.baseline},traces:[],feedback:[],candidates:[],audit:[]};if(file&&fs.existsSync(file)){const parsed=JSON.parse(fs.readFileSync(file));C.policy(parsed.policy);data={...data,...parsed};}
function save(){if(file){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(data,null,2),{mode:0o600});fs.renameSync(file+'.tmp',file);}}
function log(action,detail={}){data.audit.push({at:new Date().toISOString(),action,...detail});data.audit=data.audit.slice(-300);save();}
function trace(x){const t={id:crypto.randomUUID(),at:new Date().toISOString(),...x,policy:data.policy.id};data.traces.push(t);data.traces=data.traces.slice(-1000);save();return t;}
function feedback(b,sid){if(!['done','wrong_next','wrong_info','need_human'].includes(b.category))throw Error('INVALID_FEEDBACK');if(!data.traces.some(t=>t.id===b.trace&&t.session===sid))throw Error('TRACE_NOT_OWNED');if(data.feedback.some(f=>f.trace===b.trace&&f.category===b.category))return{deduplicated:true};const f={id:crypto.randomUUID(),trace:b.trace,session:sid,category:b.category,note:C.clean(b.note).slice(0,240),at:new Date().toISOString()};data.feedback.push(f);data.feedback=data.feedback.slice(-1000);log('feedback',{id:f.id});return f;}
function propose(b){if(!file)throw Error('SHARED_REVIEW_STORE_REQUIRED');const policy=C.policy(b.policy),reason=C.clean(b.reason).trim();if(!reason)throw Error('REVIEW_REASON_REQUIRED');const c={id:crypto.randomUUID(),policy,base:data.policy.id,reason,status:'candidate'};data.candidates.push(c);log('candidate',{id:c.id});return c;}
function replay(id){const c=data.candidates.find(x=>x.id===id);if(!c||c.status!=='candidate')throw Error('CANDIDATE_NOT_FOUND');c.replay=C.replay(c.policy);log('replay',{id});return c;}
function publish(b){const c=data.candidates.find(x=>x.id===b.id);if(b.confirm!==true)throw Error('REVIEW_CONFIRMATION_REQUIRED');if(!c||c.status!=='candidate'||!c.replay?.eligible)throw Error('PASSING_REPLAY_REQUIRED');if(c.base!==data.policy.id)throw Error('STALE_CANDIDATE');c.previous={...data.policy};data.policy={...c.policy,id:c.id};c.status='published';log('published',{id:c.id});return data.policy;}
function rollback(b){if(b.confirm!==true)throw Error('REVIEW_CONFIRMATION_REQUIRED');const c=data.candidates.find(x=>x.id===data.policy.id);if(!c?.previous)throw Error('NO_ROLLBACK');data.policy={...c.previous};c.status='rolled_back';log('rollback',{id:c.id});return data.policy;}
function view(){const judged=new Map();for(const f of data.feedback)judged.set(f.trace,f.category);const done=[...judged.values()].filter(x=>x==='done').length;return{...data,metrics:{turns:data.traces.length,judged:judged.size,done,completion:judged.size?done/judged.size:null,coverage:data.traces.length?judged.size/data.traces.length:null},unit:'turn-level user-confirmed prototype results; not production autonomous resolution or conversion'};}
return{trace,feedback,propose,replay,publish,rollback,view,policy:()=>({...data.policy})};}
module.exports={maps,operations,point};
