/* Public sources checked 2026-09-25. No live inventory or partner integration. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelServices=factory();})(globalThis,function(){
'use strict';
const definitions=[
 ['sh-metro-tickets','上海地铁购票与乘车 · Metro tickets','https://english.shanghai.gov.cn/en-Individuals-Transportation-PublicTransport/20260813/f257d5c373db4da3a8bde717b9f46b27.html','Shanghai Government','official',['地铁票','买票','乘车码','metro tickets','QR code'],'地铁可使用 Metro 大都会或支付宝、微信中的乘车服务。单程票可在车站购买，当日有效；出站换乘不能沿用同一张单程票。票价按距离计算，以车站和官方查询结果为准。','Use Metro Daduhui or supported Alipay/WeChat transit services. Buy single-journey tickets at stations; they are valid on the purchase day and do not cover out-of-station transfers. Confirm distance-based fares with the operator.'],
 ['sh-power-bank','上海共享充电宝使用指引 · Power banks','https://english.shanghai.gov.cn/en-MobileAndInternet/20260727/56b62a3a9d2f4ddaa8d77367c206b2ae.html','Shanghai Government','official',['充电宝','手机充电','没电','power bank','charging'],'商场、餐厅、地铁站等公共场所可寻找共享充电宝租借柜。扫码后先核对费用和归还规则，再按页面操作租借。本站没有接入柜机定位、剩余数量或实时价格，请使用地图和柜机运营商核实附近可借、可还的位置。','Look for rental cabinets in malls, restaurants and metro stations. Check rental fees and return instructions before renting. This site has no live cabinet locations, stock or prices; verify nearby rental and return points with the operator.'],
 ['sh-luggage-guide','上海行李寄存查询 · Luggage storage','https://english.shanghai.gov.cn/en-Individuals-Tourism-TouristServices/20260916/719ada5276444dfdb0d4f342ff68da26.html','Shanghai Government','official',['行李','寄存','存包','luggage','storage','bounce'],'上海官方旅游服务页提供地铁站、公园和商圈的行李寄存指引，以及存知己查询入口。可按所在地点查找寄存服务；是否营业、柜子余量、收费和行李尺寸限制需要在服务商页面再次核对。','The official tourist-service guide links to metro, park and commercial-area luggage storage and the Cunzhiji search platform. Check the provider for current hours, availability, fees and bag-size limits.'],
 ['sh-marriott-city-centre','上海雅居乐万豪侯爵酒店 · Marriott Marquis City Centre','https://www.marriott.com/en-us/hotels/shamc-shanghai-marriott-marquis-city-centre/overview/','Marriott','operator',['酒店','人民广场','住宿','hotel','Marriott','People Square'],'上海雅居乐万豪侯爵酒店位于黄浦区西藏中路555号。酒店官网列出附近人民广场地铁站，可乘1、2、8号线。这里展示真实酒店示例和官网入口；没有实时房价、房态，也没有替用户预订。','Shanghai Marriott Marquis City Centre is at 555 Middle Xizang Road, Huangpu. The hotel lists People’s Square station (lines 1, 2 and 8) nearby. This is a real hotel example with an official link, without live rates, availability or a reservation.']
];
const records=definitions.map(([id,title,url,publisher,sourceType,topics,summaryZh,summary])=>({id,title,url,publisher,sourceType,topics,summaryZh,summary,city:'Shanghai',kind:'reviewed_reference',recordType:'service',reviewedAt:'2026-09-25',reviewDays:30,active:true}));
const categories={hotel:['酒店','Hotels'],charging:['充电宝','Power banks'],luggage:['行李寄存','Luggage storage'],rail:['火车票','Train tickets'],metro_ticket:['地铁票','Metro tickets']};
const sourceFor={hotel:'sh-marriott-city-centre',charging:'sh-power-bank',luggage:'sh-luggage-guide',rail:'rail-passport',metro_ticket:'sh-metro-tickets'};
function cards(kind,location='',language='zh'){
 const zh=language==='zh',anchor=String(location||'上海').slice(0,100),key=categories[kind]?kind:'hotel',label=categories[key][zh?0:1],source=records.find(r=>r.id===sourceFor[key]);
 const map='https://uri.amap.com/search?keyword='+encodeURIComponent(anchor+' '+categories[key][0])+'&city=上海&view=map';
 const result=[{id:'service-'+key,kind:key,title:zh?anchor+' · '+label:label+' near '+anchor,description:zh?'地图／平台查询入口；位置、营业和余量需在打开后核对。':'Search the provider; confirm locations, opening hours and availability there.',url:key==='rail'?'https://www.12306.cn/en/':key==='metro_ticket'?records[0].url:map,sourceId:sourceFor[key],status:'provider-search'}];
 if(key==='hotel')result.push({id:'marriott-city-centre',kind:key,title:zh?'上海雅居乐万豪侯爵酒店':'Shanghai Marriott Marquis City Centre',description:zh?'真实酒店示例 · 西藏中路555号 · 人民广场周边；不代表距离你最近。':'Verified hotel example · 555 Middle Xizang Road · People’s Square area; not necessarily closest to you.',url:source.url,sourceId:source.id,status:'verified-place'});
 if(source&&key!=='hotel'&&key!=='metro_ticket')result.push({id:'guide-'+key,kind:key,title:zh?'官方使用与查询指引':'Official guide',description:zh?source.summaryZh:source.summary,url:source.url,sourceId:source.id,status:'official-guide'});
 return result;
}
return{records,categories,sourceFor,cards};
});
