/* Dated, published observations. Never a live inventory API. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelTransportHistory=factory();})(globalThis,function(){
'use strict';
const checkedAt='2026-09-25',railUrl='https://www.thepaper.cn/newsDetail_forward_27629921',airportUrl='https://www.shairport.com/xwg/info_itemid_41482.html',linkUrl='https://jtw.sh.gov.cn/xwfb2/20241226/a5c8290243d047b7b8d0d078e332708f.html';
const trains=[
 ['G7541','上海虹桥','杭州东','05:52',null,48,null],['G1321','上海虹桥','杭州东','06:10',null,73,null],['G7501','上海虹桥','杭州东','06:48',null,58,94],['G7461','上海虹桥','杭州东','09:57',null,87,null],
 ['G7376','杭州东','上海虹桥','15:40','16:33',87,null],['G7536','杭州东','上海虹桥','22:23','23:08',48,null]
].map(([train,origin,destination,departure,arrival,second,first])=>({train,origin,destination,departure,arrival,seats:{second,first},observedFor:'2024-06-15',publishedAt:'2024-06-05',sourceId:'history-sh-hz-trains',sourceUrl:railUrl,live:false}));
const records=[
 {id:'history-sh-hz-trains',title:'沪杭车次与席别价格 · 2024年6月历史观察',url:railUrl,publisher:'上观新闻报道（澎湃新闻转载）',sourceType:'media',recordType:'historical',publishedAt:'2024-06-05',topics:['高铁','二等座','一等座','便宜','时间','杭州','上海虹桥','rail','seat','cheap','Hangzhou'],summaryZh:'以下仅为报道查询2024年6月15日的历史车次，不是今日在售。上海虹桥到杭州东：G7541 05:52 二等座48元；G1321 06:10 二等座73元；G7501 06:48 二等座58元、一等座94元；G7461 09:57 二等座87元。杭州东到上海虹桥：G7376 15:40—16:33 二等座87元；G7536 22:23—23:08 二等座48元。未公布字段保持未知；出发站是上海虹桥，不是上海火车站。',summary:'Historical observations for 2024-06-15, published 2024-06-05, NOT current sales. Shanghai Hongqiao to Hangzhou East: G7541 05:52 second class CNY48; G1321 06:10 CNY73; G7501 06:48 second CNY58 / first CNY94; G7461 09:57 CNY87. Return: G7376 15:40–16:33 CNY87; G7536 22:23–23:08 CNY48. Unknown fields remain unknown. Hongqiao is NOT Shanghai Railway Station.'},
 {id:'history-airport-season',title:'浦东与虹桥机场 · 2025夏秋航季历史记录',url:airportUrl,publisher:'上海机场集团',sourceType:'operator',recordType:'historical',publishedAt:'2025-04-02',topics:['机场','航班','航线','浦东','虹桥','PVG','SHA','airport','flight'],summaryZh:'机场集团记录的2025年3月30日至10月25日夏秋航季，浦东日均计划航班1694架次、虹桥784架次。计划加密至武汉、福州、厦门、成都等国内航线。该记录证明当时的机场和航线规划，不证明今天的班次、航站楼、票价或余位；请用机场或航司查询当天航班。',summary:'Airport operator archive for the 2025-03-30 to 2025-10-25 season: planned daily movements PVG 1694, SHA 784. Plans included added domestic services for Wuhan, Fuzhou, Xiamen and Chengdu. Historical network information only; current flight numbers, terminals, fares and seats are not established.'},
 {id:'history-airport-link',title:'机场联络线 · 2024年开通公告',url:linkUrl,publisher:'上海市交通委员会',sourceType:'official',recordType:'historical',publishedAt:'2024-12-26',topics:['浦东','虹桥','机场联络线','交通','airport transfer'],summaryZh:'2024年12月26日开通公告记录虹桥2号航站楼站至浦东1号2号航站楼站，全程票价26元、通行约40分钟，初期两端首班06:00、末班22:00。它是市域线，不是航班或跨城高铁。此处是开通时历史记录，不承诺今日末班、班距和运营状况。',summary:'Opening notice dated 2024-12-26: Hongqiao Terminal 2 to Pudong Terminals 1/2, fare CNY26, about 40 minutes, initial first departures 06:00 and last departures 22:00. Suburban rail, not a flight or intercity high-speed train. An opening-era record, not a guarantee of today’s service.'}
].map(r=>({...r,city:'Shanghai',reviewedAt:checkedAt,reviewDays:30,kind:'reviewed_reference',active:true}));
function applicable(intent){const route=[intent?.destination,intent?.origin].join(' ');return intent?.kind==='rail'&&/杭州|Hangzhou/i.test(route)&&/上海|Shanghai/i.test(route);}
function compare(intent,{seat='second',sort='price',period='all'}={}){if(!applicable(intent))return[];const reverse=/杭州|Hangzhou/i.test(intent.origin||'');return trains.filter(t=>(reverse?t.origin==='杭州东':t.origin==='上海虹桥')&&(period==='all'||period==='morning'&&t.departure<'12:00'||period==='afternoon'&&t.departure>='12:00'&&t.departure<'18:00'||period==='evening'&&t.departure>='18:00')).map(t=>({...t,price:t.seats[seat]??null,seat})).sort((a,b)=>sort==='departure'?a.departure.localeCompare(b.departure):(a.price??Infinity)-(b.price??Infinity));}
function rail(intent,language='zh'){if(!applicable(intent))return null;const zh=language==='zh',explicitStation=/上海(?:火车)?站|Shanghai (?:Railway )?Station/i.test(intent.origin||''),prefix=explicitStation?(zh?'你指定的是上海火车站，已保留；下面收录的是上海虹桥的历史班次，只能作为换站备选，不能当作上海站出发。':'Your origin remains Shanghai Railway Station. Stored historical trains depart from Hongqiao and are alternatives requiring a station change. '):'';return{kind:'rail',sourceIds:['history-sh-hz-trains','rail-passport'],text:prefix+(zh?'可以按二等座／一等座、价格和出发时段比较下方历史记录。记录对应2024年6月15日，不是今天的班次和报价。原文没有的到达时间或席别价格显示“未记录”。请补充实际乘车日期，再到12306按准确车站查票。':'Compare the dated records below by class, fare and departure period. They refer to 2024-06-15, not today’s trains or prices. Unreported arrival times or fares remain unknown. Add your travel date and check the exact station pair on 12306.'),history:true};}
return{records,trains,compare,applicable,rail};
});
