const test=require('node:test'),assert=require('node:assert/strict'),T=require('./theme-routes'),D=require('./theme-routes-data'),L=require('./library'),E=require('./engine'),A=require('./assistant'),H=require('./transport-history'),MI=require('./model-intent');
test('all sixteen Shanghai districts have sourced bilingual route exports',()=>{assert.equal(D.districts.length,16);for(const d of D.districts){assert.equal(T.match(d.zh+'旅游路线'),d.id);MI.validate({kind:'itinerary',theme:d.id});for(const language of ['zh','en']){const p=T.build({theme:d.id,language,now:Date.parse('2026-09-25T13:00:00Z')});assert.ok(p.days[0].stops.length>=2,d.id);assert.equal(p.status,'ready',d.id);assert.ok(T.exportPlan(p).content.includes('https://'));}}});
test('dated rail comparison never fabricates absent seats or arrival times',()=>{const i={kind:'rail',origin:'上海火车站',destination:'杭州'};assert.match(H.rail(i).text,/上海火车站.*上海虹桥/);const rows=H.compare(i);assert.equal(rows[0].price,48);assert.equal(rows[0].arrival,null);assert.equal(H.compare(i,{seat:'first'})[0].price,94);assert.ok(H.compare(i,{seat:'first'}).some(x=>x.price===null));assert.equal(H.compare(i,{period:'evening'}).length,0);assert.equal(H.compare({kind:'rail',origin:'杭州东',destination:'上海虹桥'},{period:'evening'})[0].train,'G7536');});
test('multi-request interpretation retains charging location and exact rail origin',async()=>{const s=E.apply({...E.state(),language:'zh'},{type:'text',channel:'text',text:'上海火车站有什么充电宝吗？以及说火车站怎么去杭州呢？'});let classifications=0;const model={status:()=>({configured:true}),call:async(prompt,p)=>{if(!p.validationIssue){classifications++;return{value:{tasks:[{request:'上海火车站附近有充电宝吗',intent:{kind:'charging',destination:'上海火车站',city:'Shanghai'},source_ids:['sh-power-bank'],text:'请查询柜机运营商，本站没有实时柜位。'},{request:'上海火车站到杭州的高铁怎么坐',intent:{kind:'rail',origin:'上海火车站',destination:'杭州',city:'Shanghai'},source_ids:[],text:''}]},usage:{total_tokens:10}};}return{value:{text:'可以查询充电宝运营商，本站没有实时柜位。',source_ids:['sh-power-bank']},usage:{total_tokens:5}};}};const a=await A.assist({state:s,model,records:L.records});assert.equal(classifications,1);assert.equal(a.tasks.length,2);assert.equal(a.tasks[0].intent.kind,'charging');assert.equal(a.tasks[1].intent.origin,'上海火车站');assert.match(a.tasks[1].text,/换站备选/);assert.ok(a.tasks.every(x=>x.sourceIds.length));const restored=E.restoreMemory({...E.memory(s),history:[{...s.history[0],assistance:a}]});assert.equal(restored.history[0].assistance.tasks.length,2);assert.equal(restored.history[0].assistance.tasks[1].intent.origin,'上海火车站');});
test('all service eligibility categories use evidence realignment rather than a JCB keyword patch',async()=>{for(const kind of ['metro_ticket','charging','luggage','hotel','flight']){const s=E.apply({...E.state(),language:'zh'},{type:'text',text:'上海这项服务的使用办法',channel:'text'});let calls=0;const model={status:()=>({configured:true}),call:async(prompt,p)=>{calls++;if(calls===1)return{value:{intent:{kind,city:'Shanghai'},text:'没有个人信息所以不支持。',source_ids:['sh-power-bank']}};assert.match(prompt,/Missing details about the user never negate/);return{value:{text:'查询服务要求，个人条件尚待确认，不代表服务不支持。',source_ids:['sh-power-bank']}};}};const a=await A.assist({state:s,model,records:L.records.filter(x=>x.id==='sh-power-bank')});assert.equal(calls,2);assert.match(a.text,/不代表服务不支持/);}});
test('historical transport evidence remains dated and cannot masquerade as a live API',()=>{assert.ok(H.trains.every(t=>t.live===false&&t.observedFor==='2024-06-15'&&t.sourceUrl.startsWith('https://')));assert.ok(H.records.every(r=>r.recordType==='historical'));assert.equal(H.compare({kind:'rail',origin:'北京',destination:'上海'}).length,0);});
test('known chunk citations resolve to the parent source, unknown citations still fail',()=>{const evidence=[{id:'airport-record',summary:'Airport records.',chunkIds:['airport-record:v1:0']}];assert.deepEqual(A.validate({text:'Airport records.',source_ids:['airport-record:v1:0','airport-record']},evidence,[]).sourceIds,['airport-record']);assert.throws(()=>A.validate({text:'Airport records.',source_ids:['invented:v1:0']},evidence,[]),/ANSWER_SOURCE/);});
test('free historical comparison keeps the explicitly requested Shanghai Railway Station',()=>{const vm=require('node:vm'),fs=require('node:fs');const window={};vm.runInNewContext(fs.readFileSync(require.resolve('./transport-ui'),'utf8'),{window,document:{addEventListener(){}},TravelLibrary:L,TravelTransportHistory:H,TravelIntent:require('./intent-tools')});const html=window.TravelTransportUI.html({text:'上海火车站去杭州高铁',language:'zh',context:{city:'Shanghai'}});assert.match(html,/你选的是上海火车站/);assert.match(html,/换站备选/);});
test('queued detail markers survive archive restoration without becoming answered turns',()=>{const restored=E.restoreMemory({history:[{text:'补充一处细节',mergedDetail:true,language:'zh'}]});assert.equal(restored.history[0].mergedDetail,true);assert.equal(restored.history[0].assistance,undefined);});
