'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),Request=require('./request-semantics'),I=require('./intent-tools'),E=require('./engine'),A=require('./assistant'),L=require('./library'),Events=require('./event-data'),Products=require('./product-suggestions'),H=require('./transport-history'),Arb=require('./answer-arbitration'),News=require('./event-discovery');
test('station-only charging never creates a rail request in local memory',()=>{for(const text of ['上海火车站周围有充电宝吗','上海虹桥火车站附近手机没电了怎么充电','Where can I rent a power bank near Shanghai Railway Station?']){assert.equal(Request.railRequested(text),false,text);assert.ok(!E.parse(text,{}).tasks.includes('rail'));assert.equal(I.analyze(text,'Shanghai').kind,'charging');}});
test('explicit second rail need remains independent of station charging',()=>{assert.equal(Request.railRequested('上海火车站有充电宝吗，另外火车站怎么去杭州'),true);assert.equal(Request.railRequested('上海火车站哪里有充电宝，不要火车票'),false);});
test('arrival prose does not capture explicit metro or correction requests',()=>{assert.equal(Request.arrivalGuide('呃我现在从浦东机场降落了然后我要去上海虹桥火车站需要注意什么以及怎么走'),true);for(const t of ['My departure metro station is Shenmei Road; my arrival station is Pudong Airport Terminal 1&2.','Start from Hongqiao Airport Terminal 1 instead; the previous arrival stays.','从浦东机场到上海火车站地铁怎么坐'])assert.equal(Request.arrivalGuide(t),false);});
test('nearby dining keeps the existing discovery answer',()=>assert.equal(I.analyze('豫园附近有什么吃的','Shanghai').kind,'nearby'));
test('twenty bilingual starters are unique and opening is one sentence',()=>{const q=require('./starter-questions').questions;assert.equal(q.length,20);assert.equal(new Set(q.map(x=>x[0])).size,20);assert.ok(q.every(x=>x.length===2&&x.every(t=>t.length>12)));assert.equal(E.reply({...E.state(),language:'zh'}).say,'有什么我可以帮您？');});
test('dated train rows obey both inclusive departure bounds and seat choice',()=>{const intent={kind:'rail',origin:'上海虹桥',destination:'杭州东'};assert.deepEqual(H.compare(intent,{after:'06:00',before:'07:00'}).map(r=>r.train).sort(),['G1321','G7501']);assert.equal(H.compare(intent,{after:'23:00'}).length,0);assert.equal(H.compare(intent,{after:'06:00',before:'07:00',seat:'first'}).find(r=>r.train==='G7501').price,94);});
test('optional recommendations follow the actual service and negative preferences',()=>{assert.equal(Products.forIntent({kind:'charging'},'上海火车站').length,0);assert.equal(Products.forIntent({kind:'rail',responseMode:'service'},'高铁AMEX').length,0);assert.ok(!Products.forIntent({kind:'rail'},'不需要酒店').some(r=>r.id==='hotel'));assert.ok(Products.forIntent({kind:'hotel'},'查住宿').some(r=>r.id==='tour'));assert.ok(Products.forIntent({kind:'rail'}).every(r=>r.liveInventory===false));});
test('expired events disappear according to Shanghai end of day',()=>{assert.ok(Events.active(Events.records,Date.parse('2026-09-25T12:00Z')).some(r=>r.id==='event-sh-snacks-2026'));assert.ok(!Events.active(Events.records,Date.parse('2026-09-27T16:00Z')).some(r=>r.id==='event-sh-snacks-2026'));assert.equal(Events.active([{...Events.records[0],active:false}],Date.parse('2026-09-25')).length,0);});
test('event body evidence rejects wrong months years dates and invented locations',()=>{const V=require('./event-evidence').verify,body='The fair is held September 26–30, 2026 at Global Harbor.',e={startDate:'2026-09-26',endDate:'2026-09-30',location:'Global Harbor',dateQuote:'September 26–30, 2026'};assert.ok(V(e,body,Date.parse('2026-09-25')));for(const p of [{startDate:'2026-10-26',endDate:'2026-10-30'},{endDate:'2026-09-31'},{location:'Shanghai Station'},{startDate:'2027-09-26',endDate:'2027-09-30'}])assert.equal(V({...e,...p},body,Date.parse('2026-09-25')),null);});
test('official news discovery ignores foreign hosts query tricks future and old pages',()=>{const html=['https://english.shanghai.gov.cn/en-Events/20260924/a.html','https://evil.test/en-Events/20260924/a.html','https://english.shanghai.gov.cn/en-Events/20260124/a.html','https://english.shanghai.gov.cn/en-Events/20260924/a.html?next=evil'].map(u=>'<a href="'+u+'">International visitor festival</a>').join('');assert.equal(News.links(html,'https://english.shanghai.gov.cn',Date.parse('2026-09-25')).length,1);});
test('daily event discovery lease prevents concurrent and premature repeat fetches',async()=>{let s=require('./operations').initial(),calls=0;const store={read:async()=>s,mutate:async fn=>fn(s)},discoverFn=async()=>{calls++;return{at:'2026-09-25',candidates:[],checks:[]}};await News.daily(store,{now:Date.parse('2026-09-25'),discoverFn});await News.daily(store,{now:Date.parse('2026-09-25')+1000,discoverFn});assert.equal(calls,1);assert.equal(s.eventRefresh.assessmentCount,0);});
test('arbitration actually combines checked answers and reports missing comparison',()=>{const local={text:'请核对已购买车票和站内指示，携带购票时有效证件。',sourceIds:['rail-passport']},generated={text:'请先核对后续火车站名称，并为安检和步行留出时间。',sourceIds:['rail-boarding-practical']};const d=Arb.decide(local,generated,{kind:'other'},'进站准备');assert.equal(d.selected,'combined');const a=Arb.apply(local,generated,d);assert.ok(a.text.includes(local.text)&&a.text.includes(generated.text));assert.equal(Arb.decide(local,null,{kind:'rail'},'高铁').deepseek,null);});
test('airport guide uses grounded model prose without imposing topology',async()=>{const state=E.apply({...E.state(),language:'zh'},{type:'text',channel:'text',text:'浦东刚降落，要去上海虹桥火车站，怎么走注意什么？'});let calls=0;const model={status:()=>({configured:true}),call:async(p,body)=>{calls++;return calls===1?{value:{intent:{kind:'rail',city:'上海',origin:'浦东机场',destination:'上海虹桥火车站',responseMode:'guide'},retrieval_query:'浦东落地虹桥机场联络线指引',text:'',source_ids:[]}}:{value:{text:'先跟随机场联络线指示，到虹桥后再按火车站指引进站。为取行李、步行和安检留出时间，并核对自己的后续车票。',source_ids:['arrival-airport-link-guide']},usage:{total_tokens:10}};}};const a=await A.assist({state,model,records:L.records});assert.equal(a.intent.responseMode,'guide');assert.ok(!a.tool?.metro);assert.equal(a.arbitration.selected,'deepseek');assert.equal(calls,2);});

test('numeric failure after valid intent is corrected with unchanged source constraints and token accounting',async()=>{const state=E.apply({...E.state(),language:'zh'},{type:'text',channel:'text',text:'浦东机场降落后怎么去虹桥火车站，需要注意什么？'});let calls=0,previousEvidence;const model={status:()=>({configured:true}),call:async(prompt,body)=>{calls++;if(calls===1)return{value:{intent:{kind:'rail',city:'Shanghai',origin:'浦东机场',destination:'上海虹桥火车站',responseMode:'guide'},text:'为取行李和步行留出时间。',source_ids:['arrival-airport-link-guide']},usage:{total_tokens:10}};if(calls===2){previousEvidence=body.evidence;assert.ok(body.numberEvidence.sources.some(s=>s.sourceId==='arrival-airport-link-guide'));return{value:{text:'请提前99999分钟到站。',source_ids:['arrival-airport-link-guide']},usage:{total_tokens:20}};}assert.equal(body.validationIssue,'ANSWER_NUMBER');assert.deepEqual(body.unsupportedNumbers,['99999']);assert.deepEqual(body.evidence,previousEvidence);return{value:{text:'跟随机场联络线标识，到达虹桥后按火车站指引走。为取行李、步行和安检留出时间。',source_ids:['arrival-airport-link-guide']},usage:{total_tokens:30}};}};const answer=await A.assist({state,model,records:L.records});assert.equal(calls,3);assert.equal(answer.usage.total_tokens,60);assert.ok(!answer.text.includes('99999'));assert.ok(answer.execution.stages.some(s=>s.name==='numeric_repair'&&s.attempts===1));assert.ok(!answer.tool?.metro);});
test('low solved rate turns red only with sufficient observations',()=>{const M=require('./ops-metrics');assert.equal(M.rows({quality:{solved:1,rated:40}}).find(r=>r.key==='resolution').anomaly,true);assert.equal(M.rows({quality:{solved:1,rated:4}}).find(r=>r.key==='resolution').anomaly,false);assert.match(M.render({quality:{solved:1,rated:40}}),/metric-anomaly/);});
test('support model always sees channel distinction and missing prerequisites rule',()=>{assert.match(A.PROMPT,/Missing details about the user never negate/);assert.match(A.PROMPT,/third-party card does not prove direct railway/);const source=L.get('channel-trip-payment');assert.match(source.summaryZh,/不能推出12306/);});

test('model city aliases share evidence keys without changing endpoints or unknown cities',()=>{const MI=require('./model-intent');for(const [city,expected] of [['上海','Shanghai'],['上海市','Shanghai'],['shanghai','Shanghai'],['Shanghai, China','Shanghai'],['北京市','Beijing'],['BEIJING','Beijing'],['中国','China'],['Unknown',null],['杭州','杭州']]){const intent=MI.validate({kind:'charging',city,destination:'上海火车站'});assert.equal(intent.city,expected);assert.equal(intent.destination,'上海火车站');}});

test('rail payment answer cannot be overwritten by an unrelated route collection tool',async()=>{const state=E.apply({...E.state(),language:'en'},{type:'text',channel:'text',text:'Can I buy a high-speed train ticket on Trip.com with American Express?'});let calls=0;const model={status:()=>({configured:true}),call:async()=>{calls++;return{value:{intent:{kind:'rail',city:'China',responseMode:'service'},text:'Trip.com lists American Express. Check the specific checkout and issuer authorization; this does not establish direct 12306 acceptance.',source_ids:['channel-trip-payment']},usage:{total_tokens:12}};}};const a=await A.assist({state,model,records:L.records});assert.match(a.text,/Trip.com lists American Express/);assert.equal(a.arbitration.selected,'deepseek');assert.equal(a.arbitration.local,null);assert.equal(calls,2);});
test('event questions request evidence prose rather than a generic nearby tool',()=>assert.equal(Request.responseMode('最近上海有什么适合外国人的活动',{kind:'nearby',responseMode:'general'}),'guide'));

test('event body with unverified calendar dates is held instead of published as timeless facts',()=>{const B=require('./source-body'),content='The visitor exhibition takes place September 26 to 30, 2026 at Global Harbor in Shanghai.';const value={score:91,relevant:true,expired:false,conflict:false,quotes:[content],event:{startDate:'2026-10-26',endDate:'2026-10-30',location:'Global Harbor',dateQuote:'September 26 to 30, 2026'}};const a=B.checkAssessment(value,{content,hash:'body-hash',at:'2026-09-25'},{id:'sample-event',url:'https://english.shanghai.gov.cn/en-Events/20260925/sample.html'});assert.equal(a.eligible,false);assert.ok(a.score<60);});
