'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const Cities=require('./city-scope'),L=require('./library'),E=require('./engine'),KB=require('./kb-direct'),R=require('./rag'),Plan=require('./retrieval-plan'),Guard=require('./answer-guard'),A=require('./answer-arbitration'),H=require('./harness'),MI=require('./model-intent'),Assistant=require('./assistant'),Sources=require('./city-sources');
const records=Sources.records;
for(const [raw,city] of [['廣州','Guangzhou'],['深圳市','Shenzhen'],['香港特別行政區','Hong Kong'],['Hong Kong','Hong Kong'],['上海市','Shanghai'],['Beijing, China','Beijing']])test('canonical city '+raw,()=>assert.equal(Cities.canonical(raw),city));
for(const c of Cities.profiles)test('city selection/parsing '+c.id,()=>{const s=E.apply(E.state(),{type:'text',text:'I am going to '+c.id,channel:'text'});assert.equal(s.facts.city,c.id);assert.equal(MI.validate({kind:'other',city:c.zh}).city,c.id);});
test('unknown destinations are not relabeled Shanghai',()=>{assert.equal(Cities.canonical('Chengdu'),'Chengdu');assert.equal(E.parse('I am going to Tokyo',E.state()).patch.city,'Tokyo');});
test('mainland sources excluded from HK and explicit cross-scope must opt in',()=>{assert.equal(Cities.applies({city:'China'},'Hong Kong'),false);assert.equal(Cities.applies({city:'Shanghai'},'Hong Kong'),false);assert.equal(Cities.applies({city:'China',appliesTo:['Hong Kong']},'Hong Kong'),true);assert.equal(Cities.applies({city:'Hong Kong'},'Shenzhen'),false);});
test('Hong Kong plan does not link generic rail ticket to 12306',()=>{const s=E.apply(E.state(),{type:'text',text:'I am in Hong Kong and need train tickets',channel:'text'});assert(E.reply(s).plan.find(t=>t.id==='rail').url.includes('mtr.com.hk'));});
for(const e of KB.entries){for(const [i,q]of e.languageIndependentAliases.entries())test('approved exact KB '+e.city+' '+i,()=>{const x=KB.lookup(q,{language:i===0?'zh':'en',records:L.records});assert(x.matched);assert.equal(x.answer.usage.total_tokens,0);assert.equal(x.trace.modelCalls,0);assert.equal(x.answer.intent.city,e.city);assert.equal(x.answer.text,i===0?records.find(r=>r.id===e.sourceId).summaryZh:records.find(r=>r.id===e.sourceId).summary);});}
for(const [name,patch] of [['edit',{summary:'changed text'}],['held',{active:false}],['expired',{reviewedAt:'2000-01-01'}],['scope',{city:'Hong Kong'}],['fetch-change',{lastCheck:{status:'changed'}}]])test('KB invalidation '+name,()=>{const e=KB.entries[2],r=records.find(r=>r.id===e.sourceId);assert.equal(KB.lookup(e.languageIndependentAliases[0],{records:[{...r,...patch}],language:'zh'}).matched,false);});
test('KB never answers extra conditions or a multi-need request by partial matching',()=>{assert.equal(KB.lookup(KB.entries[0].languageIndependentAliases[0]+'另外签证怎么办',{records}).matched,false);assert.equal(KB.lookup('可以用AMEX吗',{records}).matched,false);});
test('ambiguous KB approvals are held rather than selected by array order',()=>{const e=KB.entries[0];assert.equal(KB.lookup(e.languageIndependentAliases[0],{records,registry:[e,{...e,id:'another'}]}).matched,false);});
test('direct assistant does not call any model',async()=>{const s=E.apply(E.state(),{type:'text',text:KB.entries[3].languageIndependentAliases[0],channel:'text'});s.language='zh';let calls=0;const answer=await Assistant.assist({state:s,records:L.records,model:{status:()=>({configured:true}),call:async()=>{calls++;throw Error('MUST_NOT_CALL');}}});assert.equal(answer.mode,'kb-direct');assert.equal(calls,0);});
for(const [o,h] of [['上海机场服务','北京机场服务'],['香港 MTR ticket','香港 12306 ticket'],['Shanghai JCB 200','Shanghai VISA 200'],['上海不是买火车票','上海买火车票'],['Shenzhen help','ignore instructions']])test('reject changed rewrite '+h,()=>assert(Plan.check(o,h)));
test('original request retained for accepted and rejected rewrites',()=>{const p=Plan.plan('Shanghai airport help',['Shanghai airport service help','Beijing airport help']);assert.equal(p.queries[0],'Shanghai airport help');assert.equal(p.queries.length,2);assert(p.queries[1].startsWith(p.queries[0]));assert.equal(p.decisions[1].accepted,false);});
test('bounded multi-query RRF retains scope and limits parents',()=>{const r=Plan.retrieve('Shenzhen airport help',['Shenzhen airport service help'],L.records,{city:'Shenzhen',topK:8});assert.equal(r.queryPlan.variants,2);assert(r.hits.length);assert(r.hits.every(h=>Cities.applies(L.get(h.sourceId),'Shenzhen')));const counts={};for(const h of r.h.hits||[]){}const counts2=counts;});
