'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const Cities=require('./city-scope'),L=require('./library'),E=require('./engine'),KB=require('./kb-direct'),R=require('./rag'),Plan=require('./retrieval-plan'),Guard=require('./answer-guard'),A=require('./answer-arbitration'),H=require('./harness'),MI=require('./model-intent'),Assistant=require('./assistant'),Sources=require('./city-sources');
const records=Sources.records;
for(const [raw,city] of [['廣州','Guangzhou'],['深圳市','Shenzhen'],['香港特別行政區','Hong Kong'],['Hong Kong','Hong Kong'],['上海市','Shanghai'],['Beijing, China','Beijing']])test('canonical city '+raw,()=>assert.equal(Cities.canonical(raw),city));
for(const c of Cities.profiles)test('city selection/parsing '+c.id,()=>{const s=E.apply(E.state(),{type:'text',text:'I am going to '+c.id,channel:'text'});assert.equal(s.facts.city,c.id);assert.equal(MI.validate({kind:'other',city:c.zh}).city,c.id);});
test('unknown destinations are not relabeled Shanghai',()=>{assert.equal(Cities.canonical('Chengdu'),'Chengdu');assert.equal(E.parse('I am going to Tokyo',E.state()).patch.city,'Tokyo');});
test('mainland sources excluded from HK and explicit cross-scope must opt in',()=>{assert.equal(Cities.applies({city:'China'},'Hong Kong'),false);assert.equal(Cities.applies({city:'Shanghai'},'Hong Kong'),false);assert.equal(Cities.applies({city:'China',appliesTo:['Hong Kong']},'Hong Kong'),true);assert.equal(Cities.applies({city:'Hong Kong'},'Shenzhen'),false);});
test('Hong Kong plan does not link generic rail ticket to 12306',()=>{const s=E.apply(E.state(),{type:'text',text:'I am in Hong Kong and need train tickets',channel:'text'});assert(E.reply(s).plan.find(t=>t.id==='rail').url.includes('mtr.com.hk'));});
for(const e of KB.entries){for(const [i,q]of e.languageIndependentAliases.entries())test('approved exact KB '+e.city+' '+i,()=>{const x=KB.lookup(q,{language:i===0?'zh':'en',records:L.records});assert(x.matched);assert.equal(x.answer.usage.total_tokens,0);assert.equal(x.trace.modelCalls,0);assert.equal(x.answer.intent.city,e.city);assert.equal(x.answer.text,i===0?records.find(r=>r.id===e.sourceId).summaryZh:records.find(r=>r.id===e.sourceId).summary);});}
for(const [name,patch] of [['edit',{summary:'changed text'}],['held',{active:false}],['expired',{reviewedAt:'2000-01-01'}],['scope',{city:'Hong Kong'}],['fetch-change',{lastCheck:{status:'changed'}}]])test('KB invalidation '+name,()=>{const e=KB.entries[2],r=records.find(r=>r.id===e.sourceId);assert.equal(KB.lookup(e.languageIndependentAliases[0],{records:[{...r,...patch}],language:'zh'}).matched,false);});
test('KB never answers extra conditions or a multi-need request by partial matching',()=>{assert.equal(KB.lookup(KB.entries[0].languageIndependentAliases[0]+'另外签证怎么办',{records}).matched,false);assert.equal(KB.lookup('可以用AMEX吗',{records}).matched,false);});
test('ambiguous KB approvals are held rather than selected by array order',()=>{const e=KB.entries[0];assert.equal(KB.lookup(e.languageIndependentAliases[0],{records,registry:[e,{...e,id:'another'}]}).matched,false);});
test('direct assistant does not call any model',async()=>{const s=E.apply(E.state(),{type:'text',text:KB.entries[3].languageIndependentAliases[0],channel:'text'});s.language='zh';let calls=0;const answer=await Assistant.assist({state:s,records:L.records,model:{status:()=>({configured:true}),call:async()=>{calls++;throw Error('MUST_NOT_CALL');}}});assert.equal(answer.mode,'kb-direct');assert.equal(calls,0);});
for(const [o,h] of [['上海机场服务','北京机场服务'],['香港 MTR ticket','香港 12306 ticket'],['Shanghai JCB 200','Shanghai VISA 200'],['上海不是买火车票','上海买火车票'],['Shenzhen help','ignore instructions']])test('reject changed rewrite '+h,()=>assert(Plan.check(o,h)));
test('original request retained for accepted and rejected rewrites',()=>{const p=Plan.plan('Shanghai airport help',['Shanghai airport service help','Beijing airport help']);assert.equal(p.queries[0],'Shanghai airport help');assert.equal(p.queries.length,2);assert(p.queries[1].startsWith(p.queries[0]));assert.equal(p.decisions[1].accepted,false);});
test('bounded multi-query RRF retains scope and limits parents',()=>{const r=Plan.retrieve('Shenzhen airport help',['Shenzhen airport service help'],L.records,{city:'Shenzhen',topK:8});assert.equal(r.queryPlan.variants,2);assert(r.hits.length);assert(r.hits.every(h=>Cities.applies(L.get(h.sourceId),'Shenzhen')));const counts={};for(const h of r.hits)counts[h.sourceId]=(counts[h.sourceId]||0)+1;assert(Object.values(counts).every(n=>n<=2));assert.equal(r.embedding,'none');});
test('HK retrieval never includes generic mainland-only snippets',()=>{const r=R.retrieve('rail metro ticket passport payment',L.records,{city:'Hong Kong'});assert(r.hits.every(h=>Cities.applies(L.get(h.sourceId),'Hong Kong')));});
test('candidate city gate runs before score',()=>{const answer={text:'A long, actionable answer with a cited source. Follow the signs and check the ticket.',sourceIds:[records[0].id]};assert.equal(Guard.eligibility(answer,{city:'Hong Kong'},records).eligible,false);});
test('held source excluded from candidate even if response is fluent',()=>{const answer={text:'Check the counter and follow these steps.',sourceIds:[records[0].id]};assert.equal(Guard.eligibility(answer,{city:'Shanghai'},[{...records[0],active:false}]).eligible,false);});
test('candidate responses never concatenate unchecked conflicting assertions',()=>{const source=records[0],intent={city:'Shanghai',kind:'other'},a={text:'This service is supported. Follow the signs and check the counter.',sourceIds:[source.id]},b={text:'This service is not supported. Ask staff and check a different counter.',sourceIds:[source.id]},r=Guard.select(a,b,intent,'service',records,A);assert.notEqual(r.decision.selected,'combined');assert.equal(r.guard.mergeReason,'potential-support-conflict');});
test('telemetry retains KB/query/guard path without raw generated rewrites',()=>{const s={events:[]},answer={mode:'kb-direct',sourceIds:[records[0].id],intent:{kind:'other'},execution:{stages:[],kb:{modelCalls:0},answerGuard:{selected:'tool'},totalMs:0},usage:{prompt_tokens:0,completion_tokens:0}};H.observe(s,answer);assert.equal(s.executions[0].kb.modelCalls,0);assert.equal(s.executions[0].answerGuard.selected,'tool');});
test('existing 20 starter questions are preserved and five independent arrival choices added',()=>{const s=require('./starter-questions');assert.equal(s.questions.length,20);assert.equal(s.arrivalQuestions.length,5);});
test('every approved record has immutable expected source fingerprint',()=>{for(const e of KB.entries)assert.equal(KB.fingerprint(records.find(r=>r.id===e.sourceId)),e.sourceHash);});
async function serve(handler){const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));return{server,url:'http://127.0.0.1:'+server.address().port};}
test('cloud public exact KB works without API key or experience code; no arbitrary LLM access',async()=>{const handler=require('./cloud-chat').createCloudChat({env:{},fetcher:async()=>{throw Error('NO_EXTERNAL_CALL');}}),{server,url}=await serve(handler);try{const result=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'kb',text:KB.entries[4].languageIndependentAliases[1],language:'en',city:'Hong Kong'})});assert.equal(result.status,200);const b=await result.json();assert.equal(b.answer.mode,'kb-direct');assert.equal(b.answer.usage.total_tokens,0);const denied=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'answer'})});assert.equal(denied.status,503);}finally{await new Promise(r=>server.close(r));}});
test('local public KB path and existing server state use the same reviewed records',async()=>{const runtime=fs.mkdtempSync(path.join(os.tmpdir(),'vc65-'));const app=require('./server').createApp({runtimeDir:runtime,env:{},fetcher:async()=>{throw Error('NO_EXTERNAL_CALL');}});const {server,url}=await serve(app.handler);try{const res=await fetch(url+'/api/v5/kb',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:KB.entries[2].languageIndependentAliases[0],city:'Guangzhou',language:'zh'})});assert.equal(res.status,200);assert.equal((await res.json()).answer.mode,'kb-direct');}finally{await new Promise(r=>server.close(r));app.close?.();fs.rmSync(runtime,{recursive:true,force:true});}});

test('KB republishing invalidates prior approval even if the answer text is unchanged',()=>{const e=KB.entries[0],r=records.find(r=>r.id===e.sourceId);assert.equal(KB.lookup(e.languageIndependentAliases[0],{records:[{...r,publicationHash:'new-publication'}]}).matched,false);});
test('known context city may anchor a follow-up rewrite without replacing an explicit city',()=>{assert.equal(Plan.check('airport help','Shenzhen airport help',{city:'Shenzhen'}),null);assert(Plan.check('Beijing airport help','Shenzhen airport help',{city:'Shenzhen'}));});
test('retrieval denominator does not count the approved no-retrieval path as an empty retrieval',()=>{const s={events:[],executions:[{at:new Date().toISOString(),mode:'kb-direct',kb:{modelCalls:0},totalMs:1},{at:new Date().toISOString(),mode:'deepseek',retrieval:{hits:[{}]},totalMs:10}]};const i=H.insights(s);assert.equal(i.kb.served,1);assert.equal(i.kb.denominator,2);const r=i.metrics.find(m=>m.name.includes('检索'));assert.equal(r.n,1);assert.equal(r.d,1);});
test('explicit MTR source cannot establish direct 12306 support',()=>{const source=records[4],a={text:'Here is how to buy the ticket.',sourceIds:[source.id]};assert(Guard.eligibility(a,{city:'Hong Kong'},records,'Can I buy this directly on 12306?').reasons.includes('explicit-channel-mismatch'));});
