'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const P=require('./product-suggestions'),Choices=require('./choice-memory'),Presets=require('./skill-presets'),H=require('./harness'),O=require('./operations'),E=require('./engine'),{catalog,createOps}=require('./ops-api'),{auth}=require('./ops-auth');
for(const city of ['Shanghai','Beijing','Guangzhou','Shenzhen','Hong Kong'])test('related products retain city and never claim inventory: '+city,()=>{for(const product of Object.keys(P.items)){const r=P.prepare({product,city,language:'en'});assert.equal(r.request.city,city);assert.equal(r.mode,'mock-adapter');assert.equal(r.bookingCreated,false);assert.equal(r.providerRequestSent,false);assert.ok(r.offers.every(x=>x.price===null&&x.inventory===null&&x.bookable===false&&x.prefilled===false));assert.ok(r.offers.every(x=>new URL(x.url).protocol==='https:'));if(city==='Hong Kong')assert.ok(r.offers.every(x=>!x.url.includes('12306')&&!x.url.includes('meituan')));}});
for(const [name,context]of[['unsolved',{outcome:'unsolved'}],['low battery',{facts:{battery:3}}],['offline',{facts:{network:'offline'}}],['user suppressed',{suppressed:true}]])test('recommendation suppression '+name,()=>assert.deepEqual(P.forIntent({kind:'rail'},'',context),[]));
test('self-drive and transfers are separate and English opt-outs respected',()=>{assert.equal(P.forIntent({kind:'taxi'},'No rental car').some(r=>r.id==='car'),false);assert.equal(P.forIntent({kind:'rail'},'不要租车，不需要酒店').some(r=>['car','hotel'].includes(r.id)),false);assert.match(P.prepare({product:'car'}).qualification,/驾驶资格/);assert.equal(P.prepare({product:'transfer'}).qualification,null);});
test('known hotel/flight booking suppresses redundant suggestions without making new bookings',()=>{assert.ok(!P.forIntent({kind:'rail'},'',{facts:{hotel:'booked'}}).some(x=>x.id==='hotel'));const s=E.apply(E.state(),{type:'text',text:'My flight is booked but my hotel is not booked.'});P.prepare({product:'hotel',city:'Shanghai'});assert.equal(s.facts.hotel,'not_booked');assert.equal(s.facts.flight,'booked');});
test('payment service answer and charging requests do not upsell',()=>{for(const kind of ['rail','metro_ticket','charging','luggage'])assert.deepEqual(P.forIntent({kind,responseMode:'service'},'Need help paying'),[]);});
for(const value of [{product:'rail',url:'https://evil.test'}, {product:'rail',origin:'https://example.com'},{product:'hotel',city:'<script>'},{product:'flight',destination:'me@example.com'},{product:'rail',date:'2026-02-31'}, {product:'rail',after:'24:00'},{product:'rail',after:'18:00',before:'06:00'}, {product:'rail',seat:'executive'}])test('mock adapter rejects malformed or over-scoped input '+JSON.stringify(value),()=>assert.throws(()=>P.prepare(value)));
test('rail search retains exact endpoint and departure window, missing date is not invented',()=>{const r=P.prepare({product:'rail',city:'Shanghai',origin:'上海火车站',destination:'杭州东',after:'06:00',before:'12:00',seat:'second'});assert.equal(r.request.origin,'上海火车站');assert.equal(r.request.date,null);assert.ok(r.missingFields.includes('date'));assert.equal(r.request.after,'06:00');assert.equal(r.request.before,'12:00');});
test('explicit choice memory survives rerender and refresh, does not contain answers or bookings',()=>{const map=new Map(),storage=()=>({getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)});const a=Choices(storage);a.put('answer-1',{saved:['tour'],rail:{after:'09:00',before:'12:00',seat:'first',sort:'departure'}});const b=Choices(storage);assert.deepEqual(b.get('answer-1').saved,['tour']);assert.equal(b.get('answer-1').rail.after,'09:00');b.put('answer-1',{saved:['car'],bookingConfirmed:true,rawConversation:'secret'});assert.ok(!JSON.stringify(b.get('answer-1')).includes('secret'));assert.equal(b.get('answer-1').bookingConfirmed,undefined);b.clear();assert.equal(b.get('answer-1').saved.length,0);});
test('candidate preset has bounded, explicit changes only',()=>{for(const p of Presets.list){const c=H.config(Presets.apply(p.id,H.DEFAULT));assert.ok(c.topK<=12&&c.minCoverage<=.4);assert.equal(c.chunkSize,H.DEFAULT.chunkSize);}assert.throws(()=>Presets.apply('run-shell',H.DEFAULT),/PRESET/);});
test('all candidate origins share automatic evaluation and do not publish',()=>{const r=catalog(O.initial());for(const origin of ['manual','feedback-rule','feedback-case','full-sample-loop','operator-preset:coverage']){const s=O.initial(),row=H.propose(s,H.DEFAULT,'admin',r,origin);assert.equal(row.status,'accepted');assert.equal(row.comparison.regressed,0);assert.equal(row.comparison.baselinePassed,row.evaluation.total);assert.equal(row.evaluation.semanticAssessment,'requires-human-replay');assert.equal(H.state(s).active.version,H.DEFAULT.version);assert.match(row.evaluation.evaluatorHash,/^[a-f0-9]{64}$/);}});
test('stale code/source evaluation cannot publish; explicit revalidation still awaits human release',()=>{const s=O.initial(),r=catalog(s),a=H.propose(s,H.DEFAULT,'admin',r);a.evaluation.evaluatorHash='old-code';assert.throws(()=>H.publish(s,a.id,a.hash,'admin',r),/RETEST/);const check=H.revalidate(s,a.id,a.hash,'admin',r);assert.equal(check.evaluationHistory.length,1);assert.equal(check.status,'accepted');assert.equal(H.state(s).active.version,H.DEFAULT.version);H.publish(s,a.id,a.hash,'admin',r);assert.throws(()=>H.revalidate(s,a.id,a.hash,'admin',r),/ACCEPTANCE/);});
test('city and review-days changes invalidate source fingerprint',()=>{const s=O.initial(),r=catalog(s),a=H.propose(s,H.DEFAULT,'admin',r);for(const field of ['city','reviewDays','jurisdiction']){const c=r.map((x,i)=>i?x:{...x,[field]:field==='reviewDays'?1:'changed'});assert.notEqual(H.corpusHash(c),a.evaluation.corpusHash);assert.throws(()=>H.publish(s,a.id,a.hash,'admin',c),/RETEST/);}});
async function serve(t,handler){const srv=http.createServer(handler);await new Promise(resolve=>srv.listen(0,'127.0.0.1',resolve));t.after(()=>{srv.closeAllConnections();srv.close();});return 'http://127.0.0.1:'+srv.address().port;}
test('actual mock product HTTP: method, origin, JSON, malformed inputs and no external calls',async t=>{const url=await serve(t,require('./product-api').createProducts());const send=(body,headers={})=>fetch(url,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});assert.equal((await fetch(url)).status,405);assert.equal((await send({product:'rail'},{origin:'https://evil.example'})).status,403);assert.equal((await send({product:'rail',url:'https://evil.example'})).status,400);const result=await send({product:'rail',city:'上海',after:'06:00',before:'12:00'});assert.equal(result.status,200);const b=await result.json();assert.equal(b.providerRequestSent,false);assert.equal(b.request.city,'Shanghai');assert.equal((await send({product:'rail',city:'x'.repeat(13000)})).status,413);});
test('Operations preset/revalidate require admin, preserve state until manual publication',async t=>{const env={OPS_SESSION_SECRET:'fixture-secret'.repeat(3),OPS_USERS_JSON:JSON.stringify({admin:{role:'admin'},reviewer:{role:'reviewer'}})};let saved=O.initial();const store={kind:'test',read:async()=>structuredClone(saved),mutate:async f=>{const next=structuredClone(saved),out=f(next);saved=next;return out;}};const url=await serve(t,createOps({env,store}));async function post(body,actor){return fetch(url,{method:'POST',headers:{'content-type':'application/json',cookie:actor?'vc_ops='+auth(env).issue({actor}):''},body:JSON.stringify(body)});}assert.equal((await post({action:'skill-preset',preset:'coverage'})).status,403);assert.equal((await post({action:'skill-preset',preset:'coverage'},'reviewer')).status,403);const response=await post({action:'skill-preset',preset:'coverage'},'admin');assert.equal(response.status,200);const row=(await response.json()).result;assert.equal(row.origin,'operator-preset:coverage');assert.equal(saved.harness.active.topK,8);const checked=await post({action:'skill-revalidate',id:row.id,hash:row.hash},'admin');assert.equal(checked.status,200);assert.equal(saved.harness.active.topK,8);assert.ok(saved.audit.some(x=>x.type==='skill-revalidate'));});

test('departure periods and explicit time windows have the same intersection used by the table',()=>{
 assert.deepEqual(P.departureWindow({period:'morning'}),{after:'00:00',before:'11:59'});
 assert.deepEqual(P.departureWindow({period:'afternoon',after:'13:30',before:'21:00'}),{after:'13:30',before:'17:59'});
 assert.deepEqual(P.departureWindow({period:'all',after:'06:00',before:'12:00'}),{after:'06:00',before:'12:00'});
 assert.throws(()=>P.departureWindow({period:'morning',after:'18:00'}),/DEPARTURE_WINDOW/);
 assert.throws(()=>P.departureWindow({period:'midnight'}),/DEPARTURE_PERIOD/);
});
test('provider source changes invalidate the candidate corpus',()=>{const s=O.initial(),r=catalog(s);assert.notEqual(H.corpusHash(r),H.corpusHash(r.map((x,i)=>i?x:{...x,url:'https://different.example/'})));});
test('controlled skill publication changes the next retrieval config, then rollback restores it',()=>{
 const s=O.initial(),r=catalog(s),row=H.propose(s,Presets.apply('coverage',H.DEFAULT),'admin',r,'operator-preset:coverage');
 assert.equal(H.state(s).active.topK,8);H.publish(s,row.id,row.hash,'admin',r);assert.equal(H.state(s).active.topK,10);
 const retrieval=require('./rag').retrieve('上海地铁怎么买票',r,{...H.state(s).active,city:'Shanghai'});
 assert.ok(retrieval.hits.length>0&&retrieval.hits.length<=10);assert.equal(H.state(s).active.version,'skill-'+row.id);
 H.rollback(s,row.id,'admin');assert.equal(H.state(s).active.topK,8);
});
