/* Persistent web-call controller. Recognition stays available while a reply is playing. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelVoice=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const normalize=text=>String(text||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
// Browser AEC is the first defence. Text checks reject our current playback;
// this is deliberately not represented as speaker identification.
function isEcho(text,spoken){const a=normalize(text),b=normalize(spoken);if(a.length<3||!b)return false;if(b.includes(a))return true;if(a.length<7)return false;const grams=s=>new Set(Array.from({length:Math.max(0,s.length-1)},(_,i)=>s.slice(i,i+2))),x=grams(a),y=grams(b);return [...x].filter(g=>y.has(g)).length/x.size>=.9;}
function interruptible(text,accept){return normalize(text).length>=4&&accept(String(text||'').trim());}
class Call {
 constructor(o={}){this.acceptText=o.acceptText||(()=>true);this.onRejected=o.onRejected||(()=>{});this.onInputStart=o.onInputStart||(()=>{});this.silenceMs=Math.max(1500,Math.min(5000,Number(o.silenceMs)||2600));this.localOnly=Boolean(o.localOnly);this.Recognition=o.Recognition||globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;this.synth=o.synthesis||globalThis.speechSynthesis;this.Utterance=o.Utterance||globalThis.SpeechSynthesisUtterance;this.onText=o.onText||(()=>{});this.onState=o.onState||(()=>{});this.onCaption=o.onCaption||(()=>{});this.onDraft=o.onDraft||(()=>{});this.pendingInterim='';this.active=false;this.muted=false;this.output=true;this.phase='idle';this.epoch=0;this.playbackEpoch=0;this.rec=null;this.timer=null;this.speechTimer=null;this.language='en-US';this.retry=0;this.startedAt=null;this.segments=[];}
 deliver(text){const value=String(text||'').trim();this.pendingInterim='';this.cancel();if(!this.acceptText(value)){this.onRejected(value);this.listen();return false;}this.emit('processing');this.onText(value);if(this.active&&!this.muted&&!this.rec)this.listen({mode:'processing'});return true;}
 emit(phase,detail=''){this.phase=phase;this.onState({phase,detail,active:this.active,muted:this.muted,output:this.output,supported:Boolean(this.Recognition),startedAt:this.startedAt});}
 start({consent=false,language='en-US'}={}){if(!consent)throw Error('MICROPHONE_CONSENT_REQUIRED');this.stop();this.language=language;this.active=true;this.muted=false;this.retry=0;this.startedAt=Date.now();this.emit('connecting');}
 stopPlayback(){this.playbackEpoch++;clearTimeout(this.speechTimer);this.speechTimer=null;this.speaking=false;this.echoUntil=Date.now()+650;try{this.synth?.cancel();}catch(_){} }
 cancel({preserveInterim=false}={}){if(preserveInterim&&this.pendingInterim.trim())this.onDraft(this.pendingInterim.trim());this.pendingInterim='';this.segments=[];this.currentFinal='';this.currentPartial='';this.inputNotified=false;this.finalizing=false;this.endpointDue=0;this.epoch++;clearTimeout(this.timer);clearTimeout(this.phraseTimer);clearTimeout(this.finalTimer);this.timer=null;this.phraseTimer=null;const r=this.rec;this.rec=null;if(r){r.onend=null;r.onresult=null;r.onerror=null;r.onstart=null;try{r.abort();}catch(_){}}this.stopPlayback();this.onCaption('');}
 endpointMs(){return /(?:然后|还有|以及|但是|因为|比如|我想|我要|从|到|and|because|with|from|to)\s*[，,、]?$/i.test(this.pendingInterim)?Math.max(this.silenceMs,4200):this.silenceMs;}
 scheduleEndpoint(preserve=false){clearTimeout(this.phraseTimer);const token=this.epoch;if(!preserve||!this.endpointDue)this.endpointDue=Date.now()+this.endpointMs();this.phraseTimer=setTimeout(()=>{if(this.active&&!this.muted&&token===this.epoch)this.finish();},Math.max(0,this.endpointDue-Date.now()));}
 observe(text){const value=String(text||'').trim();if(!value)return false;if((this.speaking||Date.now()<this.echoUntil)&&isEcho(value,this.spokenText))return false;const meaningful=interruptible(value,this.acceptText);if(this.speaking&&!this.inputNotified&&!meaningful)return false;if(!this.inputNotified&&meaningful){this.inputNotified=true;if(this.speaking){this.stopPlayback();this.emit('listening','听到你的补充，已暂停播报；请继续说。');}this.onInputStart(value);}return true;}
 speak(text){this.cancel({preserveInterim:true});if(!this.active)return;if(!this.output||!this.synth||!this.Utterance){this.listen();return;}const u=new this.Utterance(String(text));u.lang=this.outputLanguage||this.language;if(this.localOnly){const voice=this.synth.getVoices?.().find(v=>v.localService&&v.lang.toLowerCase().startsWith(u.lang.slice(0,2).toLowerCase()));if(!voice){this.output=false;this.emit('audio_error','本机没有对应语言的朗读声音，已保留文字；可在系统设置安装语音包。');this.listen();return;}u.voice=voice;}u.rate=this.rate||.92;this.spokenText=String(text);this.speaking=true;this.echoUntil=Infinity;this.listen({mode:'speaking'});const playback=++this.playbackEpoch;this.emit('speaking','正在播报，也在听你；直接说出补充即可插话。');let finished=false;const finish=()=>{if(finished||!this.active||playback!==this.playbackEpoch)return;finished=true;clearTimeout(this.speechTimer);this.speaking=false;this.echoUntil=Date.now()+650;if(!this.rec)this.listen();else this.emit('listening');};u.onend=finish;u.onerror=()=>{if(playback!==this.playbackEpoch)return;this.emit('audio_error','Playback unavailable; use the visible text.');finish();};this.speechTimer=setTimeout(()=>{if(playback!==this.playbackEpoch)return;this.synth.cancel();finish();},Math.max(15000,text.length*160));this.synth.speak(u);}
 listen({mode='listening',preserve=false}={}){if(!this.active||this.muted){if(this.active)this.emit('muted');return;}if(!this.Recognition){this.emit('unavailable','Speech recognition is not supported here. Text and choices still work.');return;}if(this.rec){this.emit(mode);return;}if(!preserve){this.segments=[];this.pendingInterim='';this.inputNotified=false;}this.listeningMode=mode;this.currentFinal='';this.currentPartial='';const token=++this.epoch,r=new this.Recognition(),slots=new Map();this.rec=r;r.lang=this.language;r.continuous=true;r.interimResults=true;let failed=false;
  const collect=()=>{const entries=[...slots.entries()].sort((a,b)=>a[0]-b[0]).map(x=>x[1]);this.currentFinal=entries.filter(x=>x.final).map(x=>x.text).join(' ');this.currentPartial=entries.filter(x=>!x.final).map(x=>x.text).join(' ');this.pendingInterim=[...this.segments,this.currentFinal,this.currentPartial].filter(Boolean).join('\n');};
  r.onstart=()=>{if(this.active&&token===this.epoch)this.emit(this.speaking?'speaking':mode);};
  r.onresult=e=>{if(!this.active||this.muted||token!==this.epoch)return;let changed=false;for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0]?.transcript||'';if(this.observe(text)){slots.set(i,{text:text.trim(),final:e.results[i].isFinal});changed=true;}else slots.delete(i);}collect();this.onCaption(this.pendingInterim);if(changed){this.retry=0;this.scheduleEndpoint();}};
  r.onerror=e=>{if(token!==this.epoch||!this.active||e.error==='aborted')return;if(e.error==='no-speech')return;failed=true;this.rec=null;this.cancel({preserveInterim:true});this.muted=true;this.emit(e.error==='not-allowed'||e.error==='service-not-allowed'?'permission_denied':'voice_error','Microphone/service: '+e.error+'. Resume explicitly or use text.');};
  r.onend=()=>{if(token!==this.epoch||!this.active||failed||this.muted)return;this.rec=null;if(this.currentPartial&&this.finalizing){this.cancel({preserveInterim:true});this.listen();return;}if(this.currentFinal)this.segments.push(this.currentFinal);if(this.currentPartial)this.onDraft(this.currentPartial);this.currentFinal='';this.currentPartial='';this.pendingInterim=this.segments.join('\n');if(this.finalizing){this.finish();return;}const hasWords=Boolean(this.pendingInterim);this.timer=setTimeout(()=>{if(token!==this.epoch||!this.active||this.muted)return;this.listen({mode:this.speaking?'speaking':this.phase==='processing'?'processing':'listening',preserve:true});if(hasWords)this.scheduleEndpoint(true);},180);};
  try{r.start();this.emit(this.speaking?'speaking':mode);}catch(e){this.rec=null;this.muted=true;this.emit('voice_error',e.message);}
 }
 finish(){if(!this.active||this.muted)return;clearTimeout(this.phraseTimer);if(this.currentPartial&&this.rec?.stop&&!this.finalizing){this.finalizing=true;const token=this.epoch;this.rec.stop();if(token!==this.epoch||!this.finalizing)return;this.finalTimer=setTimeout(()=>{if(this.active&&token===this.epoch){this.cancel({preserveInterim:true});this.listen();}},5000);return;}const final=[...this.segments,this.currentFinal].filter(Boolean).join('\n');if(final)this.deliver(final);else if(this.pendingInterim){this.cancel({preserveInterim:true});this.listen();}else if(this.finalizing){this.cancel();this.listen();}}
 listenWhileProcessing(){if(this.active&&!this.muted)this.listen({mode:'processing'});}
 interruptAndListen(){if(!this.active)return;this.cancel({preserveInterim:true});this.muted=false;this.retry=0;this.listen();}
 mute(value=true){this.muted=value;if(value){this.cancel({preserveInterim:true});this.emit('muted');}else this.interruptAndListen();}
 setOutput(value){this.output=value;if(!value){this.stopPlayback();if(this.active){if(!this.rec)this.listen();else this.emit('listening');}}else this.emit(this.phase);}
 stop(){this.active=false;this.cancel();this.muted=false;this.startedAt=null;this.emit('ended');}
}
return{Call,isEcho,interruptible};
});
