/* A persistent web-call controller, not PSTN or a full-duplex media service. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.TravelVoice=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
class Call {
 constructor(o={}){this.localOnly=Boolean(o.localOnly);this.Recognition=o.Recognition||globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;this.synth=o.synthesis||globalThis.speechSynthesis;this.Utterance=o.Utterance||globalThis.SpeechSynthesisUtterance;this.onText=o.onText||(()=>{});this.onState=o.onState||(()=>{});this.onCaption=o.onCaption||(()=>{});this.onDraft=o.onDraft||(()=>{});this.pendingInterim="";this.active=false;this.muted=false;this.output=true;this.phase='idle';this.epoch=0;this.rec=null;this.timer=null;this.speechTimer=null;this.language='en-US';this.retry=0;this.startedAt=null;}
 emit(phase,detail=''){this.phase=phase;this.onState({phase,detail,active:this.active,muted:this.muted,output:this.output,supported:Boolean(this.Recognition),startedAt:this.startedAt});}
 start({consent=false,language='en-US'}={}){if(!consent)throw Error('MICROPHONE_CONSENT_REQUIRED');this.stop();this.language=language;this.active=true;this.muted=false;this.retry=0;this.startedAt=Date.now();this.emit('connecting');}
 cancel({preserveInterim=false}={}){if(preserveInterim&&this.pendingInterim.trim())this.onDraft(this.pendingInterim.trim());this.pendingInterim="";this.epoch++;clearTimeout(this.timer);clearTimeout(this.speechTimer);this.timer=null;this.speechTimer=null;const r=this.rec;this.rec=null;if(r){r.onend=null;r.onresult=null;r.onerror=null;try{r.abort();}catch(_){}}try{this.synth?.cancel();}catch(_){}this.onCaption('');}
 speak(text){this.cancel();if(!this.active)return;const token=this.epoch;if(!this.output||!this.synth||!this.Utterance){this.listen();return;}const u=new this.Utterance(String(text));u.lang=this.outputLanguage||this.language;if(this.localOnly){const voice=this.synth.getVoices?.().find(v=>v.localService&&v.lang.toLowerCase().startsWith(u.lang.slice(0,2).toLowerCase()));if(!voice){this.output=false;this.emit('audio_error','本机没有对应语言的朗读声音，已保留文字；可在系统设置安装语音包。');this.listen();return;}u.voice=voice;}u.rate=this.rate||.92;this.emit('speaking');let finished=false;const finish=()=>{if(finished||!this.active||token!==this.epoch)return;finished=true;clearTimeout(this.speechTimer);this.listen();};u.onend=finish;u.onerror=()=>{if(token!==this.epoch)return;this.emit('audio_error','Playback unavailable; use the visible text.');finish();};this.speechTimer=setTimeout(()=>{if(token!==this.epoch)return;this.synth.cancel();finish();},Math.max(15000,text.length*160));this.synth.speak(u);}
 listen(){if(!this.active||this.muted){if(this.active)this.emit('muted');return;}if(!this.Recognition){this.emit('unavailable','Speech recognition is not supported here. Text and choices still work.');return;}
  const token=++this.epoch,r=new this.Recognition();this.rec=r;r.lang=this.language;r.continuous=false;r.interimResults=true;let sent=false,failed=false;
  r.onstart=()=>{if(this.active&&token===this.epoch)this.emit('listening');};
  r.onresult=e=>{if(!this.active||this.muted||token!==this.epoch||sent)return;let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)final+=text;else interim+=text;}this.pendingInterim=final.trim()?'':interim;this.onCaption(final||interim);if(final.trim()){sent=true;this.retry=0;this.rec=null;try{r.abort();}catch(_){}this.emit('processing');this.onText(final.trim());}};
  r.onerror=e=>{if(token!==this.epoch||!this.active)return;if(e.error==='aborted')return;failed=true;this.rec=null;this.muted=true;this.emit(e.error==='not-allowed'||e.error==='service-not-allowed'?'permission_denied':'voice_error','Microphone/service: '+e.error+'. Resume explicitly or use text.');};
  r.onend=()=>{if(token!==this.epoch||!this.active||sent||failed||this.muted)return;this.rec=null;if(++this.retry>3){this.muted=true;this.emit('muted','No speech detected. Resume when ready.');return;}this.emit('waiting');this.timer=setTimeout(()=>this.listen(),700);};
  try{r.start();this.emit('listening');}catch(e){this.rec=null;this.muted=true;this.emit('voice_error',e.message);}
 }
 finish(){if(this.phase==='listening')try{this.rec?.stop();}catch(_){} }
 interruptAndListen(){if(!this.active)return;this.cancel();this.muted=false;this.retry=0;this.listen();}
 mute(value=true){this.muted=value;if(value){const r=this.rec;this.rec=null;this.epoch++;clearTimeout(this.timer);clearTimeout(this.speechTimer);try{r?.abort();this.synth?.cancel();}catch(_){}this.onCaption('');this.emit('muted');}else this.interruptAndListen();}
 setOutput(value){this.output=value;if(!value){this.cancel();if(this.active)this.listen();}else this.emit(this.phase);}
 stop(){this.active=false;this.cancel();this.muted=false;this.startedAt=null;this.emit('ended');}
}
return{Call};
});
