(function(g,f){const x=f();if(typeof module==='object')module.exports=x;else g.Arrival5Voice=x;})(globalThis,function(){
'use strict';
class Voice {
 constructor(o={}){this.Recognition=o.Recognition||globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;this.synth=o.synth||globalThis.speechSynthesis;this.Utterance=o.Utterance||globalThis.SpeechSynthesisUtterance;this.onState=o.onState||(()=>{});this.onText=o.onText||(()=>{});this.turn=o.turn|| (async()=> '');this.cancelTurn=o.cancelTurn||(()=>{});this.active=false;this.seq=0;this.rec=null;this.finish=null;this.language='en-US';this.auto=true;}
 state(name,detail=''){this.onState({name,detail,active:this.active});}
 cleanup(){if(this.rec){this.rec.onend=null;this.rec.onerror=null;this.rec.abort();this.rec=null;}this.synth?.cancel();this.finish?.();this.finish=null;}
 async start({consent=false,language='en-US',greeting='',auto=true}={}){if(!consent){this.state('consent_required');return false;}if(!this.Recognition||!this.synth||!this.Utterance){this.state('unsupported','Use typing or device keyboard dictation.');return false;}this.stop();this.active=true;this.language=language;this.auto=auto;const id=++this.seq;await this.say(greeting);if(this.active&&this.seq===id)this.listen();return true;}
 say(text){return new Promise(resolve=>{if(!this.active||!text){resolve();return;}this.cleanup();this.state('speaking');const u=new this.Utterance(String(text).slice(0,900));u.lang=this.language;u.rate=1;let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(timer);this.finish=null;resolve();};this.finish=finish;u.onend=finish;u.onerror=()=>{this.state('speech_error','Read the transcript instead.');finish();};const timer=setTimeout(()=>{this.synth.cancel();finish();},30000);this.synth.speak(u);});}
 listen(){if(!this.active)return;this.cleanup();const id=this.seq,r=new this.Recognition();this.rec=r;r.lang=this.language;r.continuous=false;r.interimResults=true;let final='',failed=false;this.state('listening');r.onresult=e=>{let partial='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t;else partial+=t;}this.onText({text:final||partial,final:!!final});};r.onerror=e=>{failed=true;this.active=false;this.state(e.error==='not-allowed'?'permission_denied':'recognition_error',e.error);};r.onend=async()=>{if(this.rec===r)this.rec=null;if(failed||!this.active||id!==this.seq)return;if(!final.trim()){this.state('paused','No speech received; press Resume.');return;}if(!this.auto){this.state('review_transcript','Edit the transcript and press Send.');return;}this.state('working');try{const answer=await this.turn(final.trim());if(!this.active||id!==this.seq)return;await this.say(answer);if(this.active&&id===this.seq)this.listen();}catch(e){if(this.active)this.state('paused','Request failed; use typing or resume.');}};try{r.start();}catch(e){this.active=false;this.state('recognition_error',e.message);}}
 interrupt(){if(!this.active)return;this.seq++;this.cancelTurn();this.cleanup();this.listen();}
 pause(){if(!this.active)return;this.seq++;this.cancelTurn();this.cleanup();this.state('paused');}
 resume(){if(!this.active)return;this.seq++;this.listen();}
 stop(){this.active=false;this.seq++;this.cancelTurn();this.cleanup();this.state('idle');}
}
return {Voice};});
