'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Call,isEcho}=require('./voice'),E=require('./engine');
function rig(t){t.mock.timers.enable({apis:['setTimeout','Date']});const texts=[],drafts=[],starts=[],captions=[],recognizers=[],spoken=[];class Recognition{constructor(){recognizers.push(this);}start(){this.onstart?.();}stop(){this.onend?.();}abort(){this.onend?.();}}class Utterance{constructor(text){this.text=text;}}const synth={count:0,cancel(){this.count++;},speak(u){spoken.push(u);}};const call=new Call({Recognition,Utterance,synthesis:synth,acceptText:x=>E.speechDecision(x,E.state(),true).accepted,onText:x=>texts.push(x),onDraft:x=>drafts.push(x),onInputStart:x=>starts.push(x),onCaption:x=>captions.push(x)});call.start({consent:true,language:'zh-CN'});t.after(()=>call.stop());return {call,texts,drafts,starts,captions,recognizers,spoken,synth,tick:ms=>t.mock.timers.tick(ms)};}
const row=(text,final=true)=>Object.assign([{transcript:text}],{isFinal:final});
function result(rec,rows,index=0){rec.onresult({resultIndex:index,results:rows});}
test('three natural phrase boundaries produce one complete turn after the last pause',t=>{const r=rig(t);r.call.listen();const rec=r.call.rec;result(rec,[row('我想从浦东机场出发')]);r.tick(1800);assert.equal(r.texts.length,0);result(rec,[row('我想从浦东机场出发'),row('然后去上海火车站')],1);r.tick(1800);assert.equal(r.texts.length,0);result(rec,[row('我想从浦东机场出发'),row('然后去上海火车站'),row('请帮我看看地铁路线')],2);r.tick(3199);assert.equal(r.texts.length,0);r.tick(1);assert.deepEqual(r.texts,['我想从浦东机场出发 然后去上海火车站 请帮我看看地铁路线']);assert.equal(r.starts.length,1);assert.ok(r.call.rec,'microphone remains listening during thinking');assert.equal(r.call.phase,'processing');});
test('unfinished conjunction waits longer without weakening the one-character gate',t=>{const r=rig(t);r.call.listen();result(r.call.rec,[row('我想去上海然后')]);r.tick(3000);assert.equal(r.texts.length,0);r.tick(1200);assert.equal(r.texts.length,0);assert.deepEqual(r.drafts,['我想去上海然后']);result(r.call.rec,[row('啊')]);r.tick(3200);assert.equal(r.texts.length,0);});
test('browser recognition restart preserves complete phrases and their silence deadline',t=>{const r=rig(t);r.call.listen();const first=r.call.rec;result(first,[row('我想去上海旅游')]);r.tick(1000);first.onend();r.tick(180);assert.notEqual(r.call.rec,first);r.call.rec.onend();r.tick(180);r.tick(1840);assert.deepEqual(r.texts,['我想去上海旅游']);});
test('new phrase after browser restart joins the same turn',t=>{const r=rig(t);r.call.listen();result(r.call.rec,[row('我想去上海旅游')]);r.call.rec.onend();r.tick(180);result(r.call.rec,[row('带着父母和一个孩子')]);r.tick(3200);assert.deepEqual(r.texts,['我想去上海旅游\n带着父母和一个孩子']);});
test('playback cannot open browser recognition or accept delayed echo callbacks',t=>{const r=rig(t);r.call.listen();const late=r.call.rec.onresult;r.call.speak('请从浦东机场乘坐二号线到人民广场。');assert.equal(r.call.rec,null);late({resultIndex:0,results:[row('请从浦东机场乘坐二号线到人民广场')]});r.tick(4000);assert.equal(r.texts.length,0);assert.equal(r.starts.length,0);r.spoken[0].onend();r.tick(699);assert.equal(r.call.rec,null);r.tick(1);assert.ok(r.call.rec);assert.equal(r.call.phase,'listening');});
test('explicit interruption preserves user correction and invalidates playback callback',t=>{const r=rig(t);r.call.speak('从浦东机场出发');const done=r.spoken[0].onend;r.call.interruptAndListen();result(r.call.rec,[row('不对，我其实从虹桥机场出发')]);r.tick(3200);assert.deepEqual(r.texts,['不对，我其实从虹桥机场出发']);done();assert.equal(r.call.phase,'processing');});
test('browser partial-only end submits a complete meaningful utterance after patience window',t=>{const r=rig(t);r.call.listen();result(r.call.rec,[row('上海火车站附近有充电宝吗',false)]);r.call.rec.onend();r.tick(180);r.tick(3020);assert.deepEqual(r.texts,['上海火车站附近有充电宝吗']);});
test('turns spoken during processing are accepted without pressing interrupt',t=>{const r=rig(t);r.call.listenWhileProcessing();result(r.call.rec,[row('我还希望步行少一点')]);r.tick(3200);assert.deepEqual(r.texts,['我还希望步行少一点']);assert.equal(r.starts.length,1);});
test('unfinalized words are retained as a draft and never treated as committed facts',t=>{const r=rig(t);r.call.listen();result(r.call.rec,[row('我想从上海到',false)]);r.tick(4200);assert.deepEqual(r.texts,[]);assert.deepEqual(r.drafts,['我想从上海到']);assert.equal(r.call.phase,'listening');assert.ok(r.call.rec);});
test('mute and hangup invalidate pending phrase timers and late results',t=>{const r=rig(t);r.call.listen();const rec=r.call.rec,late=rec.onresult;result(rec,[row('我想去上海旅游')]);r.call.mute();r.tick(6000);assert.deepEqual(r.texts,[]);assert.deepEqual(r.drafts,['我想去上海旅游']);r.call.stop();late({resultIndex:0,results:[row('上海旅游')]});r.tick(6000);assert.deepEqual(r.texts,[]);assert.equal(r.call.active,false);});
test('echo match is conservative about genuinely different requirements',()=>{assert.equal(isEcho('地铁二号线到人民广场','从浦东机场乘坐地铁二号线到人民广场。'),true);assert.equal(isEcho('不是这个，我要去虹桥机场','从浦东机场乘坐地铁二号线到人民广场。'),false);assert.equal(isEcho('我想用 JCB 银行卡刷地铁','使用公共交通前可以先查询路线。'),false);});
