/* No keys or customer documents are stored in browser persistence. */
'use strict';
const D=window.ArrivalData,C=window.ArrivalCore,corpus=window.ArrivalCorpus||[];
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let server=false,admin=false,view='chat',revision=0,messages=[],draft=null,nodes=[],pending=false,controller=null,confirmation=null,progress='',status={},sourceCache=new Map(),events=[],roleDemo=false,access='',voice=null;
const allSources=()=>[...D.sources,...corpus.filter(r=>!D.sources.some(s=>s.url===r.url)).map(r=>({...r,kind:r.source_kind}))];
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}
function download(name,data,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
async function request(url,body,signal){const r=await fetch(url,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Demo-Access':access},body:body===undefined?undefined:JSON.stringify(body),signal});const x=await r.json();if(!r.ok)throw Error(x.error||'HTTP_'+r.status);return x;}
function localEvent(type,extra={}){events.push({type,at:new Date().toISOString(),...extra});}
function phase(n=0){return '<div class="phase">'+['1 · 整理需求','2 · 你来确认','3 · 查验来源','4 · 节点计划'].map((s,i)=>'<span class="'+(i<=n?'on':'')+'">'+s+'</span>').join('')+'</div>';}
function welcome(){return '<section class="welcome"><span class="orb">✧</span><h1>先聊聊，你现在需要什么？</h1><p>不用一次说完，也不用填一整页表格。<br>我会整理需求，等你确认，再找到每一步的依据。</p></section><div class="examples"><button class="example" data-sample="我刚到上海浦东机场T2公共到达厅，需要换人民币、开通网络，再坐地铁去酒店。"><em>↗</em>从落地到酒店<small>机场 · 换汇 · 通信 · 交通</small></button><button class="example" data-sample="I have booked my flight to Shanghai, but not my hotel. I need a train guide and want to understand WeChat and Alipay fees."><em>◈</em>把准备事项说给我<small>酒店 · 火车 · 支付规则</small></button><button class="example" data-sample="我在北京机场，手机电量3%，网络很差，不知道先做什么。"><em>⚡</em>我现在遇到困难<small>低电量 · 弱网 · 现场求助</small></button></div><div class="how"><span><b>01</b>说清需求</span><span><b>02</b>确认优先级</span><span><b>03</b>带出处的下一步</span></div><p class="muted" style="text-align:center;margin-top:26px">官方索引 ≠ 全部已经人工核实。每张计划卡都会说明证据状态。</p>';}
function chatView(){let h=messages.length?messages.map(m=>'<div class="message user">'+esc(m.text)+'</div>').join(''):welcome();if(draft){h+='<div class="assistant-label">VISIT CHINA · '+esc(draft.mode==='deepseek-proposed'?'DEEPSEEK REQUIREMENTS':'DEFAULT REQUIREMENTS')+'</div>'+phase(nodes.length?3:pending?2:1);if(draft.battery!==null&&draft.battery<=5)h+='<div class="help">我的手机快没电了。请问您能帮我找到可以求助的服务台吗？<p class="muted">不再加载图片或调用模型。请在关机前向眼前工作人员出示。</p></div>';h+='<section class="draft"><h2>我理解你有这几件事要做</h2><p>'+esc(draft.summary)+'</p><div class="bar"><span class="status-pill">'+esc([draft.city,draft.location?.airport==='Unknown'?'':draft.location?.airport,draft.location?.terminal,draft.location?.zone].filter(Boolean).join(' · '))+'</span><span class="muted">需求版本 '+draft.revision+' · '+(server?'当前服务端会话':'仅浏览器演示')+'</span></div>'+draft.needs.map((n,i)=>'<label class="need"><input type="checkbox" data-need="'+esc(n.id)+'" '+(n.selected!==false?'checked':'')+'><strong>'+(i+1)+'</strong><span>'+esc(n.text)+'</span></label>').join('');if(draft.missing?.length)h+='<p><b>还需要确认：</b>'+esc(draft.missing[0])+'</p><div class="chips"><button data-sample="我先到上海">上海</button><button data-sample="我先到北京">北京</button><button data-sample="我还没有确定，先给通用准备建议">还没确定</button></div>';h+='<div class="bar"><button class="primary" id="confirm" '+(pending?'disabled':'')+'>确认这些需求，生成下一步 ↗</button><button id="add-needs">继续补充／纠正</button></div><p class="muted">可以取消不需要的事项。你提供的已订信息不等于供应商确认的真实订单。</p></section>';}
 if(progress)h+='<div class="progress" role="status">'+esc(progress)+'</div>';h+=nodes.map(nodeHTML).join('');if(nodes.length)h+='<div class="bar"><button id="export-plan">导出计划与出处</button><button id="email-draft">生成行前邮件草稿</button><span class="muted">没有自动发送，也没有执行预订。</span></div>';return h;}
function nodeHTML(n){const evid=n.evidence||[];for(const e of evid)sourceCache.set(e.id,e);return'<section class="node" id="node-'+esc(n.id)+'"><div class="node-top"><span class="status-pill '+(n.audit.evidence_coverage==='evidence_gap'?'warning':'')+'">'+esc(n.mode==='deepseek-grounded'?'DeepSeek · 依据原文生成':n.audit.evidence_coverage==='evidence_gap'?'依据不足 · 保留求助路径':'已核对摘要 · 非实时保证')+'</span><span class="muted">'+esc(n.id.toUpperCase())+'</span></div><h3>'+esc(n.title)+'</h3><p class="rationale">安排理由：'+esc(n.rationale)+'</p><ol>'+n.actions.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol><p class="muted">'+esc(n.uncertainty)+'</p><div class="sources">'+n.source_ids.map(id=>{const s=evid.find(x=>x.id===id)||allSources().find(x=>x.id===id);return'<button class="source-pill" data-source="'+esc(id)+'">▤ '+esc(s?.title||id)+' ↗</button>';}).join('')+'</div>'+(n.notice?'<p class="muted warning-text">模型回退：'+esc(n.notice)+'</p>':'')+'<details class="audit"><summary>查看本节点的来源检查记录 · 不等于准确率评分</summary><pre>'+esc(JSON.stringify(n.audit,null,2))+'</pre></details><div class="outcomes"><button data-outcome="done" data-node="'+esc(n.id)+'">'+(n.outcome==='done'?'✓ ':'')+'这一步已完成</button><button data-outcome="blocked" data-node="'+esc(n.id)+'">'+(n.outcome==='blocked'?'✓ ':'')+'仍然卡住了</button></div></section>';}
function sourceDetails(id){const r=sourceCache.get(id)||allSources().find(x=>x.id===id);if(!r)return toast('未找到这条来源');const title=r.title||id;const summary=r.summaryZh||r.summary||r.excerpt||'只有索引，尚未获取可用于回答的正文。';let h='<button class="quiet" id="close-evidence">关闭 ×</button><span class="eyebrow" style="display:block;margin-top:22px">SOURCE RECORD / 原始依据</span><h2>'+esc(title)+'</h2><span class="status-pill '+(!r.reviewedAt?'warning':'')+'">'+esc(r.kind||r.source_kind||'unknown')+'</span><p>'+esc(summary)+'</p><dl class="meta"><dt>发布者</dt><dd>'+esc(r.publisher)+'</dd><dt>发布日期</dt><dd>'+esc(r.published||r.publication_date||'未标明')+'</dd><dt>编辑核对</dt><dd>'+esc(r.reviewedAt||'尚未核对')+'</dd><dt>抓取／检查</dt><dd>'+esc(r.checkedAt||r.retrieved_at||'本次未请求')+'</dd><dt>运行状态</dt><dd>'+esc(r.liveStatus||'索引／摘要，非实时')+'</dd><dt>原文哈希</dt><dd>'+esc(r.content_sha256||'未在本机抓取，不伪造')+'</dd></dl><p class="muted">自动检查仅验证地址、抓取状态和部分关键字段；不证明内容仍然有效，也不证明模型结论全部正确。</p><a class="source-pill" href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">打开发布者完整原文 ↗</a>';
 const media=r.media||[];if(media.length){h+='<div class="panel"><h2>现场照片与图示</h2><p>从发布者网站按需加载，不是实时画面。可能含第三方版权，未重新分发。</p>';media.forEach((m,i)=>{h+='<button data-photo="'+esc(id)+'" data-photo-index="'+i+'">加载官方图片 '+(i+1)+'</button><div id="photo-'+i+'"></div>';});h+='</div>';}
 if(id==='wechat-fee')h+='<div class="panel"><h2>微信基础手续费演算</h2><p>不是支付宝报价，不包含个人优惠和发卡行费用。</p><input type="number" id="fee-amount" value="201" min="0" step="0.01" aria-label="金额"><button id="calc-fee">计算</button><p id="fee-result"></p></div>';$('#evidence').innerHTML=h;$('#evidence').classList.remove('hidden');}
function sourceLibrary(){return'<div class="section-head"><h1>每一步，都能回到原始依据。</h1><p>抓取成功的页面、编辑核对的摘要、当前可执行的服务事实，是三个不同层次。<br>索引包含目的地和历史活动信息，不能全部称为现行官方指引。</p></div><div class="metrics"><div class="metric"><span>去重的官方页面索引</span><b>'+corpus.length.toLocaleString()+'</b><small>一页一条；不按切片凑数</small></div><div class="metric"><span>本版本核对的来源卡</span><b>'+D.sources.length+'</b><small>仍有日期、适用范围和资料缺口</small></div><div class="metric"><span>全部官方规则人工核实</span><b>未完成</b><small>不能把自动抓取冒充审核通过</small></div></div><div class="searchbar"><input id="source-query" placeholder="试试 airport / metro / currency / museum / train"><select id="source-city"><option value="Unknown">全部城市</option><option>Shanghai</option><option>Beijing</option></select><button id="search-sources">搜索索引</button></div><div id="source-results">'+recordsHTML(D.sources)+'</div>';}
function recordsHTML(rows){return rows.length?rows.map(r=>{sourceCache.set(r.id,r);return'<div class="record"><div><h3>'+esc(r.title)+'</h3><p>'+esc(r.publisher)+' · '+esc(r.city)+' · '+esc(r.published||r.publication_date||'日期未标明')+'</p><p>'+esc((r.topics||[]).join(' / '))+' · '+(r.reviewedAt?'短摘要已核对':'内容待审核，不能直接作为现行规则')+'</p></div><button data-source="'+esc(r.id)+'">查看依据</button></div>';}).join(''):'<div class="empty">未找到匹配记录。不要从没有命中的资料中编造答案。</div>';}
function researchView(){return'<div class="section-head"><h1>把真实问题和权威答案分开。</h1><p>公开经验用于发现需求，不用于覆盖支付规则、入境资格或服务条款。<br>未抓取受限的小红书／X 内容；未训练这些数据，也未获得竞赛成绩。</p></div><h2 style="font-size:17px;margin-top:25px">公开经验线索</h2><div class="research-grid">'+D.leads.map(r=>'<div class="panel"><span class="eyebrow">'+esc(r.platform)+'</span><h2 style="margin-top:12px">'+esc(r.title)+'</h2><p>'+esc(r.summary)+'</p><p>'+esc(r.status)+'</p><a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">查看原始页面 ↗</a></div>').join('')+'</div><h2 style="font-size:17px;margin-top:30px">评测数据与公开基准</h2>'+D.benchmarks.map(r=>'<div class="panel"><h2>'+esc(r.name)+'</h2><p>'+esc(r.use)+'</p><a href="'+esc(r.url)+'" target="_blank" rel="noopener noreferrer">论文／数据入口 ↗</a></div>').join('');}
function loginView(){return'<div class="section-head"><h1>Operations</h1><p>管理模型连接、来源启停和本次运行记录。</p></div><div class="panel"><h2>'+(server?'本机管理员登录':'浏览器演示角色')+'</h2>'+(server?'<label>用户名</label><input id="username" value="admin" autocomplete="username"><label>密码</label><input id="password" type="password" placeholder="初始演示密码 demo2026" autocomplete="current-password"><div class="bar"><button class="primary" id="login">登录</button></div>':'<p>单文件不能安全保存或调用带 Key 的模型。请运行 Node 服务后配置 DeepSeek；此处只是角色演示。</p><button id="demo-role">进入浏览器演示角色</button>')+'<p id="login-error" class="warning-text"></p></div>';}
function operationsView(){if(!admin&&!roleDemo)return loginView();return'<div class="section-head"><h1>从一次回答，到一次可复核的服务。</h1><p>'+(server?'服务端管理员模式；Key仅保存在进程内存或服务端环境变量。':'浏览器模拟角色；不具备服务端权限，不接触真实 Key。')+'</p></div><div class="metrics" id="ops-metrics"></div><section class="panel"><h2>DeepSeek · 对外连接</h2><p>本版接入需求整理与带证据的节点生成，不再仅用于分类。配置不等于完成真实联调；Token 来自供应商回执，非余额。</p><label>API Key（提交后清空，不写入浏览器存储）</label><input type="password" id="api-key" autocomplete="off" '+(!server?'disabled':'')+' placeholder="只在本机填写"><label>模型</label><select id="model-name"><option>deepseek-flash</option><option>deepseek-v4-pro</option></select><label>每次调用最大输出 Tokens</label><input id="max-tokens" type="number" min="400" max="4000" value="1600"><div class="bar"><button id="save-model" class="primary" '+(!server?'disabled':'')+'>保存到服务进程</button><button id="clear-model" '+(!server?'disabled':'')+'>清除 Key</button><button id="refresh-ops">刷新运行记录</button></div><pre id="model-usage"></pre></section><section class="panel"><h2>来源治理与支付规则</h2><p>停用后新计划不再使用该来源。历史记录保留当时依据，不伪装已重新核验。</p>'+D.sources.map(r=>'<div class="record"><div><h3>'+esc(r.title)+'</h3><p>'+esc(r.risk)+' · '+esc(r.reviewedAt)+'</p></div><button data-source="'+r.id+'">详情</button><button data-toggle-source="'+r.id+'" '+(!server?'disabled':'')+'>'+(status.disabled?.includes(r.id)?'启用':'停用')+'</button></div>').join('')+'</section><section class="panel"><h2>事件记录与指标口径</h2><p>source_check 是来源检查次数；node_generated 是节点数；node_outcome 是用户反馈事件。都不是独立游客人数。完成率需要按会话＋版本＋节点去重，并处理未反馈与撤销。</p><button id="export-events">导出本次记录</button><pre id="ops-events"></pre></section><button id="logout">退出管理员</button>';}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#compose').classList.toggle('hidden',view!=='chat');$('#content').innerHTML=view==='chat'?chatView():view==='sources'?sourceLibrary():view==='research'?researchView():operationsView();$('#nav-count').textContent=corpus.length.toLocaleString();$('#mode').textContent=server?(status.model?'本机 · '+status.model:'本机 · 默认模式'):'单文件 · 离线演示';$('#connection-note').textContent=server?'调用模型需要你勾选同意。官方访问会记录失败或缓存，不伪装实时结果。':'请运行 npm start 连接外界。此文件可演示需求确认和带来源的默认计划。';$('#stop').classList.toggle('hidden',!pending);if(view==='operations'&&(admin||roleDemo))loadOps();}
async function send(text){text=String(text||'').trim();if(!text)return;controller?.abort();controller=new AbortController();const signal=controller.signal,my=++revision;messages.push({text:C.clean(text)});draft=null;nodes=[];confirmation=null;pending=true;progress='正在整理你刚补充的需求…';$('#message').value='';view='chat';render();localEvent('message_submitted',{revision:my});
 try{if(server){const out=await request('/api/draft',{message:text,modelConsent:$('#model-consent').checked},signal);if(my!==revision)return;draft=out.draft;if(!['LOCAL_RULES','DEEPSEEK_PROPOSED'].includes(out.notice))toast('保留默认处理：'+out.notice);}else{draft=C.draft(messages,my);}localEvent('draft_created',{mode:draft.mode});}catch(e){if(e.name!=='AbortError')toast('需求未完成：'+e.message);}finally{if(my===revision){pending=false;progress='';render();}}}
async function plan(){if(!draft)return;draft.needs.forEach(n=>n.selected=$('[data-need="'+n.id+'"]')?.checked!==false);const selected=draft.needs.filter(n=>n.selected).map(n=>n.id);if(!selected.length)return toast('至少保留一个需求');controller?.abort();controller=new AbortController();const signal=controller.signal,my=revision;nodes=[];pending=true;progress='需求已确认，开始检查官方依据…';render();
 try{if(server){const out=await request('/api/confirm',{revision:draft.revision,selected},signal);confirmation=out.confirmation;const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Access':access},body:JSON.stringify({confirmation,modelConsent:$('#model-consent').checked,live:$('#live-consent').checked}),signal});if(!r.ok){const e=await r.json();throw Error(e.error);}const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const next=await reader.read();buf+=decoder.decode(next.value||new Uint8Array(),{stream:!next.done});let i;while((i=buf.indexOf('\n'))>=0){const line=buf.slice(0,i);buf=buf.slice(i+1);if(!line.trim())continue;const e=JSON.parse(line);if(my!==revision)return;if(e.type==='progress')progress=e.stage==='retrieving'?'正在获取官方依据 · '+e.need:'DeepSeek 正在依据已获取的原文组织节点 · '+e.need;if(e.type==='source')sourceCache.set(e.source.id,e.source);if(e.type==='node'){nodes.push(e.node);localEvent('node_generated',{mode:e.node.mode});}if(e.type==='error')throw Error(e.error);render();}if(next.done)break;}}else{for(const need of draft.needs.filter(n=>n.selected).slice(0,draft.battery!==null&&draft.battery<=5?1:7)){const evidence=C.forNeed(need,draft,allSources()).map(r=>({...r,liveStatus:'not_requested'}));const n=C.fallbackNode(need,draft,evidence);n.audit.record_id='browser-'+Date.now()+'-'+need.id;n.audit.at=new Date().toISOString();nodes.push(n);}localEvent('plan_completed',{mode:'browser-default'});}}catch(e){if(e.name!=='AbortError')toast('计划保留已完成节点：'+e.message);}finally{if(my===revision){pending=false;progress='';render();}}}
function loadOps(){if(!server){const counts={};events.forEach(e=>counts[e.type]=(counts[e.type]||0)+1);showOps({counts,events,model:{configured:false,calls:0,totalTokens:0},officialPages:corpus.length});return;}request('/api/admin').then(showOps).catch(e=>toast(e.message));}
function showOps(x){if(!$('#ops-metrics'))return;window.lastOps=x;$('#ops-metrics').innerHTML=[['需求确认',x.counts?.requirements_confirmed||0,'按确认事件计数'],['官方访问检查',x.counts?.source_check||0,'含成功、失败和未请求'],['供应商 Token 回执',x.model?.totalTokens||0,'真实回执才累计；不是余额']].map(a=>'<div class="metric"><span>'+a[0]+'</span><b>'+a[1]+'</b><small>'+a[2]+'</small></div>').join('');$('#model-usage').textContent=JSON.stringify(x.model,null,2);$('#ops-events').textContent=JSON.stringify(x.events?.slice(-20)||[],null,2);if(x.model?.model)$('#model-name').value=x.model.model;if(x.model?.maxTokens)$('#max-tokens').value=x.model.maxTokens;}
async function refreshStatus(){if(!server)return;status=await request('/api/status');admin=status.admin;render();}
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();send($('#message').value);});$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send(e.target.value);}});$('#close-modal').onclick=()=>$('#modal').close();
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.view){view=b.dataset.view;location.hash=view;render();return;}
 if(b.dataset.sample)return send(b.dataset.sample);
 if(b.dataset.source)return sourceDetails(b.dataset.source);
 if(b.id==='close-evidence')return $('#evidence').classList.add('hidden');
 if(b.id==='confirm')return plan();if(b.id==='add-needs'){toast('在下面继续告诉我哪些需求要补充或纠正。');$('#message').focus();return;}
 if(b.id==='stop'){controller?.abort();pending=false;progress='已停止。取消后供应商仍可能对已处理部分计费。';render();return;}
 if(b.id==='new-chat'){controller?.abort();revision++;messages=[];draft=null;nodes=[];pending=false;progress='';sourceCache.clear();if(server)await request('/api/reset',{});view='chat';render();return;}
 if(b.id==='search-sources'){const q=$('#source-query').value,city=$('#source-city').value;const rows=server?(await request('/api/search?q='+encodeURIComponent(q)+'&city='+encodeURIComponent(city))).results:C.rank(q,city,allSources(),30);$('#source-results').innerHTML=recordsHTML(rows);return;}
 if(b.id==='demo-role'){roleDemo=true;render();return;}
 if(b.id==='login'){try{await request('/api/login',{username:$('#username').value,password:$('#password').value});await refreshStatus();}catch(err){$('#login-error').textContent=err.message;}return;}
 if(b.id==='logout'){if(server)await request('/api/logout',{});admin=false;roleDemo=false;render();return;}
 if(b.id==='save-model'){const input={model:$('#model-name').value,maxTokens:Number($('#max-tokens').value)};if($('#api-key').value)input.key=$('#api-key').value;await request('/api/model-config',input);$('#api-key').value='';toast('已保存到本机服务进程；没有写入浏览器或 GitHub。');await refreshStatus();return;}
 if(b.id==='clear-model'){await request('/api/model-config',{clear:true});await refreshStatus();return;}
 if(b.id==='refresh-ops')return loadOps();
 if(b.dataset.toggleSource){const id=b.dataset.toggleSource;await request('/api/source-state',{id,enabled:status.disabled?.includes(id)});await refreshStatus();return;}
 if(b.dataset.photo){if(draft?.battery!==null&&draft?.battery<=5)return toast('低电量：保留文字求助，不加载图片');const s=sourceCache.get(b.dataset.photo)||allSources().find(x=>x.id===b.dataset.photo),i=Number(b.dataset.photoIndex),m=s?.media?.[i];if(!m)return;const u=new URL(m.url);if(!['english.shanghai.gov.cn','english.beijing.gov.cn'].includes(u.hostname))return toast('请在发布者原文查看这张图');const target=$('#photo-'+i);target.innerHTML='';const im=document.createElement('img');im.alt=m.alt||'Publisher image';im.referrerPolicy='no-referrer';im.src=m.url;im.onerror=()=>{target.textContent='图片暂时无法加载，请打开官方原文查看。';};target.append(im);return;}
 if(b.id==='calc-fee'){const f=C.fee($('#fee-amount').value);$('#fee-result').textContent='微信基础服务费：¥'+f.baseFee.toFixed(2)+'；最终以支付页为准。';return;}
 if(b.dataset.outcome){const n=nodes.find(x=>x.id===b.dataset.node);if(!n)return;if(server)await request('/api/feedback',{node:n.id,outcome:b.dataset.outcome});n.outcome=b.dataset.outcome;localEvent('node_outcome',{node:n.id,outcome:n.outcome});render();return;}
 if(b.id==='export-plan'){download('arrival-plan-with-evidence.json',JSON.stringify({version:D.version,draft,nodes,notice:'Personal prototype; no bookings or live-availability guarantee'},null,2));return;}
 if(b.id==='export-events'){download('arrival-audit.json',JSON.stringify(window.lastOps||{events},null,2));return;}
 if(b.id==='email-draft'){const text='Your China arrival checklist\n\n'+nodes.map(n=>n.title+'\n'+n.actions.join('\n')+'\n'+(n.evidence||[]).map(s=>s.url).join('\n')).join('\n\n')+'\n\nDraft only. Verify current service conditions. No reservation or payment has been made.';download('arrival-email-draft.txt',text,'text/plain;charset=utf-8');toast('邮件草稿已生成；没有发送。');return;}
 if(b.id==='mode'){modal('<h2>外部连接与演示模式</h2><p class="muted">'+(server?'本机服务已连接。管理员可以在 Operations 配置 DeepSeek。访客使用部署者提供的访问码，不是 API Key。':'当前是单文件。请解压源码，在项目目录执行 npm start 后，打开 http://127.0.0.1:8787。')+'</p><label>访客访问码（仅本次页面内存）</label><input id="access-input" type="password" autocomplete="off"><button id="save-access">使用访问码</button>');return;}
 if(b.id==='save-access'){access=$('#access-input').value;$('#access-input').value='';$('#modal').close();toast('访问码已保存在当前页面内存。');return;}
 if(b.id==='voice'){if(voice){voice.stop();voice=null;b.textContent='语音输入';return;}if(draft?.battery!==null&&draft?.battery<=5)return toast('低电量时不开启语音');const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('此浏览器不支持语音输入，可以使用系统键盘听写。');if(!window.confirm('浏览器语音服务可能将音频发送给浏览器厂商。是否开始？转写后仍需你点击发送。'))return;voice=new SR();voice.lang='zh-CN';voice.interimResults=false;voice.onresult=x=>{$('#message').value=x.results[0][0].transcript;};voice.onerror=x=>toast('语音未完成：'+x.error);voice.onend=()=>{voice=null;$('#voice').textContent='语音输入';};voice.start();b.textContent='停止听写';return;}
 }catch(err){toast(err.message);}});
(async()=>{view=['sources','research','operations'].includes(location.hash.slice(1))?location.hash.slice(1):'chat';render();if(location.protocol==='file:')return;try{status=await request('/api/status',undefined,AbortSignal.timeout(3500));server=status.server===true;admin=status.admin;if(server)await request('/api/reset',{});}catch(_){server=false;}render();})();
