"""Browser checks run against the real local Node server. No real paid model key."""
import json, pathlib
from playwright.sync_api import sync_playwright
out=pathlib.Path('evidence/v4');out.mkdir(parents=True,exist_ok=True)
checks=[]
def check(name, value):
 assert value, name
 checks.append({'name':name,'passed':True})
with sync_playwright() as p:
 browser=p.chromium.launch(headless=True)
 page=browser.new_page(viewport={'width':1440,'height':1100},device_scale_factor=1)
 page.goto('http://127.0.0.1:8787',wait_until='networkidle')
 page.wait_for_function("document.querySelector('#mode').textContent.includes('本机')")
 check('real Node connection detected','本机' in page.locator('#mode').inner_text())
 page.screenshot(path=str(out/'desktop.png'),full_page=True)
 page.locator('[data-sample]').first.click()
 page.wait_for_selector('#confirm')
 check('numbered requirements created',page.locator('[data-need]').count()>=4)
 check('known airport context is shown','PVG' in page.locator('.draft').inner_text() and 'T2' in page.locator('.draft').inner_text())
 check('user confirmation required before plan',page.locator('.node').count()==0)
 page.locator('#live-consent').uncheck()
 page.locator('#confirm').click()
 page.wait_for_selector('.node')
 page.wait_for_function("document.querySelector('#stop').classList.contains('hidden')")
 check('plan nodes rendered from HTTP stream',page.locator('.node').count()>=3)
 check('per-node audit present',page.locator('.node .audit').count()==page.locator('.node').count())
 page.locator('#compose').evaluate("e=>e.style.visibility='hidden'")
 page.screenshot(path=str(out/'plan.png'),full_page=True)
 page.locator('#compose').evaluate("e=>e.style.visibility=''")
 page.locator('[data-source]').first.click()
 check('source drawer shows provenance',page.locator('#evidence').is_visible() and page.locator('#evidence .meta').count()==1)
 page.locator('#close-evidence').click()
 page.locator('[data-view="sources"]').click()
 page.locator('#source-query').fill('Weixin fee')
 page.locator('#search-sources').click()
 page.wait_for_selector('#source-results [data-source="wechat-fee"]')
 page.locator('#source-results [data-source="wechat-fee"]').click()
 page.locator('#calc-fee').click()
 check('201 RMB Weixin example uses full amount','6.03' in page.locator('#fee-result').inner_text())
 page.locator('#close-evidence').click()
 page.locator('[data-view="operations"]').click()
 page.locator('#password').fill('demo2026')
 page.locator('#login').click()
 page.wait_for_selector('#model-usage')
 check('actual admin login opens operations',page.locator('#save-model').is_enabled())
 page.screenshot(path=str(out/'operations.png'),full_page=True)
 check('audit distinguishes token usage from balance','余额' in page.locator('#content').inner_text())
 page.locator('[data-view="research"]').click()
 check('experience and benchmark views separated','ChinaTravel' in page.locator('#content').inner_text())
 page.locator('[data-view="chat"]').click()
 page.locator('#message').fill('Actually I will arrive in Beijing, battery 3%, no internet.')
 page.locator('#send').click()
 page.wait_for_selector('.help')
 check('low power fallback appears',page.locator('.help').is_visible())
 check('city corrected in same conversation','Beijing' in page.locator('.draft').inner_text())
 page.set_viewport_size({'width':390,'height':844})
 page.locator('#new-chat').evaluate('(e)=>e.click()')
 page.wait_for_selector('.welcome')
 page.screenshot(path=str(out/'mobile.png'),full_page=True)
 check('mobile does not overflow horizontally',page.evaluate('document.documentElement.scrollWidth <= window.innerWidth+2'))
 browser.close()
(out/'browser-report.json').write_text(json.dumps({'checks':checks,'passed':len(checks),'scope':'Real Chromium -> localhost Node server on GitHub runner. Default planning; official refresh disabled for deterministic UI tests. No real DeepSeek key, microphone, booking provider or Vercel deployment.'},ensure_ascii=False,indent=2))
print(json.dumps({'browser_checks':len(checks),'passed':True}))
