/* Original short summaries and source links, not a mirror of publisher articles. */
(function(root,factory){const x=factory();if(typeof module==='object')module.exports=x;else root.ArrivalData=x;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const reviewedAt='2026-09-24';
const sources=[
{id:'wechat-fee',title:'Weixin Pay: international-card service rules',publisher:'Tenpay / 财付通',kind:'operator_primary',city:'China',topics:['payment','wechat','fee','微信','手续费'],url:'https://posts.tenpay.com/posts/9e70c66564910e6002958e997eabb18b.html',published:'2026-01-15',reviewedAt,reviewDays:7,summary:'For eligible international-card payments in Weixin, a transaction of RMB 200 or less is exempt from the international-card service fee. Above RMB 200, the base fee is 3% of the entire transaction. The payment page shows any waiver. On a refund, the related service fee is returned proportionally. This is not a spending limit or an Alipay rule.',summaryZh:'微信外卡单笔不超过200元免国际卡手续费；超过200元时，基础规则按整笔交易金额收取3%，不是只对超出部分收费。支付页面会显示减免；退款时同比例退还手续费。这不是消费上限，也不能直接用于支付宝。',anchors:['200','3%','财付通'],risk:'fee',media:[]},
{id:'pvg-arrival',title:'Pudong: connectivity, cash and one-stop arrival services',publisher:'Shanghai government / Shanghai Airport Group',kind:'government_primary',city:'Shanghai',topics:['airport','cash','currency','sim','wifi','arrival','机场','换汇','网络'],url:'https://english.shanghai.gov.cn/en-Latest-WhatsNew/20260424/88cde5e96ef242daa534102069450a03.html',published:'2026-04-24',reviewedAt,reviewDays:30,summary:'Pudong describes an information point before immigration, a SIM / portable Wi-Fi / exchange service zone in international baggage claim, and an International Services Shanghai center in public arrivals. The public center assists with payment, tourism, communications and transport. These are different access zones; ask staff before following a route. No exact gate, queue or live opening status is asserted here.',summaryZh:'浦东官方资料分别介绍入境检查前的信息点、国际到达行李提取区的通信和换汇服务区，以及公共到达区的一站式服务中心。先确认你所在区域，再请工作人员指路；本卡不编造登机口、排队时长或实时营业状态。',anchors:['Pudong','arrivals','currency'],risk:'location',media:[{url:'https://english.shanghai.gov.cn/cmsres/1e/1e0a561264684a5d90207795cc4bcf52/2382c315a6ba396be1932dd8dafaff52.png',alt:'International Services Shanghai center; publisher photograph, not a live view',rights:'Shanghai Airport Group; external reference, not redistributed'},{url:'https://english.shanghai.gov.cn/cmsres/60/6069e9a661134f64994299d2cbc56759/ce6e2814f207c9333f10785606c57df3.png',alt:'Arrival information point; confirm your access zone',rights:'Shanghai Airport Group; external reference, not redistributed'}]},
{id:'sh-metro',title:'Shanghai Metro: eligible contactless bank cards',publisher:'Shanghai Metro via Shanghai government',kind:'government_primary',city:'Shanghai',topics:['metro','subway','transport','card','地铁','交通'],url:'https://english.shanghai.gov.cn/en-Latest-WhatsNew/20250627/d8f21f2e7d3b45a5b03757e35039b806.html',published:'2025-06-27',reviewedAt,reviewDays:30,summary:'The published network-wide pilot allows eligible contactless bank cards, including specified international card schemes, at Metro gates. Card-chip compatibility, small-amount password-free payment and available funds matter. If a card does not work, ask the station service center or issuer; not every card or phone wallet is guaranteed to work.',summaryZh:'上海地铁公布了全网试点的合资格非接触式银行卡乘车方式，但芯片兼容性、小额免密和可用额度等仍有条件。失败时向车站服务中心或发卡行求助，不保证所有银行卡和手机钱包都可用。',anchors:['contactless','Visa','station'],risk:'transport',media:[{url:'https://english.shanghai.gov.cn/cmsres/b5/b524e6cbb34b4b6ca203fe7fbaadf260/bcc4843d94fb4e2a6e8c919b5acc1673.png',alt:'Publisher photograph of a Shanghai Metro payment gate',rights:'Shanghai Metro; external reference, not redistributed'}]},
{id:'rail-passport',title:'12306: foreign passports and railway e-tickets',publisher:'China Railway 12306',kind:'operator_primary',city:'China',topics:['rail','train','passport','ticket','高铁','火车','护照'],url:'https://www.12306.cn/en/faq.html',published:null,reviewedAt,reviewDays:14,summary:'China Railway explains foreign-passport real-name ticketing and official sales channels. Bring the valid identity document used for the ticket. An itinerary sheet or reimbursement receipt is not itself a ticket. For an existing booking, identify its issuing channel before seeking service. This summary does not restate change/refund fees or resolve conflicting historical child-ticket passages on the FAQ page.',summaryZh:'12306介绍外国护照实名购票和官方渠道；乘车应携带购票时使用的有效证件。行程信息单、报销凭证不等于车票。已有订单先确认出票渠道。本摘要不复述退改费，也不据该页面混合的新旧儿童票段落作资格判断。',anchors:['passports','itinerary sheet'],risk:'transport',media:[]},
{id:'beijing-arrival',title:'Beijing airports: one-stop services and official sub-guides',publisher:'Beijing municipal government',kind:'government_primary',city:'Beijing',topics:['airport','cash','currency','sim','wifi','arrival','机场','换汇','北京'],url:'https://english.beijing.gov.cn/specials/beijingservice/index.html',published:null,reviewedAt,reviewDays:30,summary:'The official Beijing airport-services hub separates Capital (PEK) and Daxing (PKX) services, with links for currency exchange, SIM cards, ATMs, transport and virtual airport tours. Select the correct airport and follow its specific guide; do not transfer a terminal or gate from Shanghai. The hub is an entry point, not a live availability or visa-eligibility decision.',summaryZh:'北京官方机场服务入口区分首都PEK和大兴PKX，并链接换汇、SIM卡、ATM、交通和虚拟机场导览。先选对机场，再看专属指引；不能套用上海航站楼位置。该入口不是实时库存或免签资格裁定。',anchors:['Currency Exchange','PEK','PKX'],risk:'location',media:[]},
{id:'beijing-payment',title:'Guide to Payment Services in Beijing',publisher:'Beijing municipal government',kind:'government_primary',city:'Beijing',topics:['payment','cash','bank','alipay','wechat','支付','现金','北京'],url:'https://english.beijing.gov.cn/specials/paymentservices/',published:null,reviewedAt,reviewDays:30,summary:'This official hub groups payment-service guidance for visitors to Beijing. Use its specific bank, cash and mobile-payment guides to check options. It is not an operator fee contract and does not prove an individual card or transaction will be accepted.',summaryZh:'北京官方支付服务入口汇集银行卡、现金和移动支付指引。它不是钱包运营商收费合同，也不能保证个人交易一定成功。',anchors:['Payment'],risk:'payment',media:[]},
{id:'alipay-app',title:'Alipay: official developer description for foreign visitors',publisher:'Alipay developer listing',kind:'operator_primary',city:'China',topics:['alipay','payment','card','支付宝','绑卡'],url:'https://play.google.com/store/apps/details?hl=en_US&id=com.eg.android.AlipayGphone',published:'2026-09-11',reviewedAt,reviewDays:14,summary:'Alipay says foreign visitors to China can connect a credit card to use its merchant network. This source does not publish the international-card service-fee threshold. The current Alipay operator fee page has not been verified in this project. Check the fee displayed in Alipay before approving a payment; do not substitute the Weixin fee rule.',summaryZh:'支付宝开发者页面说明境外来华访客可关联信用卡，但这个页面没有给出外卡手续费门槛。本项目尚未核实支付宝当前运营商收费条款；请在付款确认页查看，不套用微信规则。',anchors:['Foreign visitors','credit card'],risk:'fee_gap',media:[]}
];
const leads=[
{id:'social-reddit-wallet',platform:'Reddit',url:'https://www.reddit.com/r/chinalife/comments/1pth7yw/am_i_missing_something_with_alipay/',title:'Wallet scanning and setup friction',observedAt:reviewedAt,summary:'A discussion raises confusion about scan-to-pay workflows. Qualitative problem discovery only; not representative prevalence or a fee rule.',status:'experience_lead_not_policy'},
{id:'social-reddit-fees',platform:'Reddit',url:'https://www.reddit.com/r/travelchina/comments/1qwgjuc/wechat_or_alipaywhat_many_travelers_often_get/',title:'Fee threshold misconceptions',observedAt:reviewedAt,summary:'A traveler discussion includes fee interpretations. Its claims must be checked against the wallet operator; never infer exemptions or suggest artificial transaction splitting.',status:'experience_lead_not_policy'},
{id:'social-reddit-help',platform:'Reddit',url:'https://www.reddit.com/r/travelchina/',title:'Public travel questions',observedAt:reviewedAt,summary:'Public community entry point for qualitative research. No complete feed or representative sample has been collected.',status:'discovery_only'},
{id:'student-duke',platform:'University',url:'https://dkurelations.duke.edu/sites/default/files/Alipay-International%20Bank%20Card%20Instructions.pdf',title:'Duke-hosted Alipay student handout',observedAt:reviewedAt,summary:'Institution-hosted historical setup handout; useful for student onboarding research, not a verified current operator fee policy. PDF not ingested in the live HTML pipeline.',status:'historical_secondary'},
{id:'social-x',platform:'X',url:'https://x.com/Alipay',title:'Alipay public profile',observedAt:reviewedAt,summary:'Profile discovered. No post-level corpus collected; login-gated or unavailable content is not bypassed.',status:'discovery_only'}
];
const benchmarks=[
{name:'ChinaTravel',url:'https://www.lamda.nju.edu.cn/shaojj/chinatravel/',use:'Chinese-city travel constraints, feasibility and preference evaluation. Benchmark data are NOT live official service guidance; not counted in the official corpus.'},
{name:'TravelPlanner',url:'https://arxiv.org/abs/2402.01622',use:'Travel planning benchmark with reference intents. Use a held-out evaluation set, not as evidence of current Chinese fees or airport facilities.'},
{name:'Flex-TravelPlanner',url:'https://arxiv.org/abs/2506.04649',use:'Evaluate multi-turn constraint changes. No benchmark run or leaderboard score is claimed by this project.'}
];
return {version:'4.0.0',reviewedAt,sources,leads,benchmarks};
});
