'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const C=require('./core'),D=require('./data'),S=require('./server');
for(const [amount,want]of [[0,0],[199,0],[200,0],[201,6.03],[500,15],[1000,30]])test('Weixin base fee '+amount,()=>assert.equal(C.fee(amount).baseFee,want));
for(const amount of [-1,'no',Infinity,1000001])test('Reject invalid amount '+amount,()=>assert.throws(()=>C.fee(amount)));
test('Redact emails and long card numbers',()=>{const x=C.clean('Contact me at person@example.com and 4111 1111 1111 1111');assert.ok(!x.includes('example.com'));assert.ok(!x.includes('4111'));});
test('Multi-turn city corrections and battery are retained',()=>{const d=C.draft([{text:'I will go to Shanghai and need a train guide'},{text:'Actually I arrive in Beijing. battery 3%, no internet'}],4);assert.equal(d.city,'Beijing');assert.equal(d.battery,3);assert.equal(d.network,'offline');assert.equal(d.revision,4);assert.ok(d.needs.some(x=>x.category==='rail'));});
test('Unknown facts remain unknown',()=>{const d=C.draft([{text:'Hello'}],1);assert.equal(d.city,'Unknown');assert.equal(d.battery,null);assert.equal(d.needs[0].category,'general');});
test('Draft schema rejects unknown category',()=>assert.throws(()=>C.validateDraft({needs:[{category:'wire_money',text:'x'}]},1,{})));
test('Draft schema rejects empty needs',()=>assert.throws(()=>C.validateDraft({needs:[]},1,{})));
test('Requirement text does not introduce a URL',()=>assert.throws(()=>C.validateDraft({needs:[{category:'general',text:'https://evil.example/'}]},1,{})));
test('Correct-city ranking excludes another city',()=>{const r=C.rank('metro','Beijing',D.sources,8);assert.ok(!r.some(x=>x.city==='Shanghai'));});
test('Selected payment sources are operator primary',()=>assert.ok(C.forNeed({category:'payment',text:'fees'},{city:'Shanghai'},D.sources).every(x=>x.kind==='operator_primary')));
test('Past review deadline is explicit',()=>{assert.equal(Boolean(C.current({reviewedAt:'2020-01-01',reviewDays:7},Date.parse('2026-09-24'))),false);});
test('No key model reports unconfigured',()=>assert.equal(S.createModel({}).status().configured,false));
test('Key is never returned by model status',()=>{const m=S.createModel({});m.configure({key:'not-a-real-test-key'});assert.equal(JSON.stringify(m.status()).includes('not-a-real'),false);});
test('Reject arbitrary model IDs',()=>assert.throws(()=>S.createModel({}).configure({model:'whatever'})));
for(const u of ['http://127.0.0.1','https://127.0.0.1/','https://english.shanghai.gov.cn.evil.test/','https://user:pw@english.shanghai.gov.cn/','https://english.shanghai.gov.cn:8443/'])test('Reject SSRF target '+u,()=>assert.throws(()=>S.safeURL(u)));
test('Allow approved official source',()=>assert.equal(S.safeURL(D.sources[0].url).hostname,'posts.tenpay.com'));
test('Robots disallow and longer allow work',()=>{const rb='User-agent: *\nDisallow: /private\nAllow: /private/public\nCrawl-delay: 2';assert.equal(S.robotsAllowed(rb,'https://english.shanghai.gov.cn/private/x').allowed,false);assert.equal(S.robotsAllowed(rb,'https://english.shanghai.gov.cn/private/public/x').allowed,true);assert.equal(S.robotsAllowed(rb,'https://english.shanghai.gov.cn/x').delay,2);});
test('Specific robot group overrides wildcard',()=>{const rb='User-agent: *\nDisallow: /\nUser-agent: VisitChinaResearch\nAllow: /';assert.equal(S.robotsAllowed(rb,D.sources[0].url).allowed,true);});
test('Remove script/style before model context',()=>{const x=S.htmlText('<html><script>malicious_secret()</script><p>Useful traveler instructions here.</p></html>');assert.ok(!x.includes('malicious'));assert.ok(x.includes('Useful'));});
const need={id:'n1',category:'transport',text:'Find transport'},context={language:'en',city:'Shanghai',battery:80};
const ev=[{...D.sources.find(x=>x.id==='sh-metro'),body:'Use an eligible contactless card or ask the station service center.',liveStatus:'fetched'}];
test('Valid source-only node passes shape checks',()=>{const x=C.validateNode({actions:['Ask the station service center.'],source_ids:['sh-metro'],rationale:'Check card eligibility first.'},need,context,ev);assert.equal(x.mode,'deepseek-grounded');assert.equal(x.audit.semantic_accuracy,'not independently evaluated');});
test('Invented citation is rejected',()=>assert.throws(()=>C.validateNode({actions:['Do it'],source_ids:['fake']},need,context,ev)));
test('Invented gate number is rejected',()=>assert.throws(()=>C.validateNode({actions:['Go to gate 57'],source_ids:['sh-metro']},need,context,ev)));
test('Live-source failure cannot substantiate model answer',()=>assert.throws(()=>C.validateNode({actions:['Ask staff'],source_ids:['sh-metro']},need,context,[{...ev[0],body:null,liveStatus:'unavailable'}])));
test('Model output cannot contain arbitrary clickable URL',()=>assert.throws(()=>C.validateNode({actions:['Open https://evil.example'],source_ids:['sh-metro']},need,context,ev)));
test('Low battery returns a non-scanning fallback',()=>{const x=C.fallbackNode(need,{...context,battery:3},ev);assert.match(x.actions[0],/staff/);assert.match(x.actions[0],/Pause/);});
test('Changed source does not reuse reviewed summary',()=>{const x=C.fallbackNode(need,context,[{...ev[0],liveStatus:'changed_or_unmatched'}]);assert.equal(x.audit.evidence_coverage,'evidence_gap');});
test('Provider usage is counted but never treated as balance',async()=>{const fetcher=async()=>new Response(JSON.stringify({choices:[{message:{content:'{"ok":true}'},finish_reason:'stop'}],usage:{prompt_tokens:11,completion_tokens:5,total_tokens:16}}),{status:200,headers:{'content-type':'application/json'}});const m=S.createModel({DEEPSEEK_API_KEY:'test-key'},fetcher);const x=await m.call('JSON',{q:'test'});assert.equal(x.value.ok,true);assert.equal(m.status().totalTokens,16);});
test('Provider 401 does not masquerade as successful generation',async()=>{const m=S.createModel({DEEPSEEK_API_KEY:'test-key'},async()=>new Response('{}',{status:401}));await assert.rejects(m.call('JSON',{}),/DEEPSEEK_HTTP_401/);assert.equal(m.status().failed,1);});
test('Robots refusal does not fetch page',async()=>{let calls=0;const r=S.createRetriever(async()=>{calls++;return new Response('User-agent: *\nDisallow: /',{status:200});});const x=await r.retrieve(D.sources[0]);assert.equal(x.liveStatus,'unavailable');assert.equal(x.error,'ROBOTS_DISALLOWED');assert.equal(calls,1);});
test('Cross-host redirect is stopped',async()=>{let calls=0;const r=S.createRetriever(async u=>{calls++;return String(u).endsWith('robots.txt')?new Response('User-agent: *\nAllow: /',{status:200}):new Response('',{status:302,headers:{location:'https://evil.example/steal'}});});const x=await r.retrieve(D.sources[0]);assert.equal(x.liveStatus,'unavailable');assert.ok(calls<=2);});
async function fixture(){const app=S.createApp({env:{ADMIN_PASSWORD:'test-password'},corpusFile:'/nonexistent'});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port;let cookie='';async function call(p,b,extra={}){const r=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{...(b===undefined?{}:{'content-type':'application/json'}),cookie,...extra},body:b===undefined?undefined:JSON.stringify(b)});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];const raw=await r.text();let data;try{data=JSON.parse(raw);}catch(_){data=raw;}return{status:r.status,data,raw};}return{app,base,call,close:()=>new Promise(resolve=>app.server.close(resolve))};}
test('Real local HTTP: status, auth, consent, confirmation, plan, corrections',async()=>{const f=await fixture();try{let x=await f.call('/api/status');assert.equal(x.status,200);assert.equal(x.data.server,true);assert.equal(x.data.model,null);
 x=await f.call('/api/model-config',{key:'test-key'});assert.equal(x.status,403);
 x=await f.call('/api/plan',{confirmation:'invented'});assert.equal(x.status,409);
 x=await f.call('/api/draft',{message:'Shanghai airport cash and WeChat fee',modelConsent:false});assert.equal(x.status,200);const d=x.data.draft;
 x=await f.call('/api/confirm',{revision:999,selected:['n1']});assert.equal(x.status,409);
 x=await f.call('/api/confirm',{revision:d.revision,selected:['fake']});assert.equal(x.status,400);
 x=await f.call('/api/confirm',{revision:d.revision,selected:d.needs.map(n=>n.id)});assert.equal(x.status,200);const token=x.data.confirmation;
 x=await f.call('/api/plan',{confirmation:token,live:false,modelConsent:false});assert.equal(x.status,200);const stream=x.raw.trim().split('\n').map(JSON.parse);assert.equal(stream[0].type,'started');assert.ok(stream.some(e=>e.type==='node'));assert.equal(stream.at(-1).type,'complete');
 x=await f.call('/api/feedback',{node:d.needs[0].id,outcome:'done'});assert.equal(x.status,200);
 x=await f.call('/api/feedback',{node:d.needs[0].id,outcome:'done'});assert.equal(x.data.deduplicated,true);
 x=await f.call('/api/draft',{message:'Actually Beijing',modelConsent:false});assert.equal(x.data.draft.city,'Beijing');
 x=await f.call('/api/plan',{confirmation:token,live:false});assert.equal(x.status,409);
 x=await f.call('/api/login',{username:'admin',password:'wrong'});assert.equal(x.status,401);
 x=await f.call('/api/login',{username:'admin',password:'test-password'});assert.equal(x.status,200);
 x=await f.call('/api/model-config',{key:'not-a-real-api-key',model:'deepseek-flash'});assert.equal(x.status,200);assert.equal(x.raw.includes('not-a-real'),false);
 x=await f.call('/api/model-config',{clear:true});assert.equal(x.data.configured,false);
 x=await f.call('/api/source-state',{id:'wechat-fee',enabled:false});assert.equal(x.status,200);
 x=await f.call('/api/search?q=Weixin');assert.ok(!x.data.results.some(r=>r.id==='wechat-fee'));
 x=await f.call('/api/admin');assert.equal(x.status,200);assert.ok(x.data.counts.draft_created>=2);
 x=await f.call('/api/draft',{message:'test'},{origin:'https://evil.example'});assert.equal(x.status,403);
 x=await f.call('/api/reset',{});assert.equal(x.status,200);
 }finally{await f.close();}});
test('Another session cannot use a confirmation token',async()=>{const f=await fixture();try{let x=await f.call('/api/draft',{message:'Shanghai train'});x=await f.call('/api/confirm',{revision:x.data.draft.revision,selected:['n1']});const r=await fetch(f.base+'/api/plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({confirmation:x.data.confirmation,live:false})});assert.equal(r.status,409);}finally{await f.close();}});
