from pathlib import Path
import subprocess,json
R=Path(__file__).resolve().parents[1]
BASE='a883f7c9b9157548b7fdaca3cd3c47dc77c45a25'
files=['v5/app.js','v5/build.js','v5/server.js','v5/index.html','v5/recommendation-ui.js','v5/transport-ui.js','v5/style.css','v5/harness.js','v5/ops-api.js','v5/ops-harness-ui.js','v5/v62-browser-fixture.cjs','package.json','package-lock.json']
for p in files:
 before=subprocess.check_output(['git','show',BASE+':'+p],cwd=R)
 assert (R/p).read_bytes()==before,'Baseline changed: '+p

def rep(p,a,b):
 s=(R/p).read_text();assert a in s,(p,a[:80]);(R/p).write_text(s.replace(a,b))
rep('v5/app.js','return state.history.map(h=>{if(',"return state.history.map(h=>{h.answerId||=crypto.randomUUID();if(")
rep('v5/index.html','<script src="product-suggestions.js"></script>','<script src="product-suggestions.js"></script><script src="choice-memory.js"></script>')
rep('v5/index.html','<script src="ops-harness-ui.js"></script>','<script src="skill-presets.js"></script><script src="ops-harness-ui.js"></script>')
rep('v5/index.html','<script src="recommendation-ui.js"></script>','<script src="related-services-ui.js"></script><script src="recommendation-ui.js"></script>')
for p in ['v5/build.js','v5/server.js']:
 for a,b in [('product-suggestions','choice-memory'),('ops-harness-ui','skill-presets'),('recommendation-ui','related-services-ui')]:rep(p,"'"+a+".js',","'"+a+".js','"+b+".js',")
for a,b in [('product-suggestions','choice-memory'),('ops-harness-ui','skill-presets'),('recommendation-ui','related-services-ui')]:rep('v5/build.js',"'"+a+"',","'"+a+"','"+b+"',")
rep('v5/server.js',"if(p==='/api/chat')","if(p==='/api/products')return require('./product-api').createProducts()(req,res);\n  if(p==='/api/chat')")
rep('v5/v62-browser-fixture.cjs',"if(u.pathname==='/api/chat')","if(u.pathname==='/api/products')return require('./product-api').createProducts()(req,res);if(u.pathname==='/api/chat')")
rep('v5/recommendation-ui.js','function products(h){','function products(h){if(window.TravelRelatedServices)return TravelRelatedServices.products(h);')
rep('v5/recommendation-ui.js','window.TravelRecommendationUI={products,events}','window.TravelRecommendationUI={products,events,openOptions:input=>window.TravelRelatedServices?.openOptions(input)}')
for p in ['package.json','package-lock.json']:
 s=(R/p).read_text().replace('"version": "6.5.0"','"version": "6.6.0"');(R/p).write_text(s)
p=R/'package.json';d=json.loads(p.read_text());d['scripts']['test']+=' v5/v66.test.js';p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
rep('v5/build.js',"version:'6.5.0'","version:'6.6.0'")
# Add persistence and query preparation to the existing dated rail comparison.
p=R/'v5/transport-ui.js';s=p.read_text()
s=s.replace("const zh=h.language!=='en',source=","const choiceKey=String(h.answerId||'turn-'+h.revision)+(h.taskIndex!=null?':'+h.taskIndex:''),saved=globalThis.TravelServiceChoices?.get(choiceKey).rail||{},zh=h.language!=='en',source=")
s=s.replace("data-transport-intent=\"'","data-choice-key=\"'+esc(choiceKey)+'\" data-transport-intent=\"'")
s=s.replace('<option value="second">',"<option value=\"second\" '+(saved.seat!=='first'?'selected':'')+'>")
s=s.replace('<option value="first">',"<option value=\"first\" '+(saved.seat==='first'?'selected':'')+'>")
s=s.replace('<option value="price">',"<option value=\"price\" '+(saved.sort!=='departure'?'selected':'')+'>")
s=s.replace('<option value="departure">',"<option value=\"departure\" '+(saved.sort==='departure'?'selected':'')+'>")
s=s.replace("'<option value=\"'+v+'\">'","'<option value=\"'+v+'\" '+((saved.period||'all')===v?'selected':'')+'>'")
s=s.replace('type="time" data-rail-after',"type=\"time\" value=\"'+esc(saved.after||'')+'\" data-rail-after").replace('type="time" data-rail-before',"type=\"time\" value=\"'+esc(saved.before||'')+'\" data-rail-before")
s=s.replace("<div class=\"transport-rows\">'+table(intent,zh,{})","<div class=\"rail-quick-options\">'+[['06:00','12:00','上午 / Morning'],['12:00','18:00','下午 / Afternoon'],['18:00','23:59','晚上 / Evening']].map(([a,b,label])=>'<button data-rail-quick=\"'+a+'|'+b+'\">'+label+'</button>').join('')+'</div><p class=\"rail-validation\" role=\"status\"></p><div class=\"transport-rows\">'+table(intent,zh,saved)")
s=s.replace("<p><a href=\"'+esc(source.url)","<p><button data-rail-prepare class=\"primary\">'+(zh?'用这些时段准备查询':'Prepare a search with these times')+'</button></p><p><a href=\"'+esc(source.url)")
a=s.index("document.addEventListener('change'");b=s.index('window.TravelTransportUI',a)
s=s[:a]+r'''function update(root){const options={seat:root.querySelector('[data-rail-seat]').value,sort:root.querySelector('[data-rail-sort]').value,period:root.querySelector('[data-rail-period]').value,after:root.querySelector('[data-rail-after]').value,before:root.querySelector('[data-rail-before]').value},zh=root.dataset.transportLanguage==='zh';let error='';try{TravelProducts.time(options.after);TravelProducts.time(options.before);if(options.after&&options.before&&options.after>options.before)error=zh?'最早出发不能晚于最晚出发。':'Depart-after cannot be later than depart-before.';}catch(_){error=zh?'请输入有效时间。':'Enter a valid time.';}root.querySelector('.rail-validation').textContent=error;root.querySelector('[data-rail-prepare]').disabled=!!error;if(error)return null;TravelServiceChoices.put(root.dataset.choiceKey,{rail:options});root.querySelector('.transport-rows').innerHTML=table(JSON.parse(root.dataset.transportIntent),zh,options);return options;}
document.addEventListener('change',e=>{if(e.target.matches('[data-rail-seat],[data-rail-sort],[data-rail-period],[data-rail-after],[data-rail-before]'))update(e.target.closest('[data-transport-intent]'));});
document.addEventListener('click',e=>{const b=e.target.closest('[data-rail-quick],[data-rail-prepare]');if(!b)return;const root=b.closest('[data-transport-intent]');if(b.dataset.railQuick){const [after,before]=b.dataset.railQuick.split('|');root.querySelector('[data-rail-after]').value=after;root.querySelector('[data-rail-before]').value=before;root.querySelector('[data-rail-period]').value='all';}const options=update(root);if(b.hasAttribute('data-rail-prepare')&&options){const intent=JSON.parse(root.dataset.transportIntent);TravelRecommendationUI.openOptions({product:'rail',city:intent.city||null,origin:intent.origin,destination:intent.destination,language:root.dataset.transportLanguage,after:options.after,before:options.before,seat:options.seat});}});
'''+s[b:];p.write_text(s)
# Automated candidate evaluation retains defaults, human publication and original prompts.
rep('v5/harness.js',"const crypto=require('node:crypto'),R=require('./rag');","const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),R=require('./rag');")
rep('v5/harness.js','function evaluate(value,records)',r'''function evaluatorHash(){return digest(['harness.js','rag.js','retrieval-plan.js','answer-guard.js','confidence.js','library.js','city-scope.js'].map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,n))).digest('hex')]));}
function corpusHash(records){return digest(records.map(r=>[r.id,r.publicationHash||'',r.active,r.reviewedAt,r.reviewDays,r.content,r.summaryZh,r.summary,r.title,r.city,r.topics,r.appliesTo,r.jurisdiction,r.lastCheck?.status]));}
function evaluate(value,records)''')
rep('v5/harness.js',"corpusHash:digest(records.map(r=>[r.id,r.publicationHash||'',r.active,r.reviewedAt,r.content,r.summaryZh,r.summary]))","corpusHash:corpusHash(records),evaluatorHash:evaluatorHash(),semanticAssessment:'requires-human-replay'")
rep('v5/harness.js',"const test=evaluate(r.config,records);if(test.passed!==test.total||test.corpusHash!==r.evaluation.corpusHash)","const test=evaluate(r.config,records);if(test.passed!==test.total||test.corpusHash!==r.evaluation.corpusHash||test.evaluatorHash!==r.evaluation.evaluatorHash||test.configHash!==r.hash)")
rep('v5/harness.js',"function propose(s,value,actor,records,origin='manual'){",r'''function comparison(baseline,candidate){const base=new Map(baseline.checks.map(x=>[x.id,x.passed]));let improved=0,regressed=0;for(const x of candidate.checks){if(base.get(x.id)===false&&x.passed)improved++;if(base.get(x.id)===true&&!x.passed)regressed++;}return{baselinePassed:baseline.passed,candidatePassed:candidate.passed,total:candidate.total,improved,regressed,scope:'相同关键检索/边界样本；不是独立线上语义评测，也不证明表达收益。'};}
function revalidate(s,id,hash,actor,records){const h=s.harness||=state(s),r=h.candidates.find(x=>x.id===id);if(!r||r.hash!==hash||['published','rolled_back'].includes(r.status))throw Error('SKILL_ACCEPTANCE_REQUIRED');if(h.active.version!==r.baseVersion)throw Error('STALE_BASE');r.evaluationHistory=[...(r.evaluationHistory||[]),{at:r.evaluation.at,passed:r.evaluation.passed,total:r.evaluation.total,evaluatorHash:r.evaluation.evaluatorHash,corpusHash:r.evaluation.corpusHash}].slice(-5);const baseline=evaluate(h.active,records),test=evaluate(r.config,records);r.evaluation=test;r.comparison=comparison(baseline,test);r.status=test.passed===test.total?'accepted':'failed';r.revalidatedBy=actor;r.revalidatedAt=test.at;return r;}
function propose(s,value,actor,records,origin='manual'){''')
rep('v5/harness.js','h.candidates.push(row);','row.comparison=comparison(evaluate(h.active,records),test);h.candidates.push(row);')
rep('v5/harness.js','propose,publish,rollback,observe','propose,publish,revalidate,comparison,evaluatorHash,corpusHash,rollback,observe')
rep('v5/ops-api.js',"'intent-label','skill-loop'].includes","'intent-label','skill-loop','skill-preset','skill-revalidate'].includes")
rep('v5/ops-api.js',"if(b.action==='skill-propose')","if(b.action==='skill-preset')result=H.propose(s,require('./skill-presets').apply(b.preset,H.state(s).active),actor.name,records,'operator-preset:'+b.preset);if(b.action==='skill-revalidate')result=H.revalidate(s,b.id,b.hash,actor.name,records);if(b.action==='skill-propose')")
rep('v5/ops-api.js',"city:['Shanghai','Beijing'].includes(b.city)?b.city:null","city:require('./city-scope').known(b.city)?require('./city-scope').canonical(b.city):null")
p=R/'v5/ops-harness-ui.js';s=p.read_text()
s=s.replace("return evolution(data)+'<div","return evolution(data)+'<section class=\"ops-panel\" id=\"skill-objectives\"><span class=\"eyebrow\">OPERATOR WORKBENCH / 从业务目标开始</span><h3>选择一个优化目标，再看自动验收</h3><div class=\"ops-preset-grid\">'+TravelSkillPresets.list.map(p=>'<button data-skill-preset=\"'+p.id+'\" '+(!admin?'disabled':'')+' title=\"'+esc(p.note)+'\">'+esc(p.name)+'</button>').join('')+'</div><p>手动参数、目标预设、反馈规则和大样本Loop使用同一套候选验收。自动检查通过 ≠ 自动发布，也不等于答案正确。</p><p class=\"skill-acceptance-notice\">发布前核对：实际问法与回答、相关条件是否完整、延迟／成本和回归。生成提示的效果仍需人工或明确授权的模型回放。</p></section><div")
s=s.replace("<p>'+esc(r.evaluation.scope)+'</p>","<p>'+esc(r.evaluation.scope)+'</p><p>同批关键样本：基线 '+(r.comparison?.baselinePassed??'未记录')+' → 候选 '+r.evaluation.passed+'；改善 '+(r.comparison?.improved??'未记录')+'，退化 '+(r.comparison?.regressed??'未记录')+'。表达效果待核对。</p><small>评测器 '+esc(r.evaluation.evaluatorHash?.slice(0,12)||'旧记录，需重跑')+' · 资料 '+esc(r.evaluation.corpusHash.slice(0,12))+'</small>")
s=s.replace("+(admin&&r.status==='accepted'?","+(admin&&!['published','rolled_back'].includes(r.status)?'<button data-skill-revalidate=\"'+r.id+'\" data-hash=\"'+r.hash+'\">重新自动验收</button>':'')+(admin&&r.status==='accepted'?")
s=s.replace("const $=id=>document.getElementById(id);if($('loop-evolution-start'))","const $=id=>document.getElementById(id);for(const b of document.querySelectorAll('[data-skill-preset]'))b.onclick=()=>run({action:'skill-preset',preset:b.dataset.skillPreset},'候选及同批对照已生成；当前线上配置未改变。');for(const b of document.querySelectorAll('[data-skill-revalidate]'))b.onclick=()=>run({action:'skill-revalidate',id:b.dataset.skillRevalidate,hash:b.dataset.hash},'已在当前资料与评测器上重新检查；仍需人工决定发布。');if($('loop-evolution-start'))")
s=s.replace("b.onclick=()=>run({action:'skill-publish',id:b.dataset.skillPublish,hash:b.dataset.hash},'技能版本已发布，下一次回答使用新参数。');","b.onclick=()=>{if(confirm('已查看回放与实际回答？自动检索检查不证明表达和事实正确。确认后发布到后续回答。'))run({action:'skill-publish',id:b.dataset.skillPublish,hash:b.dataset.hash},'技能版本已发布，下一次回答使用新参数。');};")
s=s.replace('<option value="Beijing">Beijing</option>','<option value="Beijing">Beijing</option><option value="Guangzhou">Guangzhou</option><option value="Shenzhen">Shenzhen</option><option value="Hong Kong">Hong Kong</option>');p.write_text(s)
with (R/'v5/style.css').open('a') as f:f.write('''
/* V6.6: task-relevant cards; provider mode remains explicit. */
.extension-heading{display:flex;justify-content:space-between;align-items:start;gap:12px}.extension-heading h4{margin:4px 0 12px}.extension-heading small{letter-spacing:.07em}.service-extension-grid{display:grid!important;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.service-extension{border:1px solid #dedcec;border-radius:14px;padding:14px;background:#fff;min-width:0}.service-extension h5{font-size:15px;margin:6px 0}.service-extension p{font-size:13px;line-height:1.5}.service-extension button{margin:4px 2px 0 0}.extension-category{color:#66549c;font-size:10px;letter-spacing:.12em}.service-extension [aria-pressed=true]{background:#e8f4ee;color:#16533a}#related-services-dialog{max-width:780px;width:calc(100% - 28px);max-height:88vh;padding:24px;border:1px solid #ddd;border-radius:20px;overflow:auto}#related-services-dialog [data-extension-close]{float:right;font-size:22px}.service-request-details{display:grid;grid-template-columns:120px 1fr;gap:6px;margin:16px 0}.service-request-details dd{margin:0;overflow-wrap:anywhere}.rail-quick-options{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0}.rail-validation{color:#a12236}.ops-preset-grid{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.skill-acceptance-notice{background:#f4f3fb;border-left:3px solid #8273ab;padding:12px}.product-suggestions{margin-top:16px;padding:16px;border-radius:16px;background:#f6f5fc}dialog::backdrop{background:rgba(25,25,40,.35)}@media(max-width:480px){.service-extension-grid{grid-template-columns:1fr}.extension-heading{flex-wrap:wrap}#related-services-dialog{padding:16px}.service-request-details{grid-template-columns:95px 1fr}}
''')
Path(__file__).unlink()
print('Readable integration applied. Model prompts/default budgets and speech modules untouched.')
